### ISSUE TITLE
Memory issue? on CoordsExample.swift

### ISSUE THREAD

**Issue by aiaia** [i-schuetz/SwiftCharts#101]
Hello!
I like this Library! Examples are very useful!

Whenever I open [Show touch coords (interactive)] view (CoordsExample.swift), the memory usage keeps going up. 
But if I comment out these lines(line 66-67) in this file,  this does not happen. 

```
                showCoordsLinesLayer.showChartPointLines(chartPoint, chart: chart)
                showCoordsTextLayer.showView(chartPoint: chartPoint, chart: chart)
```

Any idea?

Here's Instruments screenshot. I tried to open/close the view 5 times after 00:30.000
![chk_leaks](https://cloud.githubusercontent.com/assets/3461940/13726467/047e2a26-e90c-11e5-99eb-9ccffda93291.png)

**Comment by i-schuetz** [comment]
Hmm. Have you tried using a weak reference for the layers?

**Comment by aiaia** [comment]
Sorry, I hadn't.
I tried now, but an error occured when creating chart instance, since the layer instance was nil.

Here's what I did.
- To make this debug simple, commented out lines of showCoordsLinesLayer
- line59  changed "let" to "weak var".   ->  weak var showCoordsTextLayer = ChartPointsSingleViewLayer~
- line67 added "!".   ->  showCoordsTextLayer!.showView~
- line100 added "!".   ->  showCoordsTextLayer!

Did I miss something?

**Comment by i-schuetz** [comment]
Ah, no, I meant [here](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/CoordsExample.swift#L65) to add `[weak showCoordsLinesLayer, showCoordsTextLayer] in`. Then in add `?` to the calls `showCoordsLinesLayer?.showChartPointLines(chartPoint, chart: chart)`

**Comment by aiaia** [comment]
It is difficult for me... Do you mean like this?
```
            view.touchHandler = { [weak showCoordsLinesLayer, weak showCoordsTextLayer] in
                showCoordsLinesLayer?.showChartPointLines(chartPoint, chart: chart)
                showCoordsTextLayer?.showView(chartPoint: chartPoint, chart: chart)
            }
```

The memory usage is still the same as before.

**Comment by i-schuetz** [comment]
Is it both lines causing the issue or only 1 of them? It may be also that [this](https://github.com/i-schuetz/SwiftCharts/blob/bd1d5b3f63f7c524004604708ccad9bcd84dd693/SwiftCharts/Layers/ChartShowCoordsLinesLayer.swift#L13) is preventing the chart to be deallocated. You could first determine if one line is enough to cause the issue. Then use an own copy of the layer. In you own copy of `ChartShowCoordsLinesLayer` you can for example make `view` a weak variable and see if this helps. Or remove things until the memory issue disappears to identify what is causing it.

**Comment by aiaia** [comment]
Each line causes this issue.

I will try to fix this, but it seems to take a long time...
Thank you anyway!

**Comment by i-schuetz** [comment]
The parameters also have to be declared as weak (this fixes the issue, just tested it):
```swift
view.touchHandler = {[weak showCoordsLinesLayer, weak showCoordsTextLayer, weak chartPoint, weak chart] in
    guard let chartPoint = chartPoint, chart = chart else {return}
    showCoordsLinesLayer?.showChartPointLines(chartPoint, chart: chart)
    showCoordsTextLayer?.showView(chartPoint: chartPoint, chart: chart)
}
```

**Comment by aiaia** [comment]
I tried new code. It works well! The issue is solved.
Thank you so much!!

**Comment by i-schuetz** [comment]
Great!
