### ISSUE TITLE
Make ChartPointsScatterLayer public?

### ISSUE THREAD

**Issue by marcinwlodarczyk** [i-schuetz/SwiftCharts#102]
Hi again :)
Is there any reason why ChartPointsScatterLayer is not public (along with it's methods and properties) - visible outside swift module?
I would like to create a custom shape that will be rendered in the same way as any other ChartPointsScatterLayer object (like ChartPointsScatterCirclesLayer). However to do so I would like to subclass either ChartPointsScatterCirclesLayer or preferably ChartPointsScatterLayer but then also properties and methods should be public so that I can override them.
Would you accept a change to make them public?

**Comment by i-schuetz** [comment]
Hi,
yes, they all should be public. I'd merge this.
