### ISSUE TITLE
Support for autolayout?

### ISSUE THREAD

**Issue by ogezue** [i-schuetz/SwiftCharts#105]
Is it planned to support autolayout? Or how would you handle that the user can rotate the device?

**Comment by i-schuetz** [comment]
Hi,

You can start with this: https://gist.github.com/i-schuetz/f6e285eb0c86bb831510

Here's a more complex use case (using multiple charts in a stack view) you may want to take a look into it for more details and some corrections of the gist https://github.com/i-schuetz/SwiftCharts/issues/98

**Comment by ogezue** [comment]
Thanks for the faste response. Works like a charm!
