### ISSUE TITLE
best way to draw charts as cards HealthKit style

### ISSUE THREAD

**Issue by robomotic** [i-schuetz/SwiftCharts#107]
Hello there,
what would be the reccomnded way to draw a card style boundary layer as the one in health kit?
I find them very helpful in terms of presenting charts especially if they are stacked.

![healthkitexample](https://cloud.githubusercontent.com/assets/315964/14123896/911a54e6-f5fa-11e5-9d42-9be83e369a40.jpg)

**Comment by i-schuetz** [comment]
Hi there,
I recommend an iOS tutorial, this is quite basic and not related with the charts.
