### ISSUE TITLE
Displaying chart elements using CALayer instead of drawRect

### ISSUE THREAD

**Issue by marcinwlodarczyk** [i-schuetz/SwiftCharts#109]
What do you think about replacing in some places the way how elements of the chart are created so that they are added to the chart as a sublayers instead of drawing them on the context?
The benefit for this will be decreasing memory consumption as well as improving the performance.
E.g. places which I have in mind:
- ChartAxisLayerDefault: drawing axis line, labels, title label
- ChartLabelDrawer: adding CATextLayer instead of drawing text
- ChartDividersLayer

**Comment by i-schuetz** [comment]
I think that would be quite good. Are you going to do it?

**Comment by i-schuetz** [comment]
Hi Marcin,
what happened with this? Not sure how you meant this question, I asked in case your were planning to implement it. I can give it a look but it while take a while as I currently have no time for this.

**Comment by i-schuetz** [comment]
Hi Marcin,
I just noticed your commits - what is the status of this?

**Comment by i-schuetz** [comment]
Hi Marcin :)

I just merged a lot of stuff that was developed in the last months, which is for the most part related with zooming and panning.

Your performance improvements are important now, as core graphic drawings can cause noticeable stuttering, particularly when using dotted guidelines. Using CALayers for at least the guidelines and labels, and some caching functionality would be great.

If you need any help to orientate with the new functionality, just ask. Happy to implement this together.

Thanks!
