### ISSUE TITLE
Axis colors 

### ISSUE THREAD

**Issue by constantineSafronov** [i-schuetz/SwiftCharts#110]
How to hide or change color, or change axis width? http://prntscr.com/amprz6 
I my case i just want to hide them.

chartSettings.axisStrokeWidth - doesn't work.

**Comment by i-schuetz** [comment]
You can set the line color in the axis models, e.g: 
```
let xModel = ChartAxisModel(axisValues: xValues, lineColor: UIColor.cyanColor(), axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings))
```
The axis width can be passed using `chartSettings.axisStrokeWidth`. For the axis width you have to use master, there was a bug with this that was fixed recently.

**Comment by constantineSafronov** [comment]
chartSettings.axisStrokeWidth - doesn't work, but init ChartAxisModel with clear color works well, thank you.

**Comment by i-schuetz** [comment]
You have to use master for the axis stroke width. This doesn't work in 0.3.
```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```
