### ISSUE TITLE
Graph Labels don't appear using quick start instructions: 

### ISSUE THREAD

**Issue by hellyeah** [i-schuetz/SwiftCharts#112]
<img width="487" alt="screenshot 2016-04-07 16 39 37" src="https://cloud.githubusercontent.com/assets/1475361/14368716/954d8386-fced-11e5-9b4b-28ab7e5ab619.png">

**Comment by hellyeah** [comment]
"Don't forget to always keep a strong reference to the chart instance or it will be released, which leads to axis & labels not showing."

Tried the bar graph and it didn't have labels showing either. Guessing this might have something to do with it.

**Comment by hellyeah** [comment]
xTitle and yTitle don't seem to map to anything in Chart.swift

**Comment by i-schuetz** [comment]
It's related, you need to keep a reference to the chart with an instance variable. Like in the examples.

**Comment by hellyeah** [comment]
I wish that that was mentioned closer to the quickstart or in the comments for it. Thanks so much though. We in business!

<img width="487" alt="screenshot 2016-04-08 08 07 40" src="https://cloud.githubusercontent.com/assets/1475361/14383187/6bf5e946-fd61-11e5-9ded-e1ca9fd32e3e.png">
