### ISSUE TITLE
Chart cuts off at ends

### ISSUE THREAD

**Issue by hellyeah** [i-schuetz/SwiftCharts#113]
I've tried adjusting the origin values, height, and width, but no matter what I do the chart gets cut off at the ends.

<img width="359" alt="screenshot 2016-04-08 10 25 12" src="https://cloud.githubusercontent.com/assets/1475361/14386779/39ca99e0-fd74-11e5-997a-68f4722164cf.png">

**Comment by i-schuetz** [comment]
You have to adjust the chart settings, in this case `ChartSettings.top` and `ChartSettings.trailing`.

**Comment by hellyeah** [comment]
`        let chartSettings = ChartSettings()
        chartSettings.leading = 10
        chartSettings.top = 10
        chartSettings.trailing = 10
        chartSettings.bottom = 10
        let chartConfig = ChartConfigXY(
            //**fit ends of graph
            //ChartSettings.top: 20,
            //ChartSettings.trailing: 20
            chartSettings: chartSettings,
            xAxisConfig: ChartAxisConfig(from: 2, to: 14, by: 2),
            yAxisConfig: ChartAxisConfig(from: 0, to: 14, by: 2)
        )`

Would be awesome if chartSettings was included in the quickstart.
