### ISSUE TITLE
Chart inside a UITableViewCell?

### ISSUE THREAD

**Issue by barnaclejive** [i-schuetz/SwiftCharts#114]
Is it possible to place a `Chart` inside a `UITableViewCell`? I have tried it with mixed results, I think mainly due to me not getting the AutoLayout concerns correct. 
When using a `Chart` in a `UIViewController`, it is clear when it is ok to reference the frame of the view the `Chart` is added to (`viewDidLayoutSubviews` or `viewDidAppear`, etc).
However, I am not sure how to do this in a `UITableViewCell`. Do you have any suggestions on the best way to accomplish this? Thanks for the great project.

Long description of what I have tried:
What has worked partially for me is to add a `UIView` (let's call it `chartContainer`) to the cell's content view. `chartContainer` has constraints to pin it on all sides, plus a height  constraint. Then, **after the cell is dequeued I generate the `Chart` using the `chartContainer`'s frame as the `Chart`'s frame and add it as a sub view of `chartContainer`**. What I am seeing that the Chart doesn't really fit in the view properly - it overflows in the same way it would in a UIViewController if added before view layout had been calculated by AutoLayout.

**Comment by i-schuetz** [comment]
Sure. You just need to get the correct bounds. See e.g. [this](http://stackoverflow.com/questions/30248940/detect-final-layout-size-for-view-with-flexible-width-in-uitableviewcell)

**Comment by barnaclejive** [comment]
Ah, there it is, the magical stackoveflow question I was looking for, thanks @i-schuetz.
