### ISSUE TITLE
Line with multiple colors

### ISSUE THREAD

**Issue by hellyeah** [i-schuetz/SwiftCharts#116]
Currently, the way the line is drawn, you only get to choose one color: https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/ChartLineModel.swift#L18

I want the line in the chart to be different colors depending on what the value is for that point. What would be the best way to go about making this change?

**Comment by hellyeah** [comment]
I guess I would need to do it here in the Line Drawer? https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Drawers/ChartDrawerFunctions.swift#L11

That seems like a weird place to be evaluating values though.

**Comment by hellyeah** [comment]
Maybe I could just make it by using multiple lines to generate one line?

`    lines: [
        (chartPoints: [(2.0, 10.6), (4.2, 5.1), (7.3, 3.0), (8.1, 5.5), (14.0, 8.0)], color: UIColor.redColor()),
        (chartPoints: [(2.0, 2.6), (4.2, 4.1), (7.3, 1.0), (8.1, 11.5), (14.0, 3.0)], color: UIColor.blueColor())
    ]`

**Comment by hellyeah** [comment]
Just re-using the ending point as the starting point of the next line and evaluating the values there.

**Comment by hellyeah** [comment]
This approach seems to work for me :)

**Comment by i-schuetz** [comment]
Nothing I can think of, that's the most simple approach and what I'd have suggested.

In case you need more custom logic, you can implement your own `ChartPointsLayer`, maybe using `ChartPointsLineLayer` (which is the layer you are using now) as a guide.
It seems you are using the quick start charts, keep in mind that these work only for very simple use cases. If you need further customisation you should switch to the more "low level" api.

**Comment by anupriya91** [comment]
Hi,
Can you please share any example for the same.
