### ISSUE TITLE
ChartPointsLineTrackerLayer not working?

### ISSUE THREAD

**Issue by meyumeapps** [i-schuetz/SwiftCharts#117]
Hi Ivan,

I've added a tracker so that I can display more info as a user drags or taps the points.

I followed the example and added a ChartPointsLineTrackerLayer to my chart. I also enabled user interaction on the chart.

However, nothing happens when I drag or tap on the chart points.

Is there something else I need to do?

BTW : am running in simulator

Thanks
Scott

**Comment by i-schuetz** [comment]
Have you tried debugging the view hierarchy to see if the tracker view is on top of the chart? Maybe try starting with the provided example and transform it step by step into your current chart to see what causes the issue. If you can narrow it down and come back with more infos I can help further.

**Comment by i-schuetz** [comment]
Would you be able to advance with this? If you have more questions feel free to comment. In case this is a bug it would be good to know the reason.

**Comment by SoRush17** [comment]
Hi. I've same issue here with a little difference. Tapping works perfectly. But dragging fails. It's important to mention that I've used the chart in a UITableViewCell.
