### ISSUE TITLE
How to draw a horizontal line on a bar chart?

### ISSUE THREAD

**Issue by CrashOverride90** [i-schuetz/SwiftCharts#118]
First of all, thank you for the awesome library.

I am having difficult time figuring out how to draw a straight horizontal line on a vertical bar chart at a specific y-axis point. 

Any help will be appreciated. 

Thanks

**Comment by i-schuetz** [comment]
Just create a `ChartPointsViewsLayer` and pass to it a chart point for this location (the x value doesn't matter). In the view generator you receive the screen location of the point and can create a view with the line.

**Comment by CrashOverride90** [comment]
Excellent! Thank you for the pointer. Really appreciate your help. I was able to draw the straight line. Now the last thing i need to do is add text at the end of the line. Any pointers in this regard?

**Comment by Vaibhav43** [comment]
Hi, can you please share the code to create a horizontal layer below the vertical bars in Barchart as below image.
![device-2019-01-02-144148](https://user-images.githubusercontent.com/28993855/50687867-d9d7d080-1048-11e9-8a20-75345d963553.png)
