### ISSUE TITLE
redraw on rotation question

### ISSUE THREAD

**Issue by damer** [i-schuetz/SwiftCharts#12]
New to iOS dev and really like what you've done here.  Just wondering  - what is the best way to deal with a screen rotation  and redrawing a chart with different bounds.  Thanks!

**Comment by i-schuetz** [comment]
You have to listen on orientation change event, [here](http://stackoverflow.com/questions/25666269/ios8-swift-how-to-detect-orientation-change) for example you can see how to do it.

Then, on orientation change:

```swift
        chart?.clearView()
        initChart() // create chart instance and add it's view as a subview
```

You may want to adjust the chart initialization depending on what exactly you need. For example to show more intervals in the x-axis in landscape mode.
