### ISSUE TITLE
Changing color of axis labels

### ISSUE THREAD

**Issue by hellyeah** [i-schuetz/SwiftCharts#120]
I was able to change almost all of the line chart's colors, except for the periodic axis labels. How would you go about doing this? 

<img width="487" alt="screenshot 2016-04-19 16 36 11" src="https://cloud.githubusercontent.com/assets/1475361/14659278/4c198a28-064f-11e6-8a6c-c9782bc23726.png">

Edit: seems like it's done here but I still have no clue how to implement this in my code: https://github.com/i-schuetz/SwiftCharts/blob/c9be2126c375a02b77960f441a79f15a24ce86c9/Examples/Examples/MultipleAxesExample.swift#L82-L107

**Comment by i-schuetz** [comment]
Use `ChartLabelSettings.fontColor`. For more customisation you also can create a `ChartAxisValue` subclass and override `labels`.
