### ISSUE TITLE
Examples sheets currently using 'var' parameters that are deprecated and will be removed in Swift 3 

### ISSUE THREAD

**Issue by mcobbin** [i-schuetz/SwiftCharts#121]
It will nice to have this issue resolved prior to the introduction of Swift 3.

**Comment by i-schuetz** [comment]
Ok, thanks. This is only in a few places and is easy to fix. You're also welcome to do this in case you want to give it a try :) Otherwise I'll do it in the next weeks, not a lot of time right now.
