### ISSUE TITLE
No X/Y Axis example?

### ISSUE THREAD

**Issue by mazurio** [i-schuetz/SwiftCharts#122]
Hi,

At the moment I am playing with showing the graph without Y/X Axis but the padding/margin stays (as the layers are hidden).

Any tips?

**Comment by i-schuetz** [comment]
Hi,
the space is reserved if you pass labels and spacing settings. If you're not going to show labels, the best is that you use a custom axis value class that doesn't return any labels, like here: https://github.com/i-schuetz/SwiftCharts/issues/79. For the spacing settings in the case of y axis you should set `ChartSettings.labelsToAxisSpacingY` to 0. Further you can set the inner margins of the chart to 0, e.g. `ChartSettings.leading`.

This should remove all the spacing. Don't fully remember though, it may me that I'm missing something. In case it doesn't you also can set the inner margins (e.g. `ChartSettings.leading`) to a negative value to move the chart "back".
