### ISSUE TITLE
Improve AutoLayout support

### ISSUE THREAD

**Issue by vkaramov** [i-schuetz/SwiftCharts#123]
When I added Chart.view to my view and setup constraints properly, Chart.view subviews still doesn't have constraints and that's why their layout is incorrect when their superview bounds are changed.

**Comment by i-schuetz** [comment]
Did you already take a look here? https://github.com/i-schuetz/SwiftCharts/issues/105

**Comment by vkaramov** [comment]
Not yet, but it seems to me like a hack. You re-initialize the graph each time the device is rotated.

**Comment by i-schuetz** [comment]
Yes, there's no out of the box support for autolayout yet. The solutions provided are not very elegant but work well and you can put the reinitialisation in a helper class to make it a bit better. There are some architectural changes needed, currently the chart is immutable, and not a view, which is convenient for some things but problematic for others, like autolayout or adding points on the fly. I don't have time for this now but ideas or pull request are welcome.

**Comment by i-schuetz** [comment]
For now the autolayout support will stay like it is.
