### ISSUE TITLE
Draw a dashed area

### ISSUE THREAD

**Issue by LeoTianJLL** [i-schuetz/SwiftCharts#125]
<img width="419" alt="screen shot 2016-05-03 at 7 40 02 pm" src="https://cloud.githubusercontent.com/assets/17267466/14982148/e233dbcc-1166-11e6-9aa2-b6babe9cea55.png">
I want to draw a dashed bar area shown in the picture. Is that possible?

**Comment by i-schuetz** [comment]
Yes, you can orient with this issue https://github.com/i-schuetz/SwiftCharts/issues/69:

> You also can use a layer for the highlighted area between 80 and 140 in the first chart. The quickest approach would be to use also a ChartPointsViewsLayer, pass a dummy chart point to it and generate a view that covers this area. To calculate the frame of this view you would also use modelLocToScreenLoc.

The area in that issue is not dashed, but since you return an `UIView` you can make it look however you want.

**Comment by LeoTianJLL** [comment]
Thank you very much. Finally, I draw a dashed line on the top of returned UIView. And It works now!
