### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by SkateLiu** [i-schuetz/SwiftCharts#127]
I want to ask the y axis shows the numerical is controlled by what?
----------------------------------------------------------------------------------------------
func addline(){
        let chartConfig = ChartConfigXY(
            xAxisConfig: ChartAxisConfig(from: 0, to: 14, by: 2),
            yAxisConfig: ChartAxisConfig(from: 0, to: 14, by: 2)
        )
        
        let chart = LineChart(
            frame: CGRectMake(0, 70, 300, 300),
            chartConfig: chartConfig,
            xTitle: "X axis",
            yTitle: "Y axis",
            lines: [
                (chartPoints: [(1, 5), (3, 3), (5, 6), (8, 10), (9, 14)], color: UIColor.redColor()),
                (chartPoints: [(2, 10), (4, 6), (6, 10), (7, 11), (14, 8)], color: UIColor.blueColor())
            ]
        )
        view.backgroundColor = UIColor.whiteColor();
        self.view.addSubview(chart.view)
    }
----------------------------------------------------------------------------------------------------
   func addPoint(){
        let labelSettings = ChartLabelSettings(font: ExamplesDefaults.labelFont)
        
        let models: [(x: Double, y: Double, type: MyExampleModelDataType)] = [
            (1, 5, .Type0), (3, 3, .Type0), (5, 6, .Type0), (8, 10, .Type0), (9, 14, .Type0), (2,10, .Type1), (4, 6, .Type1), (6, 10, .Type1), (7, 11, .Type1), (14, 8, .Type1)
        ]
        
        let layerSpecifications: [MyExampleModelDataType : (shape: Shape, color: UIColor)] = [
            .Type0 : (.Triangle, UIColor.redColor()),
            .Type1 : (.Square, UIColor.blueColor()),
        ]

        let xValues = 0.stride(through: 14, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}
        let yValues = 0.stride(through: 14, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}

-------------------------------------------
##The above is my code, want to ask why don't y axis has been aligned?
![b6a9e4b5-24b3-4b6f-8b90-2c97f5e0c8b6](https://cloud.githubusercontent.com/assets/16147192/15067444/008f8448-13a3-11e6-95cc-71f66564bc64.png)

**Comment by SkateLiu** [comment]
Ah, I recently started learning swift, so really don't know how to solve some problems, hope to get your help very much, as the above diagram, draw the coordinates of points are right, but the straight line coordinates has been wrong

**Comment by i-schuetz** [comment]
How are you combining them? I see you are using on one side the convenience line chart and you add the points as (?) Are you using 2 charts? Can you post the complete code?
