### ISSUE TITLE
Remake data in bubbleExample

### ISSUE THREAD

**Issue by pqhuy87it** [i-schuetz/SwiftCharts#130]
i see the chart's data was setup in let rawData: [(Double, Double, Double, UIColor)], so how can i remake data for chart ?

**Comment by i-schuetz** [comment]
Not sure I fully understand the question, but I'll guess.

You just need something that can be mapped to:

```swift
let chartPoints: [ChartPointBubble] = rawData.map{ChartPointBubble(x: ChartAxisValueDouble($0, labelSettings: labelSettings), y: ChartAxisValueDouble($1), diameterScalar: $2, bgColor: $3)}
```
where `$0` is the x coordinate, `$1` the y coordinate, `$2` the diameter of the bubble and `$3` the color.

Then you also have to ensure the axes values have the appropiate range, either by setting it manually like in the example

```swift
let xValues = (-2).stride(through: 14, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}
let yValues = (-2).stride(through: 12, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}
```
Or deriving it from the chart points, like [here](https://github.com/i-schuetz/SwiftCharts/blob/c9be2126c375a02b77960f441a79f15a24ce86c9/Examples/Examples/CoordsExample.swift#L23)

**Comment by pqhuy87it** [comment]
let me explain, i have much data of chart, i want to change new data for chart and  create animation for the changing data in chart. So i don't want remove current chart and create a new, just add new data to the chart.

**Comment by i-schuetz** [comment]
Ah, ok. The charts currently are immutable. Reinitialising the chart usually works flawlessly but of course not if you want to animate the changes. It shouldn't be very difficult to modify the library to support mutability, is case you feel like digging a bit deeper.

**Comment by pqhuy87it** [comment]
ok thank you for answer.
