### ISSUE TITLE
When using Chinese language labels in ChartAxisLayer are cut

### ISSUE THREAD

**Issue by WojciechTrzasko** [i-schuetz/SwiftCharts#134]
Hi,

First of all, thanks for great library :). We are using it in our project and we loves it :).

But in past few days we founded a small bug and we probably will need some help from your side to fix it. Mainly we have a problem rendering axis labels when using Chinese language. Screenshot below shows how it looks.

![labels-chinese](https://cloud.githubusercontent.com/assets/1029858/16033706/d17e7ae0-320d-11e6-9227-ae983010bc8d.jpg)

When using other languages, everything is ok. Example for English version:

![labels-english](https://cloud.githubusercontent.com/assets/1029858/16033718/dffc8e36-320d-11e6-9d20-0a020a4187cf.jpg)

Here is some code that we use for creating those labels:

```
let coordsSpaceForLabels = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: chartSettings, chartFrame: chartFrame, xModel: xModelForLabels, yModel: yModel)
return [coordsSpaceForLabels.xAxis]
```

After some investigation, I found that you are using `ChartUtils.textSize(font:)` method in `ChartAxisLabel` class. That method always returns same height for text, regardless of selected language and as you can see at screenshot, text for Chinese is a little bit bigger.

I'm still not 100% sure that this is source of a bug, but maybe somehow this will be helpful.
What do you think? :)

**Comment by i-schuetz** [comment]
Why did you close this?
I haven't had the time to look into this. I'm happy to merge a pull request. Otherwise if it's still an issue it should be kept open until it's fixed (even if that takes long).

**Comment by i-schuetz** [comment]
Hello,

I finally came back to this and wasn't able to reproduce it.

I remember when you opened the question, I saw something saying that it may be a bug in iOS. Was it maybe fixed in the meantime? Were you able to solve it?
