### ISSUE TITLE
how to put stack bar in library into a subview

### ISSUE THREAD

**Issue by ElaneirzGard** [i-schuetz/SwiftCharts#135]
I use pod install to load library, then copy code of StackedBarsExample.swift to paste in ViewContoller.
And I copy code of ExamplesDefaults.swift and Env.swift to paste in my Xcode project.
It can be run.

Objective: I want to put this stack bar into a subview in ViewController. This name of this subview is subviewForGraph. I don't know how to put stack bar into this subview(subviewForGraph).

>> subviewForGraph is a view that I drag from right-bottom window in Xcode.

**Comment by i-schuetz** [comment]
Here's an example with autolayout :) https://gist.github.com/i-schuetz/f6e285eb0c86bb831510

**Comment by ElaneirzGard** [comment]
Could you tell me detail or point to part of code that is an answer? :)
TT It is hard for me

**Comment by ElaneirzGard** [comment]
I cannot run https://gist.github.com/i-schuetz/f6e285eb0c86bb831510

**Comment by ElaneirzGard** [comment]
I cannot run because in 

public init(view: ChartView, layers: [ChartLayer]) {
        
        self.layers = layers
        
        self.view = view
        self.view.chart = self
        
        for layer in self.layers {
            layer.chartInitialized(chart: self)
        }
        
        self.view.setNeedsDisplay()
    }

error on  self.view.chart = self

**Comment by ElaneirzGard** [comment]
I got 

2016-06-15 16:40:38.268 testChart2[9151:236254] Unknown class ChartBaseView in Interface Builder file.
2016-06-15 16:40:40.482 testChart2[9151:236254] Unknown class ChartBaseView in Interface Builder file.
2016-06-15 16:40:40.491 testChart2[9151:236254] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x7920abd0 H:[UIView:0x79210c60(600)]>",
    "<NSLayoutConstraint:0x7863ecb0 UIView:0x79210c60.centerX == UIView:0x791126e0.centerX>",
    "<NSLayoutConstraint:0x78655640 UIView:0x79210c60.leading == UIView:0x791126e0.leadingMargin - 20>",
    "<NSLayoutConstraint:0x78661e20 'UIView-Encapsulated-Layout-Width' H:[UIView:0x791126e0(320)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7920abd0 H:[UIView:0x79210c60(600)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
(lldb)

**Comment by ElaneirzGard** [comment]
Ok I can run it 
Just I add module.
Previously I just added Class: ChartBaseView and did not add module: SwiftCharts.
![screen shot 2559-06-15 at 4 57 50 pm](https://cloud.githubusercontent.com/assets/17084433/16075815/98d01600-331a-11e6-85a7-f1cde174decf.png)

**Comment by ElaneirzGard** [comment]
thank you ^^

**Comment by ElaneirzGard** [comment]
now I am apply with Stack Bar

**Comment by ElaneirzGard** [comment]
//
//  ViewController.swift
//  testChart2
//
//  Created by Elaneirz on 6/15/2559 BE.
//  Copyright © 2559 Elaneirz. All rights reserved.
//

import UIKit
import SwiftCharts

class ViewController: UIViewController {
    
       @IBOutlet weak var subviewForGraph: ChartBaseView!
    private var chart: Chart? // arc
    private var didLayout: Bool = false
    
    // sideSelectorHeight =  change height that start graph
    let sideSelectorHeight: CGFloat = 50
    
    private func chart(horizontal horizontal: Bool) -> Chart {
        //let labelSettings = ChartLabelSettings(font: ExamplesDefaults.labelFont)
        let labelSettings = ChartLabelSettings(font: ExamplesDefaults.fontWithSize(10),fontColor: UIColor.purpleColor())
        
        let color0 = UIColor.redColor().colorWithAlphaComponent(0.6)
        let color1 = UIColor.greenColor().colorWithAlphaComponent(0.6)
        //let color2 = UIColor.redColor().colorWithAlphaComponent(0.6)
        //let color3 = UIColor.greenColor().colorWithAlphaComponent(0.6)
        
        let zero = ChartAxisValueDouble(0)
        let barModels = [
            ChartStackedBarModel(constant: ChartAxisValueString("SU", order: 1, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 2, bgColor: color0),
                ChartStackedBarItemModel(quantity: 5, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 30, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 20, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("MO", order: 2, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 3, bgColor: color0),
                ChartStackedBarItemModel(quantity: 7, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 10, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 30, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("TU", order: 3, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 20, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 10, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("WE", order: 4, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 2, bgColor: color0),
                ChartStackedBarItemModel(quantity: 6, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 50, bgColor: color2),
                // ChartStackedBarItemModel(quantity: 5, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("TH", order: 5, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 20, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 10, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("FR", order: 6, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 20, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 10, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("SA", order: 7, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 20, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 10, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("SU", order: 8, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 2, bgColor: color0),
                ChartStackedBarItemModel(quantity: 5, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 30, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 20, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("MO", order: 9, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 3, bgColor: color0),
                ChartStackedBarItemModel(quantity: 7, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 10, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 30, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("TU", order: 10, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 20, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 10, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("WE", order: 11, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 2, bgColor: color0),
                ChartStackedBarItemModel(quantity: 6, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 50, bgColor: color2),
                // ChartStackedBarItemModel(quantity: 5, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("TH", order: 12, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 20, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 10, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("FR", order: 13, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 20, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 10, bgColor: color3)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("SA", order: 14, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                //ChartStackedBarItemModel(quantity: 20, bgColor: color2),
                //ChartStackedBarItemModel(quantity: 10, bgColor: color3)
                ])
            
        ]
        
        // order in this should -1 in first, +1 in last
        // through define scale of graph
        let (axisValues1, axisValues2) = (
            0.stride(through: 12, by: 1).map {ChartAxisValueDouble(Double($0), labelSettings: labelSettings)},
            [ChartAxisValueString("", order: 0, labelSettings: labelSettings)] + barModels.map{$0.constant} + [ChartAxisValueString("", order: 15, labelSettings: labelSettings)]
        )
        let (xValues, yValues) = horizontal ? (axisValues1, axisValues2) : (axisValues2, axisValues1)
        
        let xModel = ChartAxisModel(axisValues: xValues, axisTitleLabel: ChartAxisLabel(text: "Days", settings: labelSettings))
        let yModel = ChartAxisModel(axisValues: yValues, axisTitleLabel: ChartAxisLabel(text: "Hours", settings: labelSettings.defaultVertical()))
        
        let frame = ExamplesDefaults.chartFrame(self.view.bounds)
//        let chartFrame = self.chart?.frame ?? CGRectMake(frame.origin.x, frame.origin.y, frame.size.width, frame.size.height - sideSelectorHeight)
        let chartFrame = self.subviewForGraph.frame
        //let chartFrame = self.subviewForGraph.bounds
        let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: ExamplesDefaults.chartSettings, chartFrame: chartFrame, xModel: xModel, yModel: yModel)
        let (xAxis, yAxis, innerFrame) = (coordsSpace.xAxis, coordsSpace.yAxis, coordsSpace.chartInnerFrame)
        
        // barWidth
        let chartStackedBarsLayer = ChartStackedBarsLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, barModels: barModels, horizontal: horizontal, barWidth: 10, animDuration: 0.5)
        
        
        // settings is guidelines
        let settings = ChartGuideLinesDottedLayerSettings(linesColor: UIColor.redColor(), linesWidth: ExamplesDefaults.guidelinesWidth)
        let guidelinesLayer = ChartGuideLinesDottedLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, settings: settings)
        
        return Chart(
            view: self.subviewForGraph!,
            layers: [
                xAxis,
                yAxis,
                guidelinesLayer,
                chartStackedBarsLayer
            ]
        )
    }
    
    //    private func showChart(horizontal horizontal: Bool) {
    //        self.chart?.clearView()
    //
    //        let chart = self.chart(horizontal: horizontal)
    //        self.view.addSubview(chart.view)
    //        self.chart = chart
    //    }
    
    private func showChart(horizontal horizontal: Bool) {
        self.chart?.clearView()
        
        let chart = self.chart(horizontal: horizontal)
        self.view.addSubview(chart.view)
        self.chart = chart
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.showChart(horizontal: false) // true = first express is horizatal, false = vertical
        if let chart = self.chart {
            let sideSelector = DirSelector(frame: CGRectMake(0, chart.frame.origin.y + chart.frame.size.height, self.view.frame.size.width, self.sideSelectorHeight), controller: self)
            self.view.addSubview(sideSelector)
        }
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        if !self.didLayout {
            self.didLayout = true
            self.initChart()
        }
    }
    private func initChart() {
        chart(horizontal:false)
    }
    
    class DirSelector: UIView {
        
        let horizontal: UIButton
        let vertical: UIButton
        
        
        weak var controller: ViewController?
        
        private let buttonDirs: [UIButton : Bool]
        
        init(frame: CGRect, controller: ViewController) {
            
            self.controller = controller
            
            self.horizontal = UIButton()
            self.horizontal.setTitle("Horizontal", forState: .Normal)
            self.vertical = UIButton()
            self.vertical.setTitle("Vertical", forState: .Normal)
            
            self.buttonDirs = [self.horizontal : true, self.vertical : false]
            
            super.init(frame: frame)
            
            self.addSubview(self.horizontal)
            self.addSubview(self.vertical)
            
            for button in [self.horizontal, self.vertical] {
                button.titleLabel?.font = ExamplesDefaults.fontWithSize(14)
                button.setTitleColor(UIColor.blueColor(), forState: .Normal)
                button.addTarget(self, action: #selector(DirSelector.buttonTapped(_:)), forControlEvents: .TouchUpInside)
            }
            
            // add by myself
            self.horizontal.hidden = true
            self.vertical.hidden = true
            // end add by myself
        }
        
        func buttonTapped(sender: UIButton) {
            let horizontal = sender == self.horizontal ? true : false
            controller?.showChart(horizontal: horizontal)
        }
        
        override func didMoveToSuperview() {
            let views = [self.horizontal, self.vertical]
            for v in views {
                v.translatesAutoresizingMaskIntoConstraints = false
            }
            
            let namedViews = views.enumerate().map{index, view in
                ("v\(index)", view)
            }
            
            var viewsDict = Dictionary<String, UIView>()
            for namedView in namedViews {
                viewsDict[namedView.0] = namedView.1
            }
            
            let buttonsSpace: CGFloat = Env.iPad ? 20 : 10
            
            let hConstraintStr = namedViews.reduce("H:|") {str, tuple in
                "\(str)-(\(buttonsSpace))-[\(tuple.0)]"
            }
            
            let vConstraits = namedViews.flatMap {NSLayoutConstraint.constraintsWithVisualFormat("V:|[\($0.0)]", options: NSLayoutFormatOptions(), metrics: nil, views: viewsDict)}
            
            self.addConstraints(NSLayoutConstraint.constraintsWithVisualFormat(hConstraintStr, options: NSLayoutFormatOptions(), metrics: nil, views: viewsDict)
                + vConstraits)
        }
        
        required init(coder aDecoder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
    }
}

BUT ITS RESULT HAPPENS

![simulator screen shot jun 15 2559 be 5 20 08 pm](https://cloud.githubusercontent.com/assets/17084433/16076432/841717ec-331d-11e6-93f4-7be87533579d.png)

**Comment by ElaneirzGard** [comment]
Now I can put stack bar into a subview.
but width of stack bar is not in subview.

code:
//
//  ViewController.swift
//  testChart2
//
//  Created by Elaneirz on 6/15/2559 BE.
//  Copyright © 2559 Elaneirz. All rights reserved.
//

import UIKit
import SwiftCharts

class ViewController: UIViewController {
    
    @IBOutlet weak var subviewForGraph: ChartBaseView!
    private var chart: Chart? // arc
    private var didLayout: Bool = false
    
    // sideSelectorHeight =  change height that start graph
    let sideSelectorHeight: CGFloat = 300
    
    private func chart(horizontal horizontal: Bool) -> Chart {
        //let labelSettings = ChartLabelSettings(font: ExamplesDefaults.labelFont)
        let labelSettings = ChartLabelSettings(font: ExamplesDefaults.fontWithSize(10),fontColor: UIColor.purpleColor())
        
        let color0 = UIColor.redColor().colorWithAlphaComponent(0.6)
        let color1 = UIColor.greenColor().colorWithAlphaComponent(0.6)
        
        let zero = ChartAxisValueDouble(0)
        let barModels = [
            ChartStackedBarModel(constant: ChartAxisValueString("SU", order: 1, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 2, bgColor: color0),
                ChartStackedBarItemModel(quantity: 5, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("MO", order: 2, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 3, bgColor: color0),
                ChartStackedBarItemModel(quantity: 7, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("TU", order: 3, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("WE", order: 4, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 2, bgColor: color0),
                ChartStackedBarItemModel(quantity: 6, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("TH", order: 5, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("FR", order: 6, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("SA", order: 7, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("SU", order: 8, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 2, bgColor: color0),
                ChartStackedBarItemModel(quantity: 5, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("MO", order: 9, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 3, bgColor: color0),
                ChartStackedBarItemModel(quantity: 7, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("TU", order: 10, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("WE", order: 11, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 2, bgColor: color0),
                ChartStackedBarItemModel(quantity: 6, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("TH", order: 12, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("FR", order: 13, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                ]),
            ChartStackedBarModel(constant: ChartAxisValueString("SA", order: 14, labelSettings: labelSettings), start: zero, items: [
                ChartStackedBarItemModel(quantity: 1, bgColor: color0),
                ChartStackedBarItemModel(quantity: 4, bgColor: color1)
                ])
        ]
        
        // order in this should -1 in first, +1 in last
        // through define scale of graph
        
        // comment code
//        let (axisValues1, axisValues2) = (
//            0.stride(through: 12, by: 1).map {ChartAxisValueDouble(Double($0), labelSettings: labelSettings)},
//            [ChartAxisValueString("", order: 0, labelSettings: labelSettings)] + barModels.map{$0.constant} + [ChartAxisValueString("", order: 15, labelSettings: labelSettings)]
//        )
//        let (xValues, yValues) = horizontal ? (axisValues1, axisValues2) : (axisValues2, axisValues1)
//        
//        let xModel = ChartAxisModel(axisValues: xValues, axisTitleLabel: ChartAxisLabel(text: "Days", settings: labelSettings))
//        let yModel = ChartAxisModel(axisValues: yValues, axisTitleLabel: ChartAxisLabel(text: "Hours", settings: labelSettings.defaultVertical()))
        // end comment code
        
        
        
        // define x and y axis values (quick-demo way, see other examples for generation based on chartpoints)
        let xValues = [ChartAxisValueString("", order: 0, labelSettings: labelSettings)] + barModels.map{$0.constant} + [ChartAxisValueString("", order: 15, labelSettings: labelSettings)]
        let yValues = 0.stride(through: 12, by: 1).map {ChartAxisValueInt($0, labelSettings: labelSettings)}
        
        // create axis models with axis values and axis title
        let xModel = ChartAxisModel(axisValues: xValues, axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings))
        let yModel = ChartAxisModel(axisValues: yValues, axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings.defaultVertical()))
        
        
//        let frame = ExamplesDefaults.chartFrame(self.subviewForGraph.bounds)
//        let chartFrame = self.chart?.frame ?? CGRectMake(frame.origin.x, frame.origin.y, frame.size.width, frame.size.height - sideSelectorHeight)
        let chartFrame = self.subviewForGraph.frame
        //let chartFrame = self.subviewForGraph.bounds
        
        
      
        
        
        let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: ExamplesDefaults.chartSettings, chartFrame: chartFrame, xModel: xModel, yModel: yModel)
        let (xAxis, yAxis, innerFrame) = (coordsSpace.xAxis, coordsSpace.yAxis, coordsSpace.chartInnerFrame)
        
        // barWidth
        let chartStackedBarsLayer = ChartStackedBarsLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, barModels: barModels, horizontal: horizontal, barWidth: 10, animDuration: 0.5)
        
         
        
        
        // settings is guidelines
        let settings = ChartGuideLinesDottedLayerSettings(linesColor: UIColor.redColor(), linesWidth: ExamplesDefaults.guidelinesWidth)
        let guidelinesLayer = ChartGuideLinesDottedLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, settings: settings)
        
        return Chart(
            view: self.subviewForGraph!,
            layers: [
                xAxis,
                yAxis,
                guidelinesLayer,
                chartStackedBarsLayer
            ]
        )
    }
    
    
    private func showChart(horizontal horizontal: Bool) {
        self.chart?.clearView()
        
        let chart = self.chart(horizontal: horizontal)
        self.view.addSubview(chart.view)
        self.chart = chart
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.subviewForGraph.backgroundColor = UIColor.yellowColor()
        self.showChart(horizontal: false) // true = first express is horizatal, false = vertical
        if let chart = self.chart {
            let sideSelector = DirSelector(frame: CGRectMake(0, chart.frame.origin.y + chart.frame.size.height, self.view.frame.size.width, self.sideSelectorHeight), controller: self)
            self.view.addSubview(sideSelector)
        }
    }
    
//    override func viewDidLayoutSubviews() {
//        super.viewDidLayoutSubviews()
//        
//        if !self.didLayout {
//            self.didLayout = true
//            self.initChart()
//        }
//    }
//    private func initChart() {
//        chart(horizontal:false)
//    }
    
    class DirSelector: UIView {
        
        let horizontal: UIButton
        let vertical: UIButton
        
        
        weak var controller: ViewController?
        
        private let buttonDirs: [UIButton : Bool]
        
        init(frame: CGRect, controller: ViewController) {
            
            self.controller = controller
            
            self.horizontal = UIButton()
            self.horizontal.setTitle("Horizontal", forState: .Normal)
            self.vertical = UIButton()
            self.vertical.setTitle("Vertical", forState: .Normal)
            
            self.buttonDirs = [self.horizontal : true, self.vertical : false]
            
            super.init(frame: frame)
            
            self.addSubview(self.horizontal)
            self.addSubview(self.vertical)
            
            for button in [self.horizontal, self.vertical] {
                button.titleLabel?.font = ExamplesDefaults.fontWithSize(14)
                button.setTitleColor(UIColor.blueColor(), forState: .Normal)
                button.addTarget(self, action: #selector(DirSelector.buttonTapped(_:)), forControlEvents: .TouchUpInside)
            }
            
            // add by myself
            self.horizontal.hidden = true
            self.vertical.hidden = true
            // end add by myself
        }
        
        func buttonTapped(sender: UIButton) {
            let horizontal = sender == self.horizontal ? true : false
            controller?.showChart(horizontal: horizontal)
        }
        
        override func didMoveToSuperview() {
            let views = [self.horizontal, self.vertical]
            for v in views {
                v.translatesAutoresizingMaskIntoConstraints = false
            }
            
            let namedViews = views.enumerate().map{index, view in
                ("v\(index)", view)
            }
            
            var viewsDict = Dictionary<String, UIView>()
            for namedView in namedViews {
                viewsDict[namedView.0] = namedView.1
            }
            
            let buttonsSpace: CGFloat = Env.iPad ? 20 : 10
            
            let hConstraintStr = namedViews.reduce("H:|") {str, tuple in
                "\(str)-(\(buttonsSpace))-[\(tuple.0)]"
            }
            
            let vConstraits = namedViews.flatMap {NSLayoutConstraint.constraintsWithVisualFormat("V:|[\($0.0)]", options: NSLayoutFormatOptions(), metrics: nil, views: viewsDict)}
            
            self.addConstraints(NSLayoutConstraint.constraintsWithVisualFormat(hConstraintStr, options: NSLayoutFormatOptions(), metrics: nil, views: viewsDict)
                + vConstraits)
        }
        
        required init(coder aDecoder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }
    }
}

![simulator screen shot jun 16 2559 be 11 07 58 am](https://cloud.githubusercontent.com/assets/17084433/16105215/9ac1c93e-33b2-11e6-886c-342b679362d5.png)

**Comment by i-schuetz** [comment]
Looks autolayout related, your view seem to be stretching past the right boundary. Have you debugged the view hierarchy? Or draw a border around the view to see where it ends?

**Comment by i-schuetz** [comment]
You're showing the chart in `viewDidLoad` which doesn't work with autolayout since the frame hasn't been calculated yet. You should use `viewDidLayoutSubviews` or `viewDidAppear`.

**Comment by ElaneirzGard** [comment]
Thank you
