### ISSUE TITLE
ChartPointsLineLayer not showing dashed lines from generator. 

### ISSUE THREAD

**Issue by wsdwsd0829** [i-schuetz/SwiftCharts#136]
Hi, I was trying to create a dashed line using ChartPointsLineLayer. I see the code is using ChartLinesView which call generateLayer with the path created by a view generator. However, the CAShapeLayer kind of blocking the dashed path from view generator.  I tried to add lineLayer.setDashPattern(..) in generateLayer.  It works. Since it's not proper to change pod codes in project. Is it better way to do it? (I tried to subclass, the hierarchy, but some display method is not public, which makes hard to get around this) 

Thanks, 
Max

**Comment by i-schuetz** [comment]
I'd add an optional property `dashPattern` (with default nil parameter) to `ChartLineModel` and pass it around to the view like e.g. the line color. A pull request with this would be nice, I'd merge it quickly so you can just link to master.

It would also be good to be able to subclass, maybe I forgot some public accessors, if you want to improve this in a separate pull request it would also be nice :)

**Comment by i-schuetz** [comment]
Actually, it would be good to know why the layer isn't displaying the dashed path. Could you post code to reproduce this?

**Comment by wsdwsd0829** [comment]
Hi, I made pull request, the first commit you can see the problem, second commit is my fix.

**Comment by wsdwsd0829** [comment]
I was not able to figure out reason.  (I am  assuming when BezierPath.CGPath assign to CAShapeLayer.path, the pattern information get lost)
I am not sure if it's the best way.
