### ISSUE TITLE
Chart inside UICollectionViewCell is not fitting

### ISSUE THREAD

**Issue by Instadex** [i-schuetz/SwiftCharts#139]
Hi

I am displaying chart in UICollectionViewCell on a subview and setting the chartframe as cell.subview.bounds but it doesn't fit in that subview. 

It's having  chartSize = (width = 183, height = 55)
  chartInnerFrame = (origin = (x = 41.35302734375, y = 10), size = (width = 131.64697265625, height = -10.649999999999999))
Does chartInnerFrame have to do something with this, because it is not drawing the chart within the specified chartSize.

![fullsizerender](https://cloud.githubusercontent.com/assets/20140833/16356742/db8e0e96-3b00-11e6-97a9-d163f64bf3e4.jpg)

**Comment by i-schuetz** [comment]
Probably the final size of the cell hasn't been calculated when passing the frame to the chart? The inner frame is where the chart's contents (inside the axes) is displayed, if the height is -10 it means there's something wrong with the frame. You also could use autolayout https://gist.github.com/i-schuetz/f6e285eb0c86bb831510

**Comment by Instadex** [comment]
Thanks, it helped. Issue resolved by setting layout and updating them before cell loads.
