### ISSUE TITLE
how to change X axis to be String in BarChart.

### ISSUE THREAD

**Issue by ElaneirzGard** [i-schuetz/SwiftCharts#140]

**Comment by i-schuetz** [comment]
https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/NotNumericExample.swift

**Comment by ElaneirzGard** [comment]
Oh Thankyou. 
Could you tell me that how to change X axis to be String in CandkeStick.?

**Comment by i-schuetz** [comment]
Just use the axis from the example in candle stick. The x axis there is basically already strings (formatted dates). What matters is only that the internal number (scalar), which all axis values have, corresponds to your modal data / chart points.

**Comment by ElaneirzGard** [comment]
I don't understand. The x axis there is basically already strings (formatted dates). I want to change to String that is not formatted dates. how to do that?

**Comment by i-schuetz** [comment]
Could you solve this?
