### ISSUE TITLE
How to change the color of barchart

### ISSUE THREAD

**Issue by chandansingh5** [i-schuetz/SwiftCharts#141]
How can I change the color of bar for each index like in the attached screenshot.  I am using ChartPointViewBar to generate the barchart but it has a option to change the color of all the bars.
 
![screen shot 2016-07-01 at 5 56 03 pm](https://cloud.githubusercontent.com/assets/12164119/16521546/2bfea210-3fb5-11e6-9c3d-6a926b3f6f4e.png)

**Comment by i-schuetz** [comment]
`ChartPointViewBar` has a `bgColor` field you can set for this (just noticed there's no reason for this field to exist, it would be better to just set directly `backgroundColor` of the view. But for now it's what you have to use to set it).

**Comment by chandansingh5** [comment]
It is only accepting the last color value in bgColor, not updating the colors specified in code. And can we add a label next to ChartGuideLinesForValuesDottedLayer, where the line ends.

**Comment by i-schuetz** [comment]
Sure, you can request the screen locations from the axis layers `ChartAxisLayer.axisValuesScreenLocs` and depending where the label has to be maybe also add `innerFrame.width` or `innerFrame.height`. Alternatively you can also create a `ChartPointsViewsLayer` and pass chart points to it that represent your labels in model coordinates.
