### ISSUE TITLE
ChartLine: Wrong negative value

### ISSUE THREAD

**Issue by thomascalmon** [i-schuetz/SwiftCharts#142]
**Hello,**

My ChartPoints hasn't negative values. My points after mapping:
`[0, 0, 100, 0, 200, 0, 300, 0, 400, 0, 500, 0, 600, 0, 700, 0, 800, 0, 900, 0, 1000, 33.29, 1100, 38.13, 1200, 40.44, 1300, 42.35, 1400, 43.3, 1500, 44.54, 1600, 44.1, 1700, 43.32, 1800, 42.97, 1900, 41.94, 2000, 40.35, 2100, 38.77, 2200, 38.71, 2300, 37.5, 2400, 35.57, 2500, 33, 2600, 31.82, 2700, 30.77, 2800, 29.48, 2900, 28.17, 3000, 27.56, 3100, 26.54, 3200, 24.96, 3300, 24.26, 3400, 24.63, 3500, 25.4, 3600, 25.8, 3700, 26.27, 3800, 27.17, 3900, 27.78, 4000, 27.55, 4100, 27.65, 4200, 28.15, 4300, 29.49, 4400, 29.68, 4500, 30.21, 4600, 30.41, 4700, 31.03, 4800, 30.89, 4900, 31.48, 5000, 32.42, 5100, 33.16, 5200, 33.43, 5300, 33.12, 5400, 33.93, 5500, 34.25, 5600, 35.06, 5700, 35.94, 5800, 37.14, 5900, 38.11, 6000, 37.76, 6100, 37.26, 6200, 37.08, 6300, 37.3, 6400, 37.6, 6500, 37.94, 6600, 39.5, 6700, 40.66, 6800, 41.61, 6900, 40.95, 7000, 42.69, 7100, 43.97, 7200, 46.32, 7300, 47.74, 7400, 48.94, 7500, 49.68, 7600, 48.85, 7700, 48.3, 7800, 47.63, 7900, 47.95, 8000, 47.52, 8100, 48.42, 8200, 48.12, 8300, 47.9, 8400, 46.98, 8500, 45.97, 8600, 46.16, 8700, 45.41, 8800, 45.76, 8900, 45.25, 9000, 45.38, 9100, 43.73, 9200, 42.06, 9300, 39.76, 9400, 38.45, 9500, 37.94, 9600, 36.3, 9700, 35.91, 9800, 35.1, 9900, 35.94, 10000, 35.29, 10100, 34.35, 10200, 34.04, 10300, 33.94, 10400, 33.66, 10500, 32.52, 10600, 31.83, 10700, 29.97, 10800, 27.4, 10900, 24.11, 11000, 21.42, 11100, 19.23, 11200, 16.34, 11300, 14.01, 11400, 11.48, 11500, 9.34, 11600, 7.05, 11700, 5.17, 11800, 3.36, 11900, 2.02, 12000, .68, 12100, .31, 12200, .29, 12300, .27, 12400, .25, 12500, .25, 12600, .25, 12700, .25, 12800, .25, 12900, .25, 13000, .25, 13100, .25, 13200, .18, 13300, .1, 13400, .03, 13500, .03, 13600, .03, 13700, .03, 13800, .03, 13900, .03, 14000, .04, 14100, .04, 14200, .04, 14300, .03, 14400, .02, 14500, .02, 14600, .02, 14700, .02, 14800, .02, 14900, .02, 15000, .01, 15100, .01, 15200, 0, 15300, 0, 15400, 0, 15500, 0, 15600, 0, 15700, 0, 15800, 0, 15900, 0, 16000, 0, 16100, 0, 16200, 0, 16300, 0, 16400, 0, 16500, 0, 16600, 0, 16700, 0, 16800, 0, 16900, 0, 17000, 0, 17100, 0, 17200, 0, 17300, 0, 17400, 0, 17500, 0, 17600, 0, 17700, 0, 17800, 0, 17900, 0, 18000, 0, 18100, 0, 18200, 0, 18300, 0, 18400, 0, 18500, 0, 18600, 0, 18700, 0, 18800, 0, 18900, 0, 19000, 0, 19100, 0, 19200, 0, 19300, 0, 19400, 0, 19500, 0, 19600, 0, 19700, 0, 19800, 0, 19900, 0, 20000, 0, 20100, 0, 20200, 0, 20300, 0, 20400, 0, 20500, 0, 20600, 0, 20700, 0, 20800, 0, 20900, 0, 21000, 0, 21100, 0, 21200, 0, 21300, 0, 21400, 0, 21500, 0, 21600, 0, 21700, 0, 21800, 0, 21900, 0, 22000, 0, 22100, 0, 22200, 0, 22300, 0, 22400, 0, 22500, 0, 22600, 0, 22700, 0, 22800, 0, 22900, 0, 23000, 0, 23100, 0, 23200, 0, 23300, 0, 23400, 0, 23500, 0, 23600, 0, 23700, 0, 23800, 0, 23900, 0, 24000, 0, 24100, 0, 24200, 0, 24300, 0, 24400, 0, 24500, 0, 24600, 0, 24700, 0, 24800, 0, 24900, 0, 25000, 0, 25100, 0, 25200, 0, 25300, 0, 25400, 0, 25500, 0, 25600, 0, 25700, 0, 25800, 0, 25900, 0, 26000, 0, 26100, 0, 26200, 0, 26300, 0, 26400, 0, 26500, 0, 26600, 0, 26700, 0, 26800, 0, 26900, 0, 27000, 0, 27100, 0, 27200, 0, 27300, 0, 27400, 0, 27500, 0, 27600, 0, 27700, 0, 27800, 0, 27900, 0, 28000, 0, 28100, 0, 28200, 0, 28300, 0, 28400, 0, 28500, 0, 28600, 0, 28700, 0, 28800, 0, 28900, 0, 29000, 0, 29100, 0, 29200, 0, 29300, 0, 29400, 0, 29500, 0, 29600, 0, 29700, 0, 29800, 0, 29900, 0, 30000, 0, 30100, 0, 30200, 0, 30300, 0, 30400, 0, 30500, 0, 30600, 0, 30700, 0, 30800, 0, 30900, 0, 31000, 0, 31100, 0, 31200, 0, 31300, 0, 31400, 0, 31500, 0, 31600, 0, 31700, 0, 31800, 0, 31900, 0, 32000, 0, 32100, 0, 32200, 0, 32300, 0, 32400, 0, 32500, 0, 32600, 0, 32700, 0, 32800, 0, 32900, 0, 33000, 0, 33100, 0, 33200, 0, 33300, 0, 33400, 0, 33500, 0, 33600, 0, 33700, 0, 33800, 0, 33900, 0, 34000, 0, 34100, 0, 34200, 0, 34300, 0, 34400, 0, 34500, 0, 34600, 0, 34700, 0, 34800, 0, 34900, 0, 35000, 0]`

But when chart is plotted, It seems my start value is negative:
![captura de tela 2016-07-01 as 10 31 19](https://cloud.githubusercontent.com/assets/15636889/16523124/1df34f96-3f78-11e6-998d-f25e65ac6c71.png)

Nice framework!
Thank you,

**Thomás Calmon**

**Comment by i-schuetz** [comment]
The current path generator for the curve is not very good. You can pass a different one. Please see https://github.com/i-schuetz/SwiftCharts/issues/57 for possible solutions.

**Comment by thomascalmon** [comment]
For now I will use regular lines also, like @vineethvijayan. I am not good with CoreGraphics API! ;)
Thank you!

**Thomás Calmon**

**Comment by thomascalmon** [comment]
Oh, I forgot asking: how about right-bottom label (35000) cutting off last character... do you have any tip for me? :D
Thank you.

**Thomás Calmon**

**Comment by i-schuetz** [comment]
Ah, just increase `ChartSettings.trailing`

**Comment by thomascalmon** [comment]
Amazing! Solved! :D

Thank you.
**Thomás Calmon**
