### ISSUE TITLE
How to constrain a graph in a subview?

### ISSUE THREAD

**Issue by JakeSchroeder** [i-schuetz/SwiftCharts#143]
Hello, sorry to plague the issues section with a stupid question. I am wondering how I can add constraints to the graph that will allow for it to be perfectly centered in the view.

I already tried editing the settings file as well as the properties that have to do with the graph constraints. However, the graphs's x-axis keeps ignoring the constraints I set. I don't know if this is an issue on my end or the library's?

Here is a screenshot of where I want to display the graph

![graphexample](https://cloud.githubusercontent.com/assets/18093452/16547834/821fcedc-4148-11e6-9a18-73bcb7deaf1f.jpg)

here is what it looks like now

<img width="321" alt="screen shot 2016-07-03 at 6 22 12 pm" src="https://cloud.githubusercontent.com/assets/18093452/16547928/20592b32-414b-11e6-80d8-5807973405ea.png">

Any feedback is welcome!
Thanks

**Comment by i-schuetz** [comment]
It looks like you're initialising the chart before the frame of the view is fully calculated. Please take a look at https://gist.github.com/i-schuetz/f6e285eb0c86bb831510
