### ISSUE TITLE
Finding closest element and add line / color

### ISSUE THREAD

**Issue by ryancoughlin** [i-schuetz/SwiftCharts#149]
I am trying to go through the examples to find the answer to this but wanted to see if you could here.

I have a line chart that displays tide times. The x axis is the time and y axis is the height. Depending on what time it is now, I wanted to find the closest point and adjust the color or print a vertical line (some custom view) within that coordinate space.

I was looking at viewGenerator and a few other areas, but no luck. See image attached for a quick sample of the vertical line. 

<img width="545" alt="screen shot 2016-08-01 at 10 27 49 pm" src="https://cloud.githubusercontent.com/assets/1182341/17315148/40d39340-5837-11e6-95c1-fce2a5563a9a.png">

Love the flexibility of this chart library, finally getting use to it's setup and functions. @ #

**Comment by ryancoughlin** [comment]
(Can you mark this as a Question? It won't let me label).

**Comment by i-schuetz** [comment]
To show a line / view at specific coordinates, just use a view generator, and pass to it a chart point with the location where you want to show. For this you only need the x value. You can pass as y anything you want. In the view generator you get the chartpoint with the screen location, and can use this location to add the view to the chart. The view can have any shape / size / location you want.

**Comment by i-schuetz** [comment]
Edited the answer a little. Let me know if its detailed enough, otherwise happy to expand.

**Comment by ryancoughlin** [comment]
Great timing, was about to reply and say I got it working as a first pass:

```
        let curentTimeViewGenerator = {(chartPointModel: ChartPointLayerModel, layer: ChartPointsLayer, chart: Chart) -> UIView? in
            let chartPoint = chartPointModel.screenLoc
            let chartPointX = chartPoint.x - (self.view.frame.width / 2)
            let updatedChartPoint = CGPointMake(chartPointX, chartPoint.y)

            self.scrollView.setContentOffset(updatedChartPoint, animated: true)
            let center = chartPointModel.screenLoc
            let currentTimeMarker = UIView(frame: CGRectMake(center.x, 0, 1, chart.view.frame.height))
            currentTimeMarker.backgroundColor = UIColor.yellowColor()

            return currentTimeMarker
        }

        let currentTimeChartPoint = windPoints[8]

        let currentTimeMarkerLayer = ChartPointsViewsLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, chartPoints: [currentTimeChartPoint], viewGenerator: curentTimeViewGenerator, displayDelay: 0, delayBetweenItems: 0.05)
```

I am trying to get it positioned behind the other layers. These layers aren't added in order of say:
```
        let layers: [ChartLayer?] = [
            currentTimeMarkerLayer,
            lineCirclesLayer,
            labelsLayer,
            gridLayer,
            xAxis,
            chartPointsLineLayer
        ]
```

`ChartPoint` contains the formatter on the object, it doesn't store the `NSDate` value does it? I wanted to come up with some logic to find the closest date in the array to now. I would use that same logic to pass new label settings to the axis (update color, etc.)

**Comment by i-schuetz** [comment]
The chart layers are added in order, the problem is that some of them use core graphics (render directly on the chart's base view context) and others add subviews to it, so the core graphics layers will always appear behind the view layers. Do you really need your line to appear behind the guidelines and axes or is this only a test?

The chart points don't know the concrete class of their axis values, so with a normal chart point you will not be able to get a date or other custom information from its axis values (I plan to add generics to this in the future...). But you can cast the axis values, or create a chart point subclass which stores the date separately, or maybe has a computed property which casts the axis value and retrieves the date.

Btw I see you are using scroll view, not sure about your complete use case but there's a panning & zooming fork in development which may be useful for this and will be merged soon, https://github.com/grafiti-io/SwiftCharts scroll view related examples will be probably removed.

**Comment by ryancoughlin** [comment]
>Do you really need your line to appear behind the guidelines and axes or is this only a test?

More of a design nitpick, I solved the problem by using the circle generator. 

Regarding the dates, that sounds good. Would love to see generics added in or the ability to set a type for an axis. Thinking out loud if the format of the axis values (dates) were say: "7pm" - I could grab then convert to a date and then compare the dates that way. I only need to compare to find out what model is closest to the current time (within the same day). Example: A user can look at a line chart and without scanning the whole chart, they can see the current hour highlighted in some manner. 

I would subclass `ChartPoint` add a new property, say `date` and then initialize the model with my subclass?

Going to check out the branch with panning and zooming, that would be perfect. 

Appreciate all your help and detail to this. Been sharing this library with the iOS team here at thoughtbot.

**Comment by ryancoughlin** [comment]
Going to try subclassing later this week. Will post any updates here for others looking for this.
