### ISSUE TITLE
Building bar charts with custom data using generators

### ISSUE THREAD

**Issue by ryancoughlin** [i-schuetz/SwiftCharts#152]
I created the bar chart below using a loop and creating a new view and then adding all those views to a scrollview. I have a `Wind` object that stores the values you see below:

<img width="375" alt="screen shot 2016-08-08 at 1 12 32 pm" src="https://cloud.githubusercontent.com/assets/1182341/17488974/d2021de6-5d69-11e6-9654-2aced21e568b.png">

Using the view generators you extend with this library I would be able to make a new label for wind speed (the label within the bar) and the wind direction (the image view above the bar). My confusion is with populating those views with data from my `Wind` object: wind direction in degrees to rotate `UIImage` and label text as a `String`.

I would pass it an array of `ChartPoints` but `ChartPoint` is only aware of it's axis values. Is it possible to get an index within a view generator and grab data from `Wind` to populate those custom views, is there? Rough example:

Build custom view with models

```
        let windDirectionViewGenerator = {(chartPointModel: ChartPointLayerModel, layer: ChartPointsLayer, chart: Chart) -> UIView? in

        let image = UIImageView(image: "windDirection")

        // Get some index, somehow?
        let windAtIndex = windViewModel[i]
        
        // Rotate `image` with `windAtIndex.direction`

            return image
        }
```

Generate custom layer to be send to `Chart`

```
// Build with existing frame and axis. Pass it a new generator to build the arrow.
let windDirectionLayer = ChartPointsViewsLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, chartPoints: [chartPoints], viewGenerator: windDirectionViewGenerator, displayDelay: 0, delayBetweenItems: 0.05)
```

**Comment by i-schuetz** [comment]
You can get the correct type if you set the type arguments correctly, e.g. https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/CandleStickInteractiveExample.swift#L100

With this the index shouldn't be necessary, but just as info, you can get it with `chartPointModel.index`.

**Comment by ryancoughlin** [comment]
I just printed the value of `ChartPoint` and saw `index` - will build the bar chart using this library now. Sorry about that, should have looked on that object before hand.

Thank you.

**Comment by ryancoughlin** [comment]
I should then be able to do: 

```
let index = chartPointModel.index
let wind = wind[index]

// Build image
// Build label and set with wind.speed
```

**Comment by i-schuetz** [comment]
Yep. As I said you also can use a `ChartPoint` subclass (in case you aren't doing it yet) which contains your custom data, and if you set the type parameters correctly like in the candlestick line linked, retrieve it without having to use the index or casting.
