### ISSUE TITLE
Can we shift values for x and y axis?

### ISSUE THREAD

**Issue by Instadex** [i-schuetz/SwiftCharts#153]
![screen shot 2016-08-09 at 5 18 23 pm](https://cloud.githubusercontent.com/assets/20140833/17515363/96674cec-5e55-11e6-836b-e14138c76f3c.png)
Hi,

How can I shift the values of Y and X axis, as shown in above image and custom labels for x-axis to show the start of the week and end.

Do I need to create a custom view for the label in corner "MAY".

Thanks

**Comment by i-schuetz** [comment]
To shift the values you will need to insert "filler" axis values (e.g. for the y axis the start axis value would be 68 or so). There's functionality in development to set this spacing in pt but it's not available yet. For the ranges please refer to this issue: https://github.com/i-schuetz/SwiftCharts/issues/97

For the view in the corner the best is you just use your own, which you add on top of the chart. If you need it aligned with the x axis labels, you can get the axis layer's frame origin and add the spacing setting you pass in `chartSettings` to it. This should give the y origin of these labels.
