### ISSUE TITLE
Some bars rendering no data

### ISSUE THREAD

**Issue by ryancoughlin** [i-schuetz/SwiftCharts#155]
I got my bar chart rendering using `ChartPoint` and `ChartPointsViewsLayer`. I updated the parent frame and now some of the labels and sizes are all off. Any idea on what that could be? I have been trying to backtrack and take a look.
- It lives inside a scrollview.
- I tried making them frame really large to see if that changed it and nothing changed.

I have my code here: https://gist.github.com/ryancoughlin/1ad37781c83d5dff884450ad94c6afbf - for reference. 

![simulator screen shot aug 9 2016 4 20 05 pm](https://cloud.githubusercontent.com/assets/1182341/17532136/27f5cf7a-5e4d-11e6-9a9b-a720763d9872.png)

![simulator screen shot aug 9 2016 4 08 37 pm](https://cloud.githubusercontent.com/assets/1182341/17531907/feeaea62-5e4b-11e6-986e-b8f2b44e5ac3.png)

**Comment by ryancoughlin** [comment]
I keep checking my data generated from `ChartPoint` and that all looks correct.

**Comment by ryancoughlin** [comment]
I was trying to read this within the API docs, what would be a case you would use `ChartBarModel` vs `ChartPoint`?

**Comment by ryancoughlin** [comment]
After debugging the view, it seems like the bars are getting printing outside of the views bounds.

<img width="755" alt="screen shot 2016-08-09 at 5 05 22 pm" src="https://cloud.githubusercontent.com/assets/1182341/17533589/7b2e166a-5e53-11e6-939c-013b06fc6db2.png">

**Comment by ryancoughlin** [comment]
I think part of the issue of the ones that are not rendering is that it is too low and the scale is off. So there isn't enough room for the bar. Any way to set a minimum or adjust the scale?

**Comment by i-schuetz** [comment]
Yes, you are deriving the y range from the chart points, which means that it starts with your min wind speed value, so the bars with this value can't have any height. You would have to expand the y range a bit. Maybe make it start with 0.

Re: ChartBarModel vs ChartPoint, The chart bar models and bars layer are just a more handy way to deal with bar charts, the chart points are generic and used in most layers, including `ChartPointsViewsLayer` with which you can generate any views, including bars. In later case you have to care yourself to configure, position etc. the view correctly, but have more flexibility.

I see also your bars have some horizontal overlap, may be that your content view is not wide enough? You can also retrieve `minAxisScreenSpace` from the layer's axes passed to the view generator to calculate a fitting bar width.

**Comment by ryancoughlin** [comment]
Ah yes, ok that makes sense now. Within the dummy data I am loading now the min value is `5` so that is acting as my "zero" - I am creating my `yValues` here:
```
        let yValues: [ChartAxisValue] = winds.map { wind in
            return ChartAxisValueInt(wind.speed, labelSettings: labelSettings)
        }
```
Since it is mapping over `Wind` and returning `ChartAxisValue` - I would need to pass it another "fake" `Wind` object with `speed` being `0`. If I use `ChartBarModel` I can pass `...axisValue1: ChartAxisValueDouble(0)...`

When I use `ChartBarModel` no bars are rendered, but my labels and icons are still intact:

```
        let bars: [ChartBarModel] = winds.enumerate().flatMap {index, wind in
            [
                ChartBarModel(constant: ChartAxisValueDouble(index), axisValue1: ChartAxisValueDouble(0), axisValue2: ChartAxisValueDouble(wind.speed), bgColor: UIColor.redColor())
            ]
        }
        let barsLayer = ChartBarsLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, bars: bars, horizontal: false, barWidth: 40, animDuration: 0.5)
```

Same axis, innerframe and coordpace as when rendering `ChartPointsViewLayer` - I like the idea of `ChartBarsLayer` because it is self contained and I have a good amount of custom view generators for this chart (also allows me to start at `0`).

**Comment by ryancoughlin** [comment]
I did a quick test and made one of the windSpeed values `0` - that does fix it. When I have a bar that is equal to the lowest speed, I need some type of logic to adjust my `yOffset` on the white label text. That should be easy enough. Or just not render that bar! 

![simulator screen shot aug 9 2016 7 18 16 pm](https://cloud.githubusercontent.com/assets/1182341/17536834/0bc8ef94-5e66-11e6-91cc-7763f314b339.png)

**Comment by ryancoughlin** [comment]
Updated the GIST if that helps give a better picture.

**Comment by i-schuetz** [comment]
Regarding adding the 0 axis value this is not an issue at all, the axis values are entirely independent of the contents of the chart. Since you are not displaying any axis values, actually you could simply have 2, which represent your range - 0 and the max wind speed value.

How to display low speed values, where there's no bar or the label doesn't fit in the bar is a UX question - with the view generator you have the freedom to skip label, or change the relative position, the size etc.

Regarding the bars layer, maybe use an example that uses a bars layer as start, it should be easy to find which change causes problems.

**Comment by ryancoughlin** [comment]
Sorry, been away on a company retreat. Catching up now…

Ah interesting. Correct, I don’t have a y axis visible, I am using the `windSpeed` (the value within the bar) as my y axis value. So you are saying instead mapping over my objects and creating my `yValues` via `map` I would make an array of two values: 0 and the max wind speed?

I was playing with the view generator and I can refine that a bit so when it is zero show a thin line or a gray bar. Tons of customization with using that generator, I can figure that out. Was thinking out loud in that last reply.

> Regarding the bars layer, maybe use an example that uses a bars layer as start, it should be easy to find which change causes problems. 

I will give that a go if I keep having issues.
