### ISSUE TITLE
Axis Titles Location on Axis

### ISSUE THREAD

**Issue by Trever123** [i-schuetz/SwiftCharts#157]
Hi,

Is there a way to move the axis titles from being aligned in the centre of the axis to the ends. 

If you aligned the Y axis to the bottom and X axis to the left if would look something like the following:

<img width="337" alt="screen shot 2016-08-31 at 11 07 27" src="https://cloud.githubusercontent.com/assets/1190118/18124671/2abd74a4-6f6b-11e6-9529-8587306f14f2.png">

Thanks

**Comment by i-schuetz** [comment]
That's currently not possible, but you can retrieve the rects of the generated axis layers and add your own labels.

**Comment by Trever123** [comment]
Ok ill give that a go, thanks :)
