### ISSUE TITLE
Example using in Objective c

### ISSUE THREAD

**Issue by geogerar** [i-schuetz/SwiftCharts#159]
Hi,

A very nice work indeed.
Is it possible to provide an example for using "SwiftCharts" with Objective-C App.
This will be very helpful for a lot of developers.

Thank you for this nice job

George Gerardis

**Comment by i-schuetz** [comment]
Thanks. You mean the integration? Should be straight forward. https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html If you run into problems just write it in this thread and I'll help. If you mean porting example code to Obj-C, this is something anyone can do, I currently don't have the time. Happy to add links to an external repository or articles.

**Comment by geogerar** [comment]
Hi again,

No, I mean an example of objective-c to show how we use it in objective-c

George

**Comment by i-schuetz** [comment]
yeah so
1. Add the library using pods / cartage just like described in the readme (there's no difference here)
2. Necessary steps to use Swift in Obj-C as described in https://developer.apple.com/library/ios/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html
3. Port the code of some example to Obj-C, probably a short one like [HelloWorld](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/HelloWorld.swift
)
4. See if it works :)
5. Publish this in your own repo or some blog article, very happy to add a link to my readme, as you said this would be a great help for other users.

I'm also available to help if you get stuck in any of these steps.

**Comment by Spettacolo83** [comment]
Hello there! I'm trying to use this wonderful class to Objective-C.
I've tried to add:

#import <SwiftCharts/SwiftCharts-Swift.h>
#import <SwiftCharts/SwiftCharts-umbrella.h>

But I can't see the class such as ChartPoint and LineChart.
Maybe I need to do something else.
Can you help me please?

**Comment by i-schuetz** [comment]
Hi,

SwiftCharts currently doesn't support Obj-C. I can consider adding it if someone submits a pull request. Otherwise I think it will stay like this, since it's not a prio and I don't have time.

Sorry!

**Comment by i-schuetz** [comment]
Hi,

SwiftCharts currently doesn't support Obj-C. I can consider adding it if someone submits a pull request. Otherwise I think it will stay like this, since it's not a prio and I don't have time.

Sorry!

P.S.

To import Swift framework in Obj-C you should need only @import LibraryName;

Just fyi - it doesn't work with SwiftCharts.

**Comment by Spettacolo83** [comment]
Hi i-schuetz, I tried `@import SwiftCharts` but it does not work!

**Comment by DenZuck** [comment]
Objective-c cannot read top-level swift classes. The only solution is to subclass the no top-level swift classes from NSObject.
