### ISSUE TITLE
Use of unresolved identifier 'ExamplesDefaults'

### ISSUE THREAD

**Issue by mostworld77** [i-schuetz/SwiftCharts#16]
Hi,
i installed this framework but i get same 6 errors on different lines with ExamplesDefaults:
ex.: LineChart.swift:23:54: Use of unresolved identifier 'ExamplesDefaults'
Im using xCode 7 Beta 4

Where can be the problem?

**Comment by i-schuetz** [comment]
Hi,

oops, seems I let some code of the examples project in the core project in my last updates.

If you're using master you should be fine using the latest stable version (0.2.2). If you're on swift2.0, please checkout the last stable commit. If you're using pods use this:

use_frameworks!
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git', :branch => 'swift2.0', :commit => '082f8319af'

I will fix it soon - then you can continue using the very bleeding edge ;)

**Comment by i-schuetz** [comment]
It's fixed now in master and swift2.0.

**Comment by rolyanos** [comment]
Hello, I have the same issue in swift 3.0

**Comment by i-schuetz** [comment]
@rolyanos Which Xcode version?

**Comment by rolyanos** [comment]
@i-schuetz, Version 8.2.1 (8C1002)

**Comment by i-schuetz** [comment]
I was just able to build master as well as 0.5.1 with Xcode 8.2.1

Please clean / delete the derived data folder and clean pods too:
```
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod search SwiftCharts
```

**Comment by rolyanos** [comment]
Not fixed(

**Comment by i-schuetz** [comment]
Is it really the same error? Because this was fixed about 2 years ago. It's definitely fixed in the Swift 3.0 branches. Which pod version are you using?

**Comment by rolyanos** [comment]
1.2.0

**Comment by i-schuetz** [comment]
Hmm so you're getting help here and write in other libraries that you "saw more than 3 issues". Good luck then, hope you can find what you need elsewhere.
