### ISSUE TITLE
Programatically Panning

### ISSUE THREAD

**Issue by treverj** [i-schuetz/SwiftCharts#160]
Hi,

I am unable to add this question to the grafiti-io fork so adding it here, sorry. 

I am trying to programmatically pan the view to a set location. I am programatically highlighting some of the bars but if i am zoomed in and those bars are off the screen, they cannot be seen. I am wanting to pan the view so they are on the screen but if i try to use the highlighted bars frame as a pan to point (x coordinate), it always reverts back to the left as if i was setting it to 0.

`self.chart.pan(x:tappedGroupBar.tappedBar.view.frame.origin.x, y: 0)`

Any suggestions?

Thanks

**Comment by i-schuetz** [comment]
I think you need a negative x value, because it's an offset to the left.

**Comment by i-schuetz** [comment]
Was this solved?
