### ISSUE TITLE
Swift3 support

### ISSUE THREAD

**Issue by bugsend** [i-schuetz/SwiftCharts#161]
Can't rebuild SwiftCharts for Xcode8 Swift 3 compiler... Is it possible or we should wait for you to upgrade library appropriately for the new Swift version ?

Carthage really asks for library developer to rebuild library with the new language: 

> === BUILD TARGET SwiftCharts OF PROJECT SwiftCharts WITH CONFIGURATION Release ===

> Check dependencies
> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

> ** BUILD FAILED **

**Comment by RohanRamsay** [comment]
Conversion to Swift 3 doesn't work either.

When can we expect the release for Swift 3?

**Comment by RohanRamsay** [comment]
Thanks i-schuetz.
(Just so you know, after conversion to Swift 3, there weren't that many errors - just a couple. related to Int to dispatchTime conversion)

**Comment by i-schuetz** [comment]
Yeah, maybe it's not a lot of work. Thing is also that there's currently a fork with quite a lot of changes that should be merged before porting.

**Comment by i-schuetz** [comment]
Update: @loudnate came to the rescue and ported master to Swift 3.0 (https://github.com/i-schuetz/SwiftCharts/pull/162)!. I'll merge it in the course of this week. The fork I mentioned will be merged later.

**Comment by bugsend** [comment]
Thanks for keeping us up to date with this issue !

**Comment by i-schuetz** [comment]
It's in master now.
