### ISSUE TITLE
Carthage dependency for Swift 3

### ISSUE THREAD

**Issue by bugsend** [i-schuetz/SwiftCharts#163]
Is there a Carthage dependency for recent Swift3 update ? I can see dedicated section for cocoa pods, but Carthage section still doesn't mention Swift3 compatibility.

Thanks !

**Comment by bugsend** [comment]
I am asking because this is what I have as output form the following command:

`carthage update --platform IOS `

> /usr/bin/xcrun xcodebuild -project /Users/szaytsev/Documents/Projects/nameyourchild/Carthage/Checkouts/SwiftCharts/SwiftCharts.xcodeproj -scheme SwiftCharts -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean buildBuild settings from command line:
    BITCODE_GENERATION_MODE = bitcode
    CARTHAGE = YES
    CODE_SIGN_IDENTITY = 
    CODE_SIGNING_REQUIRED = NO
    ONLY_ACTIVE_ARCH = NO
    SDKROOT = iphoneos10.0

>  === CLEAN TARGET SwiftCharts OF PROJECT SwiftCharts WITH CONFIGURATION Release ===

> Check dependencies
> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
> 
> === BUILD TARGET SwiftCharts OF PROJECT SwiftCharts WITH CONFIGURATION Release ===
> 
> Check dependencies
> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
> “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
> 
>

**Comment by i-schuetz** [comment]
I released 0.5 tag, let me know if it works.

**Comment by bugsend** [comment]
Thanks! Version 0.5 successfully updated !
