### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by floriannagel** [i-schuetz/SwiftCharts#164]
I try to reimplement a cubic chart. But is can't build bc of strange errors

`let labelSettings = ChartLabelSettings(font: UIFont.systemFontOfSize(11))

```
    var tempPoints: [(Int, Int)] = []
    var i: Int = 0

    for item in moodsArray {

        let point = (i, Int(item.mood))
        tempPoints.append(point)
        i += 1
    }

    let chartPoints = tempPoints.map {

        ChartPoint(x: ChartAxisValueInt($0.0, labelSettings: labelSettings), y: ChartAxisValueInt($0.1))
    }`
```

Cannot convert value of type 'ChartAxisValueInt' to expected argument type 'Float'

This doesn't make sense

**Comment by i-schuetz** [comment]
What version of XCode and SwiftCharts are you using? Try also to set the type in the `chartPoints` declaration, sometimes the compiler has problems with this.
