### ISSUE TITLE
Cocoapods won't get the newest version of SwiftCharts

### ISSUE THREAD

**Issue by pktrkts** [i-schuetz/SwiftCharts#165]
Hi,

For some reason when I try to get SwiftCharts 0.5 with my pod file, it refuses.  I think somehow Cocoapods only knows about 0.4.  I don't know why this is.  Any help in getting the podfile to get the most recent version would be helpful.  Thanks.

Sincerely,
Sean

**Comment by i-schuetz** [comment]
Hi,

for now please use master as described in the readme (it's stable). Last time I tried there were some issues creating the pod and don't have time to investigate this. Will come back to this later.

**Comment by pktrkts** [comment]
Hi,

Any hints on how to upgrade 0.4 to Swift 3 or Swift 2.3?  I've upgraded to XCode 8 and I need the library I'm working with to work with one of those Swift versions.  Thanks for your consideration of this matter.

**Comment by i-schuetz** [comment]
Yes use master, which is 3.0. In the readme you find all you need.

**Comment by i-schuetz** [comment]
0.5(.1) is now available in Pods, sorry for the delay!
