### ISSUE TITLE
While following official documentation, CocoaPods refuses to fetch version 0.5 even when specifying explicitly master branch

### ISSUE THREAD

**Issue by thexande** [i-schuetz/SwiftCharts#166]
Greetings. 

I cannot get version 0.5 into my project by following the official documentation for your library. 

This piece specifically: 
##### CocoaPods

Add to your Podfile:

Swift 3.0:

``` ruby
use_frameworks!
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```

Note: To use Swift 3.x / master, you need Xcode 8+

I have tried both of the following combinations in my podfile to fetch version 0.5:

``` ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```

``` ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git', :branch => 'master'
```

Both result in the following. What am I missing?

![screen shot 2016-09-24 at 2 00 48 pm](https://cloud.githubusercontent.com/assets/7704414/18810934/0dad4166-8260-11e6-8939-61fdd66aaa73.png)
![screen shot 2016-09-24 at 1 59 20 pm](https://cloud.githubusercontent.com/assets/7704414/18810935/1074eb92-8260-11e6-86c2-5297e489f3ae.png)

**Comment by i-schuetz** [comment]
Try with `pod update SwiftCharts` in the command line.

**Comment by simonstewart** [comment]
Had a similar issue.

Using the Swift 3 instructions, the code that came down was Swift <2.3 and the auto-conversion doesn't work.

Am keen to use this lib again, but not keen to convert another codebase to Swift 3.  Can you double check the Cocoapods & git issue?

**Comment by i-schuetz** [comment]
@simonstewart master is 3.0 and if you use the master as described in the readme you should get this. Do not use 0.5 because this tag doesn't exist in pods. If you continue having issues please verify the version / commit hash in your lock file. If nothing helps, try to clean your pod cache

```ruby
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
```

And after it `pod install` or `pod update`

**Comment by i-schuetz** [comment]
0.5(.1) is now available in Pods, sorry for the delay!

**Comment by simonstewart** [comment]
@i-schuetz thanks!  Will give it a try in a couple days on one of my apps.
