### ISSUE TITLE
Error 'No such module SwiftCharts' in Xcode 8.0

### ISSUE THREAD

**Issue by mobyforce** [i-schuetz/SwiftCharts#168]
Hi,
I am using Swift 3.0 and Xcode 8.0. I am getting the compilation error ' No such module SwiftCharts'. Here is my pod file.

platform :ios, '8.0'

target 'xxxxx' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git', :branch => 'master'

end

Please help.

Rafeeq

**Comment by i-schuetz** [comment]
Could you please provide more details? Do you see errors in compilation of SwiftCharts?

**Comment by aescariom** [comment]
Same error here. There are no errors on the code, but the compiller says:

Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Once I try to convert it, I get hundreds of errors.

I tried deleting the folder or even creating a new project

**Comment by marktdavison** [comment]
I have also had the same issue yesterday, tho I have varied the platform to :ios, '9.0' and :ios, '10.0' to see if it made a difference - it didn't.

**Comment by i-schuetz** [comment]
I created an empty project, init pod with SwiftCharts as dependency and got errors related with Swift version. The generated pod project doesn't have the correct Swift version. This could be fixed by updating cocoa pods (`sudo gem update cocoapods --pre`) and running pod install again.

See http://stackoverflow.com/questions/39380939/alamofire-xcode-8-swift-3-results-in-786-compile-errors for more details.

After updating cocoapods, if you still have problems you can also clean pods and install/update again:
```ruby 
rm -rf "${HOME}/Library/Caches/CocoaPods"
rm -rf "`pwd`/Pods/"
pod update
```

Let me know if it works! If it doesn't try with an empty project, like I did, so we can locate better the source of the problem.

**Comment by aescariom** [comment]
I already fixed it, I deleted the Pods folder and then install again. Finally I converted the code to swift 3.0. It worked

**Comment by i-schuetz** [comment]
Which code?

**Comment by aescariom** [comment]
The entire SwiftCharts lib.

I'll try to use your method later on

**Comment by i-schuetz** [comment]
SwiftCharts master is already in Swift 3.0 - you must have had a cached version or something.

**Comment by aescariom** [comment]
I know that, it says so on the readme, but XCode says that library it is not on that version... maybe it is doing some catching and not downloading the last version? I have no idea.

**Comment by i-schuetz** [comment]
The project's settings are correct, as you can see [here](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts.xcodeproj/project.pbxproj#L1184) (look for SWIFT_VERSION / LastSwiftMigration = 0800). It looks to me like entirely cocoapods issue.

**Comment by aescariom** [comment]
Thanks for the tips! For now it is working for me.

Thanks for this awesome library

**Comment by i-schuetz** [comment]
Thanks ;) Try to get it working with the online version, having this local port is not a good idea.

**Comment by marktdavison** [comment]
Big improvement - only 5 errors - same one in init of 5 .swift files:

 Swift Compiler Error Group
<project>/Pods/SwiftCharts/SwiftCharts/ChartCoordsSpace.swift:93:204: @escaping attribute only applies to function types
<project>/Pods/SwiftCharts/SwiftCharts/Layers/ChartPointsViewsLayer.swift:25:116: @escaping attribute only applies to function types
<project>/Pods/SwiftCharts/SwiftCharts/Layers/ChartPointsCandleStickViewsLayer.swift:13:117: @escaping attribute only applies to function types
<project>/Pods/SwiftCharts/SwiftCharts/Layers/ChartPointsSingleViewLayer.swift:16:117: @escaping attribute only applies to function types
<project>/Pods/SwiftCharts/SwiftCharts/Layers/ChartPointsTouchHighlightLayer.swift:27:165: @escaping attribute only applies to function types

**Comment by i-schuetz** [comment]
What about you investigate the issue a little? As mentioned above after upgrading cocoapods issue was fixed, so it's very likely something related with your local configuration.

**Comment by marktdavison** [comment]
missed that - my apologies.  Updated Xcode and it compiles... now to use, thanks again
