### ISSUE TITLE
Move Origin to top left and reverse axis order

### ISSUE THREAD

**Issue by TheBogueRat** [i-schuetz/SwiftCharts#169]
Is it possible to flip the Y-Axis as illustrated below, so that the origin is in the top left instead of bottom left?  I didn't see anything comparable in the examples.  Perhaps this is not desirable feature.
<img width="566" alt="screen shot 2016-10-05 at 3 16 19 pm" src="https://cloud.githubusercontent.com/assets/3030061/19136636/28797854-8b3c-11e6-885b-fcf0af28a42f.png">

My workaround for now is to flip all my data values to the negative. Which is actually not too much work but it would be nice to just have a 'flipAxis' switch to throw so my labels would be positive.

![screen shot 2016-10-05 at 9 54 46 pm](https://cloud.githubusercontent.com/assets/3030061/19138018/823ae13e-8b46-11e6-87ce-711bf8a103b2.png)

Instead, I found I could change the labels thusly: 

`let yValues = [-1020, -800, -600, -400, -200, 0].map {ChartAxisValueString(String(-Int($0)), order: $0)}`

![screen shot 2016-10-05 at 10 58 54 pm](https://cloud.githubusercontent.com/assets/3030061/19139051/656f6a76-8b4f-11e6-85cb-620305f9f930.png)

And now I have something that works but requires me to adjust my data source instead of adjusting the view.  Although I have come to a solution, would it be possible to add the ability to flip the axis?

**Comment by i-schuetz** [comment]
I think you should be able to simply pass the chart points in reversed order. Haven't found it necessary so far to do this at view level, considering how easy it is to do it with the model. Let me know if it works for you.

**Comment by TheBogueRat** [comment]
Thank you for the feedback.  Perhaps I don't understand what you are trying to say.  If I flip the y axis label values like this (from HelloWorld example):
       ` let yValues = stride(from: 16, through: 0, by: -2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}`
from 
       ` let yValues = stride(from: 0, through: 16, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}`

The axis is then compressed to the bottom.  Is there another setting that needs to be changed as well?  It doesn't see like this is set up to show values on the y axis in reverse order with lower numbers at the top.

<img width="317" alt="screen shot 2016-10-06 at 9 14 59 am" src="https://cloud.githubusercontent.com/assets/3030061/19153679/7937103a-8ba5-11e6-86bd-4b97ffc40445.png">

That was the first thing I tried to do, reversing order of data/labels but I couldn't figure out the logic.  I ended up inverting y values and changing the labels accordingly which is fine.

Since I also need to figure out how to scale the x-axis exponentially, I'll poke around and see if I can get a better understanding of your framework design.

**Comment by i-schuetz** [comment]
Somebody did a fix a while ago to avoid a division by 0, which broke this. I fixed it: https://github.com/i-schuetz/SwiftCharts/commit/1705b493b9239cbeb74c484eb9fa9694e42e5b7d update master and let me know if it works now!

**Comment by TheBogueRat** [comment]
Perfect, thank you.  So now I just set the labels array in the order I need them from the bottom up, instead of manipulating the data.  This is great!

<img width="314" alt="screen shot 2016-10-06 at 1 39 48 pm" src="https://cloud.githubusercontent.com/assets/3030061/19163563/7ad562d2-8bca-11e6-9a7b-3fe9015e9dee.png">
