### ISSUE TITLE
Number of Compiler Errors

### ISSUE THREAD

**Issue by car92** [i-schuetz/SwiftCharts#17]
Hi Ivan,

I'm trying to import the framework into a project (via pods) but am having a few issues I thought you might be able to shed some light on.

First of all, I'm getting 6 compiler errors from the pods and an additional error "No Such Module" when I attempt to import the framework (images attached).

The steps I've followed are merely setup and installed the podfile with the Swift 2.0 branch, opened the workspace in xCode 6.3.1, inputted the import statement and built the project.

Thanks for your help!

P.S. in reference to my previous question involving getting the touch point to move between two different points on the y-axis, I managed to develop a method, although I am sure it could be done more elegantly - happy to upload if you are interested.

<img width="1397" alt="default" src="https://cloud.githubusercontent.com/assets/13217014/8903984/21e4d492-349f-11e5-8d03-92ec36a1a96e.png">

<img width="267" alt="screen shot 2015-07-27 at 8 31 15 pm" src="https://cloud.githubusercontent.com/assets/13217014/8904003/53fb308e-349f-11e5-90dc-08fd93898d2b.png">

**Comment by i-schuetz** [comment]
Hi,

you need XCode 7 (beta 4) to use the Swift2.0 branch. XCode 6 only supports Swift 1.2.

As I mentioned in your previous question, the intersection issue should be fixed now and it was also merged in the swift2.0 branch.

**Comment by car92** [comment]
Appreciated. Thanks.
