### ISSUE TITLE
Implement float instead of Int

### ISSUE THREAD

**Issue by muzamilhassan1987** [i-schuetz/SwiftCharts#183]
Hi,
I am following NotNumericExample and i want to set the values as float at Y axis, also i want to set float values in graph also , i mean for calculation , but in example you take only integer how would i implement that

**Comment by i-schuetz** [comment]
Hi,

sorry for the late response. Yes `ChartAxisValueString` accepts only ints. You could change this class to use doubles (and submit a pull request). Or you can map your floats to integers and also if you need the original float create a subclass `ChartAxisValueString` where you also store it.
