### ISSUE TITLE
Swift 3 Support

### ISSUE THREAD

**Issue by Gerst20051** [i-schuetz/SwiftCharts#185]
It doesn't appear like this has been migrated yet.

**Comment by i-schuetz** [comment]
Aha.

**Comment by Gerst20051** [comment]
Maybe the CocoaPod isn't pointed to the latest master?

**Comment by i-schuetz** [comment]
https://github.com/i-schuetz/SwiftCharts#installation

**Comment by Gerst20051** [comment]
gotcha

**Comment by i-schuetz** [comment]
`0.5.1` is not available in Pods!

**Comment by i-schuetz** [comment]
`0.5.1` is now available in Pods!
