### ISSUE TITLE
Change Axis line position

### ISSUE THREAD

**Issue by muzamilhassan1987** [i-schuetz/SwiftCharts#187]
I am trying to change the position of axis lines but still facing issues i need to set both line at 0 position and then it will show axis values like this, like i add chart in another view but it start after some point not from 0, 0 i need axis line to be start from 0,0 of uiview 

Currently it look like this 
![1](https://cloud.githubusercontent.com/assets/5962169/20569126/c7567526-b1c0-11e6-8157-45c3ee92b2ec.png)

And i want this 
![2](https://cloud.githubusercontent.com/assets/5962169/20569133/cfd08624-b1c0-11e6-813e-e93fc8a30f5a.png)

**Comment by i-schuetz** [comment]
The easiest would be to just use a second view for the chart, then move this view to the left and down by the size of the axes frames (field `rect`). Let me know how it works!

**Comment by muzamilhassan1987** [comment]
I dont understand will you please elaborate more

**Comment by i-schuetz** [comment]
Sorry. Somehow I missed answering to this. What I meant was simply to move the chart view such that the lines start at the edges. You have to also set `clipsToBounds` of the parent to `false` it order for the labels and part of the line to not be clipped. Alternatively you can also use a separate view for the background (the green/red area) and move it top/right?

You can query the position/size of the axes area by calling `rect` of the axis layers.
