### ISSUE TITLE
Change only Y axis label position

### ISSUE THREAD

**Issue by muzamilhassan1987** [i-schuetz/SwiftCharts#188]
I want to change to change Y axis label positions currently it is left side of the bar i want it to inside of the bar

**Comment by i-schuetz** [comment]
Don't understand what you mean with left side / inside of the bar? Which labels are you talking about?

**Comment by muzamilhassan1987** [comment]
Currently it look like this
![1 copy](https://cloud.githubusercontent.com/assets/5962169/20570707/8336ab76-b1c6-11e6-826d-998bad0e6bb7.png)

and i want this 
![3 copy](https://cloud.githubusercontent.com/assets/5962169/20570712/894a8f64-b1c6-11e6-9f3f-f5ffdde84ee1.png)


The label on Y axais is on left side of line 
i need to right side of line

**Comment by i-schuetz** [comment]
Ok, "bar" confused me a little. There's no way to do this out of the box, 2 possibilities:

1. Pull request to add support for this - you could add a e.g. a setting to for arrangement, similar to the current setting for alignment `ChartLabelTextAlignment`.

2. Workaround: You use an y axis layer that doesn't show any labels, and then create a second one, with `textAlignment` set to `.left`, with line hidden and give it an offset to the right. To create this second one you use the initializer of `ChartAxisYLowLayerDefault` and copy basically everything you use in the first y axis except the x position of `p1` and `p2`. 

Let me know if it works! Feel free to comment if you need more help.
