### ISSUE TITLE
Enchancement!!!!!

### ISSUE THREAD

**Issue by geogerar** [i-schuetz/SwiftCharts#19]
Hello,
I can say....your colection is fantastic. A real tool for them they want a chart library!!!
Thanks a lot for your work.
I want to propose an enchancement for them they love objactive c
Is it possible to have your tools in objective c also?

One more time thanks you very much.

George Gerardis

**Comment by i-schuetz** [comment]
Hi,
thanks for the nice words! I'm not planning to port the library to Obj-C. Since it's possible to use Swift libraries from Obj-C I don't see a good enough reason. I would rather prefer to invest the time in new features...
