### ISSUE TITLE
Carthage installation error

### ISSUE THREAD

**Issue by Domsware** [i-schuetz/SwiftCharts#191]
Swift 2.3

## Cartfile
`github "i-schuetz/SwiftCharts" ~> 0.4`

## Message
```
*** Building scheme "SwiftCharts" in SwiftCharts.xcodeproj
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /<MY_PROJECT>/Carthage/Checkouts/SwiftCharts/SwiftCharts.xcodeproj -scheme SwiftCharts -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by i-schuetz** [comment]
Clean failed sounds like a local problem. Could you try passing verbose flag? And with a new project?

**Comment by Domsware** [comment]
Here some logs after verbose update:

`“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

I already use Carthage for other libraries for this project so this may come from SwiftCharts project's configuration.

I found an issue related to this point on [Carthage GitHub](https://github.com/Carthage/Carthage/issues/1415)
And here is an interesting quote:

> In Build Settings, each target should make sure it chooses "YES" or "NO" instead of unspecified for "Use Legacy Swift Language Version".

**Comment by i-schuetz** [comment]
Ok, there were actually 2 issues: 

- The 0.4 tag didn't have the 2.3 upgrade
- The tv target didn't have the legacy version setting

Should be fixed now, please try again (you don't have to change anything)

**Comment by i-schuetz** [comment]
Is it fixed?

**Comment by Domsware** [comment]
Problem solved! Thank you.
