### ISSUE TITLE
Download builds OK, but not run anything

### ISSUE THREAD

**Issue by ahartman** [i-schuetz/SwiftCharts#192]
I download example, install SwiftCharts with cocoa pods.
Project builds successfully but does not start example.
Help appreciated.
André Hartman, Belgium

**Comment by i-schuetz** [comment]
To start the example you have to run directly the Github project, not install with pods. Pods only downloads the library.

**Comment by ahartman** [comment]
Dear Ivan,

I got your library working and it looks powerful and simple at the same time, good to use.
I need to do a stacked bar charts of 2 variables that one or both can be positive or negative.
So, depending on the values the chart should look like a stacked bar chart - both value positive or both negative - or a +/- bar chart - when one value is positive and the other one negative.

Any idea how to do this?

Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België
tel:		0032 3 666 0411
GSM:	0032 488 626 895

**Comment by i-schuetz** [comment]
Hi Andre,

thanks! If I understand correctly, you want to display different chart types depending on your model data. Just have a method that builds the stacked chart, and another the +/- chart and decide which to use based on your model data?

**Comment by ahartman** [comment]
Dear Ivan,
Please find attached a screen image of the browser version of what I am now developing in Swift.
As you can see, the stacked bars can be up and under the x-axis. That is something I cannot make your SwiftCharts do. There is nothing special about it, it may be just the way SwiftCharts is coded?

Anyway, if you could help with an idea how to realise how this could be done with SwiftCharts, that would be much appreciated.


Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België
tel:		0032 3 666 0411
GSM:	0032 488 626 895

**Comment by i-schuetz** [comment]
Unfortunately there's no image attached!

**Comment by ahartman** [comment]
Ivan,
The image was in the sent message, let ut us try again.

Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België
tel:		0032 3 666 0411
GSM:	0032 488 626 895

**Comment by i-schuetz** [comment]
Could you please attach it directly in the Github site? Email attachments don't seem to work.

**Comment by ahartman** [comment]
Ivan,
I created issue #197 - StackedBarCharts.
You see 2 graphs in the image (of the browser version).
The right graph will always be positive values, so this is doable.
The left graph is the issue. Bars can be fully positive or negative or be positive AND negative on both sides of the x-axis.


Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België
tel:		0032 3 666 0411
GSM:	0032 488 626 895
