### ISSUE TITLE
Unknown values management

### ISSUE THREAD

**Issue by Domsware** [i-schuetz/SwiftCharts#193]
I need to display values on Y axis along date. But for some date no value exists. Does SwiftCharts handle this?

**Comment by i-schuetz** [comment]
Yes, you have full control over what you want to display. You can create a `ChartAxisValue` (or `ChartAxisValueDate`) subclass and implement accordingly.

**Comment by i-schuetz** [comment]
The axis just has to represent a range. You basically only need 2 axis values to create an axis. What you want to display inside of the range - how many values, in which intervals, and the text you show for each of them is as said up to you.

**Comment by Domsware** [comment]
I think there is a misunderstanding. What I need is to display a discontinued line: in other words: if for a given date there is no values, the line is then _cut_ and is therefore made of 2 segments.

**Comment by i-schuetz** [comment]
Ok, some ideas:

1. Quick and dirty: You can show an overlay in front of the axis line, where you want it to be divided, i.e. add a subview of the chart view, that has the same color as the background. To determine the position and size of the overlay you can use `screenLocForScalar(_ scalar: Double)`

2. You can make the axis line invisible and show the segments basically as chart points, using `ChartPointsViewsLayer` (you can see this layer in use e.g. in HelloWorld example). `ChartPointsViewsLayer` is used to show any kind of UIViews on the chart, so you can use it to show these lines too. You'd create 2 chart points with model coordinates corresponding to the location of your "gap", and then in the view generator using the computed screen locations of these points generate rectangular views that resemble the segmented line.

3. You can create a subclass of the axis layer you want to be segmented, and override either `generateLineDrawer(offset: CGFloat)` to return also a subclass of `ChartLineDrawer` which draws the line in the way you want. You can submit a PR to make `generateLineDrawer(offset: CGFloat)` public (it's internal now so you'd not be able to override it), and also note that `ChartLineDrawer` works only with screen coordinates so you probably would have to map first the model coordinates from where the gap should be to screen coordinates, e.g. using the axis layer as in method 1.

I could imagine more advanced ways to implement this, which would require non trivial changes in the library, like allowing to control the generated line based on model coordinates. But this is probably an overkill.

I personally would try 2. It's handy improvisation and not a hack - `ChartPointsViewsLayer` exists essentially to add subviews to the chart based on model coordinates, so this would be a legitime use. The chart also doesn't clip the contents.
