### ISSUE TITLE
X and Y axis not showing with code from example

### ISSUE THREAD

**Issue by Lacni135** [i-schuetz/SwiftCharts#194]
Hi, I'm using the the example code of the bar chart but when I implement it, the labels, x and y axis are not showing.

**Comment by Lacni135** [comment]
Nvm just forgot to keep a strong reference in order to display the labels and values :P

**Comment by teldridge11** [comment]
@Lacni135 What exactly does "keep a strong reference" mean?  isn't any constant a strong reference?  I'm unable to get the labels/axes to show up as well.  Just using the example code and adding the chart view as a subview to an existing view.  What exactly did you change to make this work?
