### ISSUE TITLE
Is there a way to remove label value on Y axis ?

### ISSUE THREAD

**Issue by Domsware** [i-schuetz/SwiftCharts#195]
My need is to display a chart with not Y data, neither title or values.
This can be achieve by setting title to an empty string and setting a transparent color to Y values. But the space consumed by Y axis is then lost.

Is there any way to remove these data and save the related space?

**Comment by i-schuetz** [comment]
You can subclass `ChartAxisValue` and override `labels` to return an empty array, this way there's no text. Also set all spacing settings in `ChartSettings` and `axisStrokeWidth` to 0. Also you don't have to pass empty string as axis title, you can also pass an empty array - for the y-axis it should have the same effect but it signalises better what you want to do.
