### ISSUE TITLE
StackedBarCharts image - ahartman

### ISSUE THREAD

**Issue by ahartman** [i-schuetz/SwiftCharts#197]
![optiemonitor](https://cloud.githubusercontent.com/assets/688316/21292099/da43b72a-c4f8-11e6-8a90-b530f1220c55.jpeg)

**Comment by i-schuetz** [comment]
Ohhh, I see what you mean now!

You're right that it's not supported. 

I think that stacked bars layer should be improved to handle this.

Want to try to do it? Otherwise I'd have some hours available, for hire.

It would also be possible (maybe easier) to adjust the plus/minus example, which uses the generic views layer to produce the bars, to use stacked bar views instead.

**Comment by ahartman** [comment]
Dear Ivan,
I adapted your StackedBarsExample, please find attached.
After some thinking, this turned out to be quite easy, I extended your layers approach with a second BarsModel.
Depending on a value being positive or negative, it goes in one or the other barmodel.
You can also find some code to automatically determine Y-axis scaling based on bar values.
Take a look at my code adaptations and you should feel free to use this in your own examples if you wish.

You can help me with explaining what variables to adapt to accommodate more bars in a graph than the 4 in the example.
I have found bar width and the number of bars but how to decrease spacing between bars?
Also I want to find the setting to paint X-axis labels vertically so that they fit when charting more bars.
Finally I need to work out how to redraw for portrait orientation and I want to adapt your existing horizontal/vertical coding for that.

Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België
tel:		0032 3 666 0411
GSM:	0032 488 626 895

**Comment by ahartman** [comment]
Ivan,
I made issue 200 with my example code attached.

Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België
tel:		0032 3 666 0411
GSM:	0032 488 626 895

**Comment by ahartman** [comment]
Ivan,
For some time, I was too busy to work on my project with SwiftCharts.
I customised your StackedBars example, so that it shows positive AND negative values. The trick sits in func populateModels().
You asked me to send the code example in a gist which I just made: https://gist.github.com/ahartman/fc97b05537fc4d38d94b3bb10e798119.

You wrote to me on 5 January that when adding bars, either the spacing or the bars width will adjust. Of course all adjustment is finite, ideally one should bar width as a percentage of total available width and let the bars layer adjust bars width as well as spacing to make the lost of available room.

If I want the bar width to adjust while keeping spacing fixed, how do I use " the other initializer of stacked bars layer". 

Kind regards, André Hartman

**Comment by i-schuetz** [comment]
Hi André,

could you maybe use master?  As you can see here: https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartGroupedBarsLayer.swift#L247
it's possible to pass the spacing and the bar's width.

Note that master has some api changes but they are small and should be easy to follow with one of the examples.

To use master you have to update your podfile with this:

```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```

Let me know how it goes! If you want to use zooming/a scrollable view port let me know, the api to do this, especially with the bars is a bit unwieldy right now but I'm happy to help.

**Comment by ahartman** [comment]
Ivan,
I update my podfile but I seem not to get master. Pod update said SwiftCharts went from 0.5.1 to 0.5.1, which does not really bring me forward. Any ideas?
Regards, André Hartman
