### ISSUE TITLE
Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2

### ISSUE THREAD

**Issue by dustinspengler** [i-schuetz/SwiftCharts#198]
Im having trouble running SwiftCharts on my iOS simulator. It works fine on my phone (which is running iOS 10.2). Has anyone else had this issue and solved it?

When i try to build the app an error arises that says `Module compiled with Swift 3.0 cannot be imported in Swift 3.0.2`

here is my import statement for my podfile:
`pod 'SwiftCharts', '~> 0.5'`

**Comment by dustinspengler** [comment]
**Update**
I did a number of things which fixed the issue but to be honest I'm not sure exactly what actually solved the problem so here was the process.

1. I held option and clicked product -> clean build folder.
2. Reinstalled my cocoa pods.
3. Re-opened the app and clicked edit -> convert -> to current swift syntax... and followed through the conversion.
4. Clicked product -> clean

**Comment by i-schuetz** [comment]
Works fine for me. Was anything converted in the library? Does it work if you do a fresh installation of the library (maybe try in a new project)?

**Comment by dustinspengler** [comment]
No syntax was actually converted in the SwiftCharts frame work, so im not really sure what was causing the problem. Maybe just simply running the "convert to swift swift syntax" let xcode know it was up to swift version 3.0.2? Either way really I appreciate your quick response and awesome framework!
