### ISSUE TITLE
pod not working with swift 2.3

### ISSUE THREAD

**Issue by HPRaval** [i-schuetz/SwiftCharts#199]
I have downloaded pod 0.4 but it shows me lots of error in my Xcode 7.3 with swift 2.3. Can you please tell me the working version?

**Comment by HPRaval** [comment]
well i have changed my pod file to pod 'SwiftCharts', '0.4' instead of pod 'SwiftCharts', '~> 0.4' and it worked.

I have another question, how can i make chart to adjust in both portrait and landscape?

**Comment by HPRaval** [comment]
Thnx for your replay. Yes i have checked link you have provided, but re-instantiate the chart and i am creating charts dynamically, there is no predefined view controller, and add chart.view as subview, so it will be appreciated if i can achieve it without reinstantiation. I have tried to give flexible height and width to chart view but it only resize axis, chart remain same.

**Comment by i-schuetz** [comment]
Hmm not sure I understand the use case but you don't have to create the view again, only remove the subviews of the chart view and then initialize the chart (which is not a view) with the new parameters... and the same view. There's currently also no other way.

**Comment by i-schuetz** [comment]
Not sure I understand the use case, can't you somehow pass the view around in order to clear it and re-populate it using the new chart instance? Maybe post some code and I can provide more help. The chart is currently immutable, so there's no other way than re-instantiation.

**Comment by HPRaval** [comment]
Here is my class to show chart

```
class ViewController: UIViewController {

    var chart : Chart!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        chart.clearView()
        self.view.addSubview(chart.view)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    override func viewWillTransitionToSize(size: CGSize, withTransitionCoordinator coordinator: UIViewControllerTransitionCoordinator) {
        chart.view.removeFromSuperview()
        self.view.addSubview(chart.view)
    }
}

```

and the chart is initialised from another class

```
let next = storyboard?.instantiateViewControllerWithIdentifier("chartView") as! ViewController
        next.chart = data[indexPath.row].vc
        presentViewController(next, animated: true, completion: nil)
```

**Comment by i-schuetz** [comment]
You have to create the chart again when the size changes, since everything is configured based on this. You should restructure your code such that you can pass either a frame or the chart's base view as a parameter to the chart initialization code. Having the chart instantiated without any awareness of the view/available size in the controller seems also in general a bad practice...
