### ISSUE TITLE
15 Swift Compiler Errors

### ISSUE THREAD

**Issue by mac389** [i-schuetz/SwiftCharts#2]
I am trying to include SwiftCharts in a small graphing app targeted at iOS 8 or later. 

Swift Chart is the only library beyond UIKit in my app. I am programming in Swift.

I installed CocoaPods, and linked to the SwiftCharts pod without trouble. The same issues arise on versions 0.1 and 0.2. 

Console output: 
(Thanks in advance for your help)
![screen shot 2015-05-22 at 5 42 10 pm](https://cloud.githubusercontent.com/assets/2212010/7780193/e312273e-00a9-11e5-90c2-5c68492356f2.png)

**Comment by mac389** [comment]
I am using XCode 6.1 in OS 10.9.5

**Comment by i-schuetz** [comment]
This library uses Swift 1.2. You have to use XCode 6.3.
