### ISSUE TITLE
Adding trendlines ?

### ISSUE THREAD

**Issue by Peyo61** [i-schuetz/SwiftCharts#20]
I would be interested by the automatic addition of trendlines to line charts.

Simple linear trendlines are sufficient for my intended use, however I suppose higher order trendlines are of general interest too.

**Comment by i-schuetz** [comment]
I implemented a linear trendline generator and added an example https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/Examples/TrendlineExample.swift (it's also in the swift2.0 branch).

Higher order trendlines are certainly a nice to have, but that can be added later.

**Comment by Peyo61** [comment]
Thanks a lot Ivan.
