### ISSUE TITLE
Stacked Bar chart with positive and negative values

### ISSUE THREAD

**Issue by ahartman** [i-schuetz/SwiftCharts#200]
Please find example code attached.
Regards, André Hartman
[InterGraphViewController.swift.zip](https://github.com/i-schuetz/SwiftCharts/files/687634/InterGraphViewController.swift.zip)

**Comment by i-schuetz** [comment]
Hi André,

please don't open new issues for the same topic. This as well as the image from the other thread belong to the same initial issue.

Would it be possible to upload the code as a repo - or at least a gist?

I'll close this thread, let's continue the conversation in https://github.com/i-schuetz/SwiftCharts/issues/197
