### ISSUE TITLE
How to hide a vertical guide line on a bar chart?

### ISSUE THREAD

**Issue by anismansuri** [i-schuetz/SwiftCharts#201]
First of all, thank you for the library.

I want to hide vertical guide line in bar chart.

help will be appreciated.

Thanks

**Comment by ikousik** [comment]
@anismansuri @i-schuetz  Any update in this?

**Comment by i-schuetz** [comment]
To hide the guidelines, you have to pass `ChartGuideLinesLayerAxis.x` to the guidelines layer. To hide the axis line, you have to pass 0 as stroke width to the axis model, using [this setting](https://github.com/i-schuetz/SwiftCharts/blob/09520dd8496f5d57cc545e9bc0338912b201b05e/SwiftCharts/Chart.swift#L43).

**Comment by ikousik** [comment]
@i-schuetz Thanks !!  I am able to hide the vertical guide lines using ChartGuideLinesLayerAxis.x. But not able to set the stroke color only for one axis. As both of them are using the same axisStrokeWidth. How can I change only for Y axis?


let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: chartSettings, chartFrame: frame, xModel: xModel, yModel: yModel)
        let (xAxisLayer, yAxisLayer, innerFrame) = (coordsSpace.xAxisLayer, coordsSpace.yAxisLayer, coordsSpace.chartInnerFrame)

**Comment by i-schuetz** [comment]
You're welcome! Please read my comment again. I edited it shortly after I posted it.

**Comment by ikousik** [comment]
@i-schuetz  Thanks a lot buddy. 👍  it is working fine.
