### ISSUE TITLE
Autolayout issue - Axis not being displayed with provided sample

### ISSUE THREAD

**Issue by mgurnani** [i-schuetz/SwiftCharts#203]
Hello,

Using version SwiftCharts v0.5, Xcode 8 with Swift 3.

I am using the code provided in https://gist.github.com/i-schuetz/f6e285eb0c86bb831510
It had few minor changes to support Swift 3 syntax. 

I have a VC in Storyboard which has a UIView  with class set to 'ChartBaseView' in Identity inspector. This view is linked to the corresponding variable in Swift file.

However when I try to run it, I don't see the axis..  Attaching the screenshot and the swift code.. 
Thanks in advance for any help you can provide !!

[HelloWorld.txt](https://github.com/i-schuetz/SwiftCharts/files/694463/HelloWorld.txt)

![simulator screen shot 10-jan-2017 12 59 59 am](https://cloud.githubusercontent.com/assets/8996069/21780074/333c6924-d6d0-11e6-9d81-2be987239744.png)

**Comment by i-schuetz** [comment]
Did you store the chart instance in an instance variable? Otherwise is gets deallocated and this happens...

**Comment by mgurnani** [comment]
Yes I did.. It's actually already done in the sample code for Autolayout..

**Comment by i-schuetz** [comment]
I tested the gist and it still works. I think you are missing something. 

Btw, I migrated it to Swift 3.0 in case you need it (the previous code is now revision 2).

**Comment by mgurnani** [comment]
Strange.. Is it possible for you to share the project where it works for you?
If it helps, here's mine : https://github.com/mgurnani/TestSwiftCharts

**Comment by i-schuetz** [comment]
Oh. It seems you also have to set the module in the Storyboard to "SwiftCharts".
![screen shot 2017-01-10 at 14 19 33](https://cloud.githubusercontent.com/assets/1381744/21807631/f93758b8-d73f-11e6-87f6-f299cbd1f0cf.png)

**Comment by mgurnani** [comment]
Yeah !! That did it.. Don't know if it's just me but might be a good point to add in Readme..

Thanks much again for this library !!

**Comment by i-schuetz** [comment]
I added it to the gist, thanks!
