### ISSUE TITLE
getting compile error using Chart as IBOutlet

### ISSUE THREAD

**Issue by holiday-sunrise** [i-schuetz/SwiftCharts#212]
/Users/user/git/XXX/XXX/MyChartViewController.swift:14:5: @IBOutlet property cannot have non-'@objc' class type 'Chart'

`class MyChartViewController: UIViewController {

    @IBOutlet var lineChart: Chart!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        // Do any additional setup after loading the view.
    }`

whats wrong ?!?

**Comment by i-schuetz** [comment]
You have to use the chart view, not `Chart` as outlet. See [example](https://gist.github.com/i-schuetz/f6e285eb0c86bb831510).
