### ISSUE TITLE
ChartPointsViewsLayer.conflictSolver

### ISSUE THREAD

**Issue by NachoSoto** [i-schuetz/SwiftCharts#217]
Looks like this is unimplemented: `ChartPointsViewsLayer.init` takes a `ChartViewsConflictSolver<T, U>`, which is an empty class without subclasses.

Am I missing something?

Thanks.

**Comment by i-schuetz** [comment]
This class was meant to be a protocol but I had problems getting it to work with generics.

Its purpose is to allow to solve possible overlaps between chart points. This can be done in a variety of ways, depending on the layer and requirements... and I have not written implementations yet :)
