### ISSUE TITLE
help needed with custom tracker layer

### ISSUE THREAD

**Issue by DKalachniuk** [i-schuetz/SwiftCharts#218]
Hello, 
Please help me with custom tracker layer

```
        let trackerSettings = ChartPointsLineTrackerLayerSettings(thumbSize: 10, thumbCornerRadius: 5, thumbBorderWidth: 2, thumbBorderColor: UIColor.green, thumbBGColor: UIColor.red, infoViewFont: Fonts.regular(), infoViewFontColor: Colors.customText, infoViewSize: CGSize(width: 100, height: 44), infoViewCornerRadius: 5)
        let trackerLayer = ChartPointsLineTrackerLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: chartFrame, chartPoints: chartPointsData, lineColor: UIColor.blue, animDuration: 0.7, animDelay: 0, settings: trackerSettings)
        layers.append(trackerLayer)
```

is it possible to customize tracker view? I want to change only the text, instead of Pos: <data>,<data> I want to show my data

Thank you

**Comment by i-schuetz** [comment]
Hi @DKalachniuk,

you could use master. There have been several improvements here. Now there's no position view but you can pass a callback to handle yourself the position updates. There's also multi-line support, zoom&pan etc.

```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```

Note that master has some minor api changes. You can see this in the example.
