### ISSUE TITLE
Multiple y-axis for single x

### ISSUE THREAD

**Issue by rolyanos** [i-schuetz/SwiftCharts#219]
Hello, I sow multiple line chart example, but is it have support of multiple y-axis for singe x in current version?
For example: 
(x: 1, y1: 1, y2: 2, y3: 4,  .... yn: n)
.....

**Comment by i-schuetz** [comment]
If you mean only to have multiple y-values for an x value you just have to create the line models accordingly (in your case you pass [x: 1, y: 1, ...] to the first line model, [x: 1, y: 2...] to the second line model, etc.).

If you do actually need multiple y-axis, you can orient wth [MultiAxesExample](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/MultipleAxesExample.swift). It uses 4 y-axes and 4 x-axes, you just have to remove what you don't need.

**Comment by rolyanos** [comment]
@i-schuetz thanks for quick response. 
Ok, I will try to do it!

Thanks, Rostyk.
