### ISSUE TITLE
Unable to satisfy the requirements Following

### ISSUE THREAD

**Issue by GRoberson** [i-schuetz/SwiftCharts#22]
Hi, newbie cocoapods help please.
I'm having trouble installing the pod.
I am getting the following error:
[!] Unable to satisfy the requirements Following:

- `SwiftCharts (from` https: // github.com / i-Schuetz / SwiftCharts.git`, branch `swift2.0`) required by` `Podfile`

I followed the following steps:

- Sudo gem install cocoapods
- Pod install

And I used the Podfile seguite:
use_frameworks!
pod 'SwiftCharts': git => 'https://github.com/i-schuetz/SwiftCharts.git': branch => 'swift2.0'

How I do I solve this problem?

Thanks,

Geraldo Roberson

**Comment by i-schuetz** [comment]
Try with `pod update`

**Comment by GRoberson** [comment]
I've tried that but still presented the same problem.

**Comment by GRoberson** [comment]
I got the following message:
MacBook-Pro-de-Geraldo:Examples geraldoroberson$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `SwiftCharts` from `https://github.com/i-schuetz/SwiftCharts.git`, branch `swift2.0`
[!] Unable to satisfy the following requirements:

- `SwiftCharts (from `https://github.com/i-schuetz/SwiftCharts.git`, branch `swift2.0`)` required by `Podfile`

**Comment by i-schuetz** [comment]
I just tested it in a random project and it works. Your syntax has mistakes, but I assume it's a copy error, because you would get a different message. In any case ensure you have exactly this in your podfile:

```ruby
use_frameworks!
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git', :branch => 'swift2.0'
```

Then clean and try to install again:
```
rm -rf Pods
rm -rf ~/Library/Caches/CocoaPods
pod install
```

If it still doesn't work try:
```
pod install --verbose 
```
to see a more detailed error message.

**Comment by GRoberson** [comment]
The problem remains, unfortunately. Follows the result:

MacBook-Pro-of-Geraldo: Examples geraldoroberson $ rm -rf Pods
MacBook-Pro-of-Geraldo: Examples geraldoroberson $ rm -rf ~ / Library / Caches / CocoaPods
MacBook-Pro-of-Geraldo: Examples geraldoroberson $ pod install --verbose
  Preparing

Updating the local repositories specs

Updating repo spec `master`
  $ / Usr / bin / git pull --ff-only
  Already up-to-date.

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target` Pods`: (``)

Fetching external sources
-> Pre-downloading: `` SwiftCharts` from https: // github.com / i-Schuetz / SwiftCharts.git`, branch `swift2.0`
 > Git download
 > Git download
     $ / Usr / bin / git clone https://github.com/i-schuetz/SwiftCharts.git
     / Var / folders / sw / _1nbdbm94n15zpm6ht8p5q1h0000gn / T / d20150802-7197-27lglt --single-branch --depth 1 --branch swift2.0
     Cloning into '/ var / folders / sw / _1nbdbm94n15zpm6ht8p5q1h0000gn / T / d20150802-7197-27lglt' ...
  > Copying from SwiftCharts
  `/Users/geraldoroberson/Library/Caches/CocoaPods/Pods/External/SwiftCharts/5e40d770a9b413901c87c05fef706dda` to `Pods / SwiftCharts`

Resolving dependencies of `Podfile`
[!] Unable to satisfy the requirements Following:

- `SwiftCharts (from` https: // github.com / i-Schuetz / SwiftCharts.git`, branch `swift2.0`) required by` `Podfile`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:388:in `Handle_resolver_error '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:69:in `Rescue resolve in '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:56:in `Solve '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:535:in `Block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `Section '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:533:in `Resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:70:in `Analyze '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `Analyze '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `Block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `Section '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `Resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `Install! '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `Run_install_with_update '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `Run '
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `Run '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `Run '
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<Top (required)> '
/ Usr / bin / pod: 23: in `load '
/ Usr / bin / pod: 23: in `<main> '
MacBook-Pro-of-Geraldo: Examples geraldoroberson $

Earlier today I got to do the installation without problems. But I had to format my mac and when I went relizar the pod installation again this error occurred.
I'm grateful for your help.

**Comment by i-schuetz** [comment]
Ok, I could reproduce the error with cocoapods 0.38.

I was able to fix it by adding this to the podfile:

```ruby
platform :ios, '8.0'
```
It's weird that it doesn't work with 7.1 though, which is the deployment target. I'll investigate this.

**Comment by GRoberson** [comment]
Ok, now it works.
Thank you very much.
