### ISSUE TITLE
Bar chart rotate labels

### ISSUE THREAD

**Issue by jakewelton** [i-schuetz/SwiftCharts#225]
Hey. I'm wondering if there is a way to rotate the x axis labels? I can see when creating the ```ChartAxisValueDouble``` objects, the default label settings are applied (0 for rotation) and that these objects are then used to build the ```ChartBarModel``` objects. However I cannot find a way to edit the label settings for those objects, as the init only access tuples with ```String``` and ```Double```.

**Comment by i-schuetz** [comment]
Yes, you can find rotated labels [here](https://github.com/i-schuetz/SwiftCharts/blob/0.5.1/Examples/Examples/CustomUnitsExample.swift#L112)

**Comment by jakewelton** [comment]
That example appears to be for a line chart, however I'm after a bar chart. The bar chart init seems to be constructed differently.

**Comment by i-schuetz** [comment]
The axis values work exactly the same for all chart types. You just need to set the rotation in the label settings and pass this to the axis values.
