### ISSUE TITLE
Circles get clipped by chart frame

### ISSUE THREAD

**Issue by ilyavelilyaev** [i-schuetz/SwiftCharts#226]
![simulator screen shot 25 2017 18 37 27](https://cloud.githubusercontent.com/assets/7473350/23332363/85c9fe4e-fb89-11e6-9d8f-569767493b0f.png)

Is there any way to have this circles on sides unclipped and showed fully?

**Comment by i-schuetz** [comment]
This is in master right? The examples there have not been fully updated yet!

I think if you pass `clipViews: false` to the `ChartPointsViewsLayer` that generates the circles it will be fixed. I'll update this example in the next week.

**Comment by ilyavelilyaev** [comment]
I think I tried this, but it didn't help, because somehow circles were under the lines layer. And they were clipped by Chart.containerView. I've made fork for my needs and fixed this by adding chart.containerView.clipsToBounds = false

Overall, thank you! Nice library 👍
