### ISSUE TITLE
How to run Examples as an app?

### ISSUE THREAD

**Issue by troyshu** [i-schuetz/SwiftCharts#228]
I'm new to Swift, xcode, cocoapods, etc. I think I've set up cocoapods correctly, including the Podfile, and am able to `import SwiftCharts` without any errors in a brand new project (opening the '.xcworkspace' file, as cocoapods says).

Now, I'm trying to run the "Examples" app, like in the SwiftCharts [demo](https://www.youtube.com/watch?v=bD6uDF-KckM) video here. How would I go about doing running that app in the xcode simulator? 

e.g. Where should all the [Example source code](https://github.com/i-schuetz/SwiftCharts/tree/master/Examples) go, within an xcode project workspace? I've copied all the "Example" code into my xcode project's directory, then used "Add File" within xcode to actually add all those files into the workspace, and then changed settings in "Build Settings" so that xcode actually finds the "Info.plist" file in the "Supporting Files" directory in "Examples". But then I get about 6 "Use of unresolved identifier" errors where it looks like the code is trying to call classes like "ChartAxisValuesStaticGenerator" but failing for whatever reason? Maybe because my local "Pods" directory isn't setup correctly somehow (and thus the [SwiftCharts code that defines](https://github.com/i-schuetz/SwiftCharts/blob/a8a832d2cdf5f579c0636b6357281314e465f987/SwiftCharts/Axis/ChartAxisValueStaticGenerator.swift) "ChartAxisValuesStaticGenerator" doesn't exist locally)?

Anyways, that's most of what I've tried, I may have gone down the wrong rabbit hole(s). Just trying to run the "Examples" app, like in the SwiftCharts [demo](https://www.youtube.com/watch?v=bD6uDF-KckM) video, let me know what I can do. Thanks!

**Comment by i-schuetz** [comment]
You just have to download / clone the project, open SwiftCharts.xcodeproj and run it!

**Comment by troyshu** [comment]
Wow @i-schuetz responded, I feel like I'm talking to a celebrity! :) Doh that was easy... I got it working now. Thanks for the awesome library, excited to dig in!

**Comment by i-schuetz** [comment]
loool, thanks :D Glad I could help
