### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by GRoberson** [i-schuetz/SwiftCharts#23]
I tried to run the code on both xcode 6.4 and 7 beta 4  gave compilation error. I tried to convert the code to the latest version of swift, and keeps giving error. I wonder if a specific configuration is required to run the code?

thanks

**Comment by i-schuetz** [comment]
The swift2.0 branch should run with XCode 7 beta 4. Which errors?

Am Montag, 3. August 2015 schrieb Geraldo Roberson :

**Comment by luicm** [comment]
same problem here with Xcode 6.4, seams that the folder "Convenience" is missing after pod install
:)

**Comment by i-schuetz** [comment]
@GRoberson Pull request https://github.com/i-schuetz/SwiftCharts/commit/2733b1d15082c5358465d2c9e194bf648d71da72 removed some public identifiers, which causes the build to fail when the library is used as a pod. It's now fixed (https://github.com/i-schuetz/SwiftCharts/commit/88e2bc7cf689c95b897f23864916d2070cd0ea10).

@luicm For Swift 2.0 you have to use XCode 7. If you are using Swift 1.2 please run `pod update`, it should work now.

**Comment by GRoberson** [comment]
Hi,
Problem solved. Simply I deleted the project and downloaded again. I do not know what happened, but the compiler was reporting more than 200 errors. Now it's ok.
Thank you very much.
