### ISSUE TITLE
Rounded line graph w/ bubbles & StackedBar w/ labels

### ISSUE THREAD

**Issue by escully27** [i-schuetz/SwiftCharts#231]
Hello

Great library so far. Been pretty smooth sailing. Trying to implement this screen.

1.) How do I automatically pan a graph furthest to the right possible? (by dates, this is the most current part of the graph) Attempting various values for the deltax, but can't get it right.

2.) How do I use bubbles and a rounded line graph on the same chart? The bubbles don't behave the same as the lines, given the same data, when panning and zooming. Bubbles stay in place

3.) How do I add labels to the stacked bar graphs sections? Admittedly have not tried this part but wanted your advice first. 

Thank you in advance - any advice is greatly appreciated.

![insights](https://cloud.githubusercontent.com/assets/11113163/23841348/ad1ec1c2-0800-11e7-8f9a-d7faf441e555.png)

**Comment by i-schuetz** [comment]
Hi,

for the panning to the right side just pan it to the left by a very large (negative) number. The api for this is a little unpolished right now (for example there's also a parameter "elastic" which shouldn't be in the public interface) but this will be improved for the release.

The bubbles work in the same way as e.g. the `ChartPointsViewsLayer` used in `HelloWorld`. The key here is the `.translate` mode, which causes the bubbles to not scale, but only translate. I'm assuming this is what you mean with "stay in place" (?).

For the labels there are different options, you can use a `ChartPointsViewsLayer`, just like with the circles and let it generate the labels. You have to pass to it chart points representing the locations of the labels in the chart, i.e. the top of the bars. Here also you have to use `.translate` mode in order for the labels not to be scaled when zooming.

The other option, if you are using grouped bars, is to use `GroupedBarsCompanionsLayer` - this layer will notify you of the updated positions of all the bars during the transforms via a closure in which you can update your labels (or whatever views you want to attach to the bars) accordingly. Let me know if you have problems with this - there are no examples currently using this layer. It could make sense to add one.

**Comment by escully27** [comment]
Great! Thank you for the help. Will use that info asap and let you know how it goes.
