### ISSUE TITLE
Fill gradient below one of the two line graphs

### ISSUE THREAD

**Issue by Daemon-Devarshi** [i-schuetz/SwiftCharts#232]
I have to show a multiline chart, I think it can be easily achieved by SwiftCharts. The only tricky part for me is - I have to fill gradient below one of the two drawn lines.

Something like this:

<img width="515" alt="gradient below one of the line graphs" src="https://cloud.githubusercontent.com/assets/959126/23845646/581ea784-07ef-11e7-914f-d0dc14ac8d70.png">

Is the desired behavior achievable? Please suggest. Any code pointer would be of great help.

**Comment by ArturoLee** [comment]
Check out his response here: https://github.com/i-schuetz/SwiftCharts/issues/202
I actually would like to implement gradients in my chart. If I figure it out I'll let you know and make a pull request.

**Comment by ArturoLee** [comment]
I just made a pull request to add this feature: https://github.com/i-schuetz/SwiftCharts/pull/237
