### ISSUE TITLE
How to rotate the xaxis values to prevent overlapping?

### ISSUE THREAD

**Issue by surendias** [i-schuetz/SwiftCharts#234]
Hi can you give an example on how to rotate the xaxis values for a bar chart to prevent it from overlapping each other? Please refer the following file.
<img width="299" alt="screen shot 2017-03-14 at 6 46 26 pm" src="https://cloud.githubusercontent.com/assets/823317/23897016/8f7a0a14-08e6-11e7-8fd8-4c0cb7ded3a7.png">

**Comment by i-schuetz** [comment]
There is an [example](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/CustomUnitsExample.swift#L131) with rotated labels.

**Comment by surendias** [comment]
Hi Thanks! That helped. :)
