### ISSUE TITLE
Cocoapods version issue

### ISSUE THREAD

**Issue by Jobs23** [i-schuetz/SwiftCharts#235]
Hey Ivan,

First off, I love your charts repo. I had used your repo in a project previously too, and its awesome how you can customize mostly anything. I installed the framework via cocoapods as I had earlier done for your previous version. Everything's working, as in I am able to render charts onto my app. However, I am unable to access some of the features as shown in the examples. For example, the `ChartSettingsZoomPan` and the `stackFrameSelectionViewUpdater` are non existent in the pod among other features. Is it possible that the version of the pod isn't updated? Or do you suggest manual installation directly from your repo?

`pod 'SwiftCharts', '~> 0.5'`  
This is what I've put in my podfile. I even tried not specifying the version but to no avail. The version of the pod installed is 0.5.1

Suggestions as to why this is happening?

Cheers!

**Comment by i-schuetz** [comment]
Thanks!

You have to use master for that:

```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```

**Comment by Jobs23** [comment]
Thanks! That fixed it!
Cheers
