### ISSUE TITLE
App-Extension-Safe version of SwiftCharts 

### ISSUE THREAD

**Issue by bharat** [i-schuetz/SwiftCharts#236]
Hey guys. We use SwiftCharts in [Loop](github.com/LoopKit/Loop) and it's awesome. Recently I've been trying to embed SwiftCharts into an app extension so that I can show the chart on the lock screen.

This results in the following warning:
`warning: linking against dylib not safe for use in application extensions`

Can you produce an App Extension Safe version of SwiftCharts that we can use this way? I don't have a sense for why this might be difficult, so if it's a challenge - would love to explore and understand more. thanks!

Relevant docs:
https://developer.apple.com/library/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionOverview.html#//apple_ref/doc/uid/TP40014214-CH2-SW6

**Comment by i-schuetz** [comment]
Thanks for reporting this! A bit busy right now. I'll give it a look later this week.

**Comment by bharat** [comment]
Awesome, thank you! happy to help with the heavy lifting if you can give me some guidance.

**Comment by i-schuetz** [comment]
I honestly have no idea about this issue. My first step will be probably to google it ;)

**Comment by bharat** [comment]
I generally understand the basics of this, but what's not clear to me is what dependencies are in SwiftCharts that are actually causing it to be not extension safe. I'm happy to spin up a test project which demonstrates the issue if that'll help!

**Comment by i-schuetz** [comment]
No worries, I'll do this.

**Comment by i-schuetz** [comment]
Ok, I checked. Apparently all what's needed is to set "Require Only App-Extension-Safe API" in the build settings to yes. Actually someone fixed this already in master.

You can use master directly:
```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```

Let me know if that fixes it! Note that it has some minor api changes. It should be easy to orientate with the updated examples in master.

**Comment by bharat** [comment]
master is not compiling for me - but I made a branch in my own fork that cherry-picks the two relevant commits from master and that does seem to resolve it.

https://github.com/bharat/SwiftCharts/tree/0.5.1-extension-api-safe

thanks. I think we can consider this closed.

**Comment by i-schuetz** [comment]
What's not compiling in master? I just tested it and it works. Is it related with the extension?

**Comment by bharat** [comment]
Possibly! We're using Carthage. You can repro the problem by doing this:

```
$ echo 'github "i-schuetz/SwiftCharts" "dc80cd4fe7071f740bdfc19419ce30bb4abbfe61"' > Cartfile
$ carthage bootstrap
```

that commit id is the most recent commit to master.

Compile failure captured here:
https://gist.github.com/bharat/20282a745cb58c654cef1065b7562803

**Comment by i-schuetz** [comment]
Hmm. Reproduced it. What's weird is that it downloads the project correctly, if you go to `Carthage/Checkouts/SwiftCharts` and open the project it compiles fine. It's master. The things that the console reports as missing are there.

Seems to me to be a problem with Carthage itself. Any ideas? I never use Carthage so you probably have better chances to figure this out than me.

**Comment by bharat** [comment]
So it looks like the tvOS scheme is failing in master:

<img width="125" alt="screen-shot-2017-03-27-at-9 20 20-pm" src="https://cloud.githubusercontent.com/assets/54570/24390321/091d1720-133d-11e7-9c9a-94e8149caa39.png">

Are you seeing that as well?

Our carthage config currently builds all schemes. we can probably change that to restrict it to just the schemes we care about, but it probably makes sense for the tvOS scheme to build as well.

**Comment by i-schuetz** [comment]
My bad!! It should be fixed now, please try again!

**Comment by i-schuetz** [comment]
I'm assuming this is now working for you so I'll close this. Thanks for your help!
