### ISSUE TITLE
Resizing Graph

### ISSUE THREAD

**Issue by namo92** [i-schuetz/SwiftCharts#24]
I am looking to re-size a graph, in specific your scatter plot. What is the best way to do that? I would ideally like to have a scroll view in which the graph would occupy a portion of the screen while having a few things above/below it like buttons and text fields for inputs but would like to know how to resize the graph such that it won't occupy the entire view.

Thanks!

**Comment by i-schuetz** [comment]
When you create the graph you can pass either a view or a frame, specifying
the size.

2015-08-04 10:41 GMT+02:00 namo92 <notifications@github.com>:

**Comment by namo92** [comment]
Excuse my ignorance, I'm new to app development - Could you please elaborate a bit further on how to "pass" a view or frame? Do you mean you can just change the attributes in the Size Inspector? 

Essentially I have a "View" I would like to use, and have come up with these errors. They occur when I change the Superclass from UIViewController to UIView.

![screen shot 2015-08-04 at 8 37 54 pm](https://cloud.githubusercontent.com/assets/13638873/9058987/1af315a4-3ae9-11e5-8b08-c887cdb1fd79.png)

Thanks, your patience is appreciated!

**Comment by i-schuetz** [comment]
You just have to pass `Chart` a frame, which is a rectangle where the chart has to be displayed. The chart will generate a view with this frame. After that you can retrieve the view from the chart using `chart.view` and add it as a subview of another UIView, so it can be displayed.

You may want to start with the original code, then assign a different to `chartFrame`, e.g:

```swift
let chartFrame = CGRectMake(0, 100, 400, 350) 
```
With this the chart will become 400x350 pt (with origin at (0,100)).

Concerning custom views / UIViewController, etc. I suggest you look up iOS tutorials, which can give you a much better introduction than I could here.

**Comment by namo92** [comment]
That works perfectly. Thanks so much for your help, much appreciated!
