### ISSUE TITLE
there is no "zoomPan" varity in SwiftCharts0.5.1

### ISSUE THREAD

**Issue by ximalayashanjiao** [i-schuetz/SwiftCharts#241]
I downloaded your examples on github. I found that you used "**zoomPan**" varity in your examples, but there is no "zoomPan" varity in SwiftCharts0.5.1 . How I control zoom and pan in SwiftCharts0.5.1?

![2017-03-26 22 37 41](https://cloud.githubusercontent.com/assets/12340211/24332234/9c14c12c-1275-11e7-9da7-0429fa0c3226.jpg)

**Comment by i-schuetz** [comment]
That's currently only available in master!

```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```

**Comment by ximalayashanjiao** [comment]
thanks!
