### ISSUE TITLE
Use of unresolved identifier "ChartAxisGeneratorMultiplier"

### ISSUE THREAD

**Issue by najmul-csebuet** [i-schuetz/SwiftCharts#246]
I imported SwiftCharts. But when I went for use of ChartAxisGeneratorMultiplier in my project I am seeing above error.

What can I do now please?

**Comment by i-schuetz** [comment]
You have to use master for that:

```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```
