### ISSUE TITLE
x-axis coverage issues

### ISSUE THREAD

**Issue by jeeftor** [i-schuetz/SwiftCharts#248]
We are having an issue that depending on the number of y-axises we add it appears our x-axis isn't covering the whole charting area. 

If we have a single y-axis the x-axis covers the whole area - in this case with 4 axises we dont get full coverage.  Any ideas?

**1 Series**
![simulator screen shot apr 5 2017 1 30 37 pm](https://cloud.githubusercontent.com/assets/6491743/24718482/28360ac2-1a04-11e7-9683-a4ee1c25178f.png)

**2 Series**
![simulator screen shot apr 5 2017 1 31 34 pm](https://cloud.githubusercontent.com/assets/6491743/24718502/4119394c-1a04-11e7-9a92-a8e8238d00c6.png)

**3 Series**
![simulator screen shot apr 5 2017 1 32 20 pm](https://cloud.githubusercontent.com/assets/6491743/24718527/507923ac-1a04-11e7-93da-cf84f42c446b.png)

**4 Series**
![simulator screen shot apr 5 2017 1 29 33 pm](https://cloud.githubusercontent.com/assets/6491743/24718556/6a0147b4-1a04-11e7-8e0d-5474e6170392.png)

** Zooming **

Data will write past where the x-axis ends but the axis isn't correct...

![simulator screen shot apr 5 2017 1 20 37 pm](https://cloud.githubusercontent.com/assets/6491743/24718090/c60cf136-1a02-11e7-936a-9b9172a9639b.png)

**Comment by i-schuetz** [comment]
What version of SwiftCharts are you using?

Have you compared your code with the multi axes examples? It seems the x-axis is reserving additional space for the y-axes (this should be the only reason to cause it to shrink like this).

If you can't figure it out feel free to upload a gist or repo to your Github where I can reproduce it.

**Comment by i-schuetz** [comment]
Any news on this?
