### ISSUE TITLE
What is easiest way to set String to xValues? 

### ISSUE THREAD

**Issue by ban9ban3** [i-schuetz/SwiftCharts#25]
Thanks! (I'm newbie)

**Comment by i-schuetz** [comment]
You have to use `ChartAxisValueString`, for the axis values, where you pass the text and `order` which is an internal value to indicate the position:

```ruby
ChartAxisValueString("myName", order: 1)
```

[There is an example for this] (https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/Examples/NotNumericExample.swift). This has  some additional functionality which may be confusing as a start though. You may want to start with the [hello world example] (https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/Examples/HelloWorld.swift) and adjust it to use `ChartAxisValueString` for the x values.

**Comment by ban9ban3** [comment]
Wow!!. Thank you so much!!
