### ISSUE TITLE
Is it possible to make this chart scroll horizontally?

### ISSUE THREAD

**Issue by najmul-csebuet** [i-schuetz/SwiftCharts#255]

**Comment by i-schuetz** [comment]
What do you mean exactly with "scroll horizontally"? Panning? Programmatically? etc

**Comment by ethanfox** [comment]
Yes panning

**Comment by i-schuetz** [comment]
https://github.com/i-schuetz/SwiftCharts/wiki/View-hierarchy-and-transforms#making-the-chart-scrollable
