### ISSUE TITLE
Problem with tracking

### ISSUE THREAD

**Issue by Fermi37** [i-schuetz/SwiftCharts#257]
Hello. I have a problem with tracking chart values. I have used TrackerExample for my solution.  My solution works fine on the left part of the chart, but on the right value is not appear.  
![simulator screen shot 17 2017 0 58 37](https://cloud.githubusercontent.com/assets/1323303/25074912/cd883a2c-230f-11e7-9f70-36d2e67bae22.png)

![simulator screen shot 17 2017 0 58 42](https://cloud.githubusercontent.com/assets/1323303/25074913/d0bab594-230f-11e7-9da0-9e6577265463.png)

**Comment by i-schuetz** [comment]
Hi! At first sight: No idea. What version of SwiftCharts are you using? 

You can debug it yourself to see why there are no values. You could put a breakpoint e.g. [here](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartPointsLineTrackerLayer.swift#L217), for example (if you're using master) and step through the code to find problems. If you're using an older version it should be also easy to follow by debugging `ChartPointsLineTrackerLayer`. 

If you can't find it, you also can upload an example to your Github where the issue can be reproduced. I'll give it a look. Thanks!

**Comment by Fermi37** [comment]
I will try. Thank you.

**Comment by Fermi37** [comment]
I  take master version example, remove the second chart and change values.  Here are code and gif. Values near zero are disappearing. 

```swift 
let chartPoints = [(2, 5), (4, 4), (7, 3), (8, 2), (12, 0)].map{ChartPoint(x: ChartAxisValueDouble($0.0, labelSettings: labelSettings), y: ChartAxisValueDouble($0.1))}        
//        let chartPoints2 = [(2, 3), (3, 1), (5, 6), (7, 2), (8, 14), (12, 6)].map{ChartPoint(x: ChartAxisValueDouble($0.0, labelSettings: labelSettings), y: ChartAxisValueDouble($0.1))}
```
![mmlydmg017djc](https://cloud.githubusercontent.com/assets/1323303/25106756/edd7959c-23d3-11e7-9314-baf557b3f4d1.gif)

**Comment by i-schuetz** [comment]
Yeah I could reproduce the it and it's definitely a bug. Until it's fixed you can use a copy of `ChartPointsLineTrackerLayer` with the fix you proposed here. If there's anything causing problems to use this copy (e.g. private/internal fields) let me know and I'll change it.

**Comment by i-schuetz** [comment]
Sorry for having abandoned this, turned out to be more time consuming than I expected and don't have a lot of time these days. Hope you could get it working with the layer copy. Closing for now as there's a solution (although not an optimal one) and it doesn't seem to be affecting many users.
