### ISSUE TITLE
The Chart Values with decimals doesn't render the expected chart

### ISSUE THREAD

**Issue by abdul-naveed** [i-schuetz/SwiftCharts#258]
I tried with your app as an example. Which doesn't render a proper chart say for example i have the code below:

Class : AreasExample.swift

let chartPoints1 = [(0, 50.5), (2, 50.4), (4, 50.3), (6, 50.6)].map{ChartPoint(x: ChartAxisValueDouble($0.0, labelSettings: labelSettings), y: ChartAxisValueDouble($0.1))}
        let chartPoints2 = [(0, 60.5), (2, 60.4), (4, 60.3), (6, 60.2)].map{ChartPoint(x: ChartAxisValueDouble($0.0, labelSettings: labelSettings), y: ChartAxisValueDouble($0.1))}
        let chartPoints3 = [(0, 70.1), (2, 70.2), (4, 70.3), (6, 70.4)].map{ChartPoint(x: ChartAxisValueDouble($0.0, labelSettings: labelSettings), y: ChartAxisValueDouble($0.1))}

The above code draws a straight line how can i set the scale dynamically and draw the chart

How do i set the scale for y axis like 50.3,50.4,50.5,50.6,60.2,60.3,60.4,60.5 and on... only those in ascending order which exists in chart data points as a scale. Is there any attribute i can set and start using.

Is it possible to set the scale of y axis values as the same as what i have in the above chart points as y axis.?
Image attached for your reference. Please help me out in get this fixed.

![screen shot 2017-04-19 at 4 48 07 pm](https://cloud.githubusercontent.com/assets/22762759/25177573/38979b52-2520-11e7-982e-fe2cb0924389.png)

**Comment by i-schuetz** [comment]
Sure! Just adjust the y range?

You can do it like e.g. [here](https://github.com/grafiti-io/SwiftCharts/blob/master/Examples/Examples/HelloWorld.swift#L33):

```swift
let yModel = ChartAxisModel(firstModelValue: 0, lastModelValue: 16, axisTitleLabels: [ChartAxisLabel(text: "Axis title", settings: labelSettings.defaultVertical())], axisValuesGenerator: generator, labelsGenerator: labelsGenerator)
```
by changing the values of `firstModelValue` and `lastModelValue`. If you're passing a values array, just ensure that the values are in the range you want.

**Comment by abdul-naveed** [comment]
What version of Swift Charts i need to use?

**Comment by i-schuetz** [comment]
I assumed you're using the new one (master), because in you screenshot the content view is clipped, which doesn't happen in any previous versions.
