### ISSUE TITLE
.../Pods/SwiftCharts/SwiftCharts/Chart.swift:88:21: Failable initializer 'init(coder:)' cannot override a non-failable initializer

### ISSUE THREAD

**Issue by Jirka1111** [i-schuetz/SwiftCharts#26]
Just delete a question mark behind init.

**Comment by i-schuetz** [comment]
Are you using the correct XCode version? For the swift2.0 branch you need XCode 7 (beta 4).

**Comment by Jirka1111** [comment]
@i-schuetz I am using Version 7.0 beta (7A121l). I think it is beta 2.

**Comment by i-schuetz** [comment]
You need the latest beta... there where some changes.

**Comment by Jirka1111** [comment]
@i-schuetz Ok, I will try. Thank you.

**Comment by Jirka1111** [comment]
I have updated to Xcode beta 5 and the error is still the same...

... WatchKit Extension/InterfaceController.swift:62:62: Unnamed parameters must be be written with the empty name '_'

And another error:

.../Pods/SwiftCharts/SwiftCharts/Chart.swift:74:45: Value of optional type 'CGContext?' not unwrapped; did you mean to use '!' or '?'?

in the:

private func drawRect(rect: CGRect) {
        let context = UIGraphicsGetCurrentContext()
        for layer in self.layers {
            layer.chartViewDrawing(context: context, chart: self)
        }
    }

**Comment by i-schuetz** [comment]
These are new issues in beta 5. Everything works in beta 4. There's already a PR for that https://github.com/jeremygibbs/SwiftCharts/commit/c90999ed28094f5abafb2218a272d91b822e2dc8 

I'll merge it soon.

**Comment by i-schuetz** [comment]
The PR is merged. The swift2.0 branch works now in XCode 7 beta 5.

**Comment by Jirka1111** [comment]
@i-schuetz Thank you, everything works just great!
