### ISSUE TITLE
Cocoapods version bump

### ISSUE THREAD

**Issue by fabioknoedt** [i-schuetz/SwiftCharts#261]
Please, bump the version of the release to `0.5.2` or `0.6`.
There are changes in master that are not in the latest release.
Cocoapods is still using `0.5.1` with some old bugs fixed.

**Comment by i-schuetz** [comment]
I'll try to do a release this weekend, but can't promise!

The thing is that master has quite a lot of changes and there are 1-2 things that need to be fixed + some examples still have to be updated.

**Comment by fabioknoedt** [comment]
Release as `1.0` with "break" changes. So who has the `0.5.1` knows that if they upgrade, changes can happen. I am pretty sure people prefer to have a less-buggy library with old examples and than an old and (with some bugs) versions.

**Comment by i-schuetz** [comment]
I released `0.6`.
