### ISSUE TITLE
Stepped Line Graph

### ISSUE THREAD

**Issue by kmuddapu** [i-schuetz/SwiftCharts#263]
Hello , 
Can I draw a stepped line graph as below?

<img width="575" alt="screen shot 2017-05-08 at 9 37 18 pm" src="https://cloud.githubusercontent.com/assets/2403156/25832234/6697d2f8-3437-11e7-8e7c-423083c0951c.png">

**Comment by i-schuetz** [comment]
Sure! The small lines inside the grid require some special work, as there's no provided layer that supports this, but you can of course implement it. The best way to do this would be to create a custom layer, which works similar to the existing guidelines layer.

**Comment by kmuddapu** [comment]
Thanks for the reply. Is there any chance of adding stepped line graph in Examples

**Comment by i-schuetz** [comment]
This is just a normal line graph, for which there are already examples... The only special thing about it are the small markers in the grid, but this seems a little too specific.
