### ISSUE TITLE
Unable to change label Xais numbers to labels

### ISSUE THREAD

**Issue by moheny** [i-schuetz/SwiftCharts#264]
I'm trying to change the Xais numbers in the AreasExample.swift to text labels (dates).

so after digging into the code I have figure out that the following line is taking care of the labels.

let xValues: [ChartAxisValue] = (NSOrderedSet(array: allChartPoints).array as! [ChartPoint]).map{$0.x}

I have print the xValues ChartAxisValue  array and saw that the results are something like

▿ 0 : 0
  ▿ 1 : 0
  ▿ 2 : 1
  ▿ 3 : 1
  ▿ 4 : 2
  ▿ 5 : 2
  ▿ 6 : 3
  ▿ 7 : 3
  ▿ 8 : 4
  ▿ 9 : 4
  ▿ 10 : 5
  ▿ 11 : 5

So I have reused some methods in other project and recreate the array to the following structure

  ▿ 0 : 06.04
  ▿ 1 : 14.04
  ▿ 2 : 22.04
  ▿ 3 : 30.04
  ▿ 4 : 08.05
  ▿ 5 : 16.05

using these methods

    func createChartPoint(dateStr: String, percent: Double, readFormatter: DateFormatter, displayFormatter: DateFormatter) -> ChartPoint {
        return ChartPoint(x: createDateAxisValue(dateStr, readFormatter: readFormatter, displayFormatter: displayFormatter), y: ChartAxisValuePercent(percent))
    }
    
    func createDateAxisValue(_ dateStr: String, readFormatter: DateFormatter, displayFormatter: DateFormatter) -> ChartAxisValue {
        let date = readFormatter.date(from: dateStr)!
        let labelSettings = ChartLabelSettings(font: ExamplesDefaults.labelFont, rotation: 45, rotationKeep: .top)
        return ChartAxisValueDate(date: date, formatter: displayFormatter, labelSettings: labelSettings)
    }
    
    class ChartAxisValuePercent: ChartAxisValueDouble {
        override var description: String {
            return "\(formatter.string(from: NSNumber(value: scalar))!)%"
        }
    }

so I'm getting the results I want but, the graph/chart is not showing up. 
any suggestion of how to show dates instead of numbers ?

**Comment by i-schuetz** [comment]
Hey sorry for the delay! Were you able to solve this?

**Comment by moheny** [comment]
Thank you for taking your time and replying.
It's took me like 2 and half days to do it, I had to change the model a little bit to make it work.
still, it's a bit complicated process  to replace data in other charts.
I did found another bug tho, with the bubble calculation. if the the top info bubble is positioned on the top of the chart, the info bubble will be up-side-down. i did not find a way to fix yet. do you want me to open a new issue ?

**Comment by i-schuetz** [comment]
For the dates just orient with an example that use dates, e.g. [CandleStickExample](https://github.com/grafiti-io/SwiftCharts/blob/master/Examples/Examples/CandleStickExample.swift). You simply have to copy the code used to generate the axis to the chart you want to use.

I was able to reproduce the bubble issue. Showing inverted is correct as it tries to show the bubble below the point, because there's not enough space at the top. But it's not being positioned correctly. You can open a new issue if you want!

**Comment by quetool** [comment]
Hi @moheny, can you explain to me how do you achieved that?
