### ISSUE TITLE
How can I add ChartPoints dinamically and refreshing chart

### ISSUE THREAD

**Issue by quetool** [i-schuetz/SwiftCharts#266]
Hi! Your project is awesome! I need to add ChartPoints dinamically by requesting results from an Api and refreshing everytime a new ChartPoint is added... How can I achieve that? I am currently using Cubic Lines Chart! Thanks in advance!

**Comment by i-schuetz** [comment]
It's not possible to add points dynamically at the moment. The only way to do this is to re-create the chart with the updated state. The performance of this is of course not good if you need a high refresh rate. Pull requests welcome!
