### ISSUE TITLE
Custom View that scales with chart

### ISSUE THREAD

**Issue by zzhao36** [i-schuetz/SwiftCharts#267]
Hi, I'm trying to create my own custom bar view, similar to ChartStackedBarLayer. I'm currently implementing my system with ChartPoints and draw a rect with some precalculated width. However, whenever the rect is not correctly scaled when I zoom in on the graph. Is there some way I can achieve this? Thanks!

**Comment by i-schuetz** [comment]
Did you already read the wiki, in particular https://github.com/i-schuetz/SwiftCharts/wiki/View-hierarchy-and-transforms?

Also, I recommend you look at the examples, where views are scaled.

If you still are stuck please post an example where I can reproduce the issue!
