### ISSUE TITLE
Requesting documentation to show how to display hour String on xaxis

### ISSUE THREAD

**Issue by davidkneely** [i-schuetz/SwiftCharts#274]
Hereʻs the code that displays strings on the xAxis:

let xValues = [ChartAxisValueString("", order: -1)] + chartPoints.map{$0.x} + [ChartAxisValueString("", order: 10)]

But every single minute is showing up. I only want the xAxis to dispaly the hour as a tick. How do I update these xValues to have a minSegmentCount, maxSegmentCount, and multiple so that only the hour shows up on the xAxis?

ChartAxisValuesStaticGenerator.generateXAxisValuesWithChartPoints takes Doubles as input, not Strings.

Any help with this would be appreciated.

**Comment by i-schuetz** [comment]
In the [helloworld example](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/HelloWorld.swift) you find a more flexible way to generate the axis values / labels. You can use `ChartAxisGeneratorMultiplier` along with a label generator. In the [wiki](https://github.com/i-schuetz/SwiftCharts/wiki/Axes#generators) you also can read about this.

**Comment by davidkneely** [comment]
Thanks for the links and advice. I was able to successfully display the times on the xaxis. #274
