### ISSUE TITLE
Solid node colors in line charts

### ISSUE THREAD

**Issue by sstig** [i-schuetz/SwiftCharts#276]
Hi,

Anyway I can edit the nodes to be solid circle instead of donuts?
![notesattached_example_720-1](https://user-images.githubusercontent.com/927592/28587615-a7f95c1c-712c-11e7-9c2d-bc2f79f9f821.png)

**Comment by i-schuetz** [comment]
You can display any kind of views, please take a look at the examples or the wiki...
