### ISSUE TITLE
How do I remove ChartPointsLineTrackerLayer from the chart when I redraw it?

### ISSUE THREAD

**Issue by davidkneely** [i-schuetz/SwiftCharts#277]
Iʻve been using the "TrackerExample" in Examples. It works great but I canʻt for the life of me figure out how to remove the ChartPointsLineTrackerLayer when I remove the chart and draw a new one. Iʻve searched the code, documentation, and wiki and found nothing about how to remove the  "chartPointsTrackerLayer" when redrawing the chart.

Please help

**Comment by davidkneely** [comment]
Before refresh: 
![screen shot 2017-07-25 at 4 54 30 pm](https://user-images.githubusercontent.com/10734935/28602482-0a54a7f4-715a-11e7-9371-b36e61b418ec.png)

After refresh:
![screen shot 2017-07-25 at 4 55 00 pm](https://user-images.githubusercontent.com/10734935/28602492-11b8e924-715a-11e7-8e6c-13ad393c0ef1.png)

**Comment by i-schuetz** [comment]
Just remove all the subviews of the chart's view! [Here](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/RangedAxisExample.swift#L242) for example in the rotate method everything is cleared before re-adding the chart.

**Comment by i-schuetz** [comment]
I forgot: The labels in the example are added to the controller's view - you have to of course also remove them, by iterating through the array where they are stored and call `removeFromSuperview()`

**Comment by davidkneely** [comment]
These links helped me fix the issue. #277
