### ISSUE TITLE
Bar chart

### ISSUE THREAD

**Issue by rejdic** [i-schuetz/SwiftCharts#280]
Would it be possible to create a chart like the one they have here for the "Total of Steps" Chart?

https://camo.githubusercontent.com/0858db57496e5802ed511310896b44430b9ac551/687474703a2f2f692e696d6775722e636f6d2f725149683371442e676966

Im guessing you would start with a regular bar chart?

**Comment by i-schuetz** [comment]
Yeah bars should be the way to go - in any case you would use 2 similar layers, one for the static background items and the other for the foreground animation. The bars layer allows to pass a custom bar view generator. You will have to experiment a little to get it working but it's definitely possible.
