### ISSUE TITLE
BarChart with one Date item?

### ISSUE THREAD

**Issue by seenoevo** [i-schuetz/SwiftCharts#281]
This is pretty much the same issue as in #106 , however instead of using `ChartAxisValueString` as in the `NotNumericExample.swift`, I'm actually using `ChartAxisValueDate`.

Since `ChartAxisValueDate` does not have an `order` parameter to pass in, how can I show one bar if there's only one `Date` item when creating a `ChartAxisModel`?

**Comment by i-schuetz** [comment]
I'll take a look into supporting one value axis soon (maybe this or the next weekend), in the meantime just add some invisible padding values... similar to how it's done with order. E.g. -day, +day

**Comment by seenoevo** [comment]
@i-schuetz I'm not sure what you mean?

Can you provide an example please?...Thanks!

**Comment by i-schuetz** [comment]
Just add two fake surrounding axis values, and set their visibility to hidden. So you have a total of 3 axis values instead of 1. The offset to the center value is actually not important, it just has to be the same so your value appears at the center of the axis.

**Comment by seenoevo** [comment]
@i-schuetz thanks for the explanation, are you referring to something like this?

```
let xValues = [
            createDateAxisValue("01.10.2015", readFormatter: readFormatter, displayFormatter: displayFormatter),
            createDateAxisValue("03.10.2015", readFormatter: readFormatter, displayFormatter: displayFormatter),
            createDateAxisValue("05.10.2015", readFormatter: readFormatter, displayFormatter: displayFormatter)
        ]
        
let xModel = ChartAxisModel(axisValues: xValues, axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings))
```
where `01.10.2015` and `05.10.2015` are "fake" surrounding x-axis values of the real `03.10.2015` axis value, and then just set the two's visibility to hidden?

or are you referring to something else?...sorry for the noobish clarification, first time learning this code after reading the README

thanks for the awesome library!

**Comment by i-schuetz** [comment]
Yeah something like that! It's not pretty but it should work until there's a better solution. I think if you work with timestamps just working with milliseconds deltas (e.g. -/+ 1 ms) should be enough, maybe it simplifies things. Thanks!

**Comment by seenoevo** [comment]
@i-schuetz thanks, playing around with the `CustomUnitsExample`, I was able to show just one axis value:

![simulator screen shot jul 31 2017 9 23 56 pm](https://user-images.githubusercontent.com/8109158/28809200-aca611b0-7636-11e7-8569-9cde3a7f0e12.png)

Now I just need to do this hack to my code.

I hope you can support one axis graph soon. Thanks I really appreciate it!

**Comment by i-schuetz** [comment]
It's not convenient but I'm not sure I would call it a hack either... technically it's correct as the bottom line an axis line and each point on an axis stands for an actual axis value - if you had an axis with only one value it would be a point, not a line. Of course a (so to say) one dimensional chart is a valid use case and shouldn't require more than one axis line, but that's not what I had in mind when I developed this. Either way will look into if I have time ;)

**Comment by seenoevo** [comment]
I understand your point of view....if it was a line chart as in the case of the above example because yes, "one value...would be a point, not a line."

But what about bar charts?...which I'm currently using.

Since it's a vertical bar, there's no prerequisite to have 2 points, but just one point since the bar extends up from that particular point on the axis. 

Forgive my ignorance as I'm not even on the same level of experience as you are so I wouldn't be able to help you with this, but is it that difficult/time consuming to implement this feature?

If it is, my apologies as I was only trying to help you improve your useful library.

Either way, I will continue to use this library. Thanks!
