### ISSUE TITLE
Hide label in linechart

### ISSUE THREAD

**Issue by ak0815** [i-schuetz/SwiftCharts#282]
Hi,

how can  hide this labels?

Thanks
Andy
![2017-07-31_10-59-27](https://user-images.githubusercontent.com/7480191/28770403-543a3e86-75df-11e7-9760-d0a308160ff2.png)

**Comment by i-schuetz** [comment]
I don't know which example you're using, you should be able to hide them by simply removing the layer that is showing them.

**Comment by ak0815** [comment]
Thanks. But I don´t know which layer it is. I didn´t set a layer for this.

**Comment by i-schuetz** [comment]
The instances that are passed to the chart layers array... delete them and you will see the labels (and the rest of the content) disappear... delete one by one and you will find which layer is responsible for the labels.
