### ISSUE TITLE
Rotating chart point labels and programmatically jump to a specific bar

### ISSUE THREAD

**Issue by Plutini** [i-schuetz/SwiftCharts#288]
Hi. I have been playing around a bit with this library (to probably later use it on a project) and there is some things that I would like to do but don't know how to do it or if it is (currently) possible to do.

So, right now I have this:

![screen shot 2017-08-18 at 14 45 49](https://user-images.githubusercontent.com/3579409/29462752-5692d402-8428-11e7-897b-5331e18c7c87.png)

I can drag it side-by-side (pan left and right, and with zoom locked and disabled), and it is displaying the values correctly. But there is some  things that I have not found how to do. I am trying to make it similar to this:

![screen shot 2017-08-18 at 15 29 47](https://user-images.githubusercontent.com/3579409/29463320-324f6874-842a-11e7-8a8a-bb310f27ba00.png)

Two of the things that I can't do, and are in the above image, is to rotate the labels 90º and change the color depending on the percentage value. If the percentage value is below 50% then the label will be above the bar and coloured black, but if it is 50% or above it will be "inside" the bar and coloured white.

The other thing I would like to do is to programmatically jump to a specific bar in the chart (with animation, if possible). The ideia here is, again based on the above image, when a row in the table is selected it should highlight the corresponding bar in the chart, and so it needs to make the bar visible if it is not showing it.

And... that's it. Hope to hear from you soon 😄 

And thank you for this library! I'm having a great time learning it. I specially like the way everything is built with layers

**Comment by i-schuetz** [comment]
Hello... thanks. Rotating or styling the labels should be straightforward, since these are just external custom views... let me know which specific problem you have with it.

Re: jumping to a bar, the chart instance has methods to pan (and zoom) programmatically either to a specific (screen) position or by a (screen) delta... you have to calculate the distance to pan for the selected bar, which depends on the index, bar width, spacing settings, etc. you passed. There's no built-in "pan to bar x".

**Comment by Plutini** [comment]
I have been working on this a bit more and I found out how to rotate and color the labels. I was creating the layer chart points correctly but not using the model data properly when creating the label layer. So, at least that part, is done.

Regarding the jumping to a bar, I'll try to implement a "pan to bar x" functionality based on your advice about calculating the distance to pan. I'll later let you know how it went.

**Comment by Plutini** [comment]
Hello! Just wanted to let you know that I was able to create a "pan to bar x" functionality. It is not perfect (far from it), but it is enough for now.

So this issue can be closed.

Thanks for everything!
