### ISSUE TITLE
barSpacing variable gone

### ISSUE THREAD

**Issue by ahartman** [i-schuetz/SwiftCharts#289]
In the latest version of SwiftCharts, downloaded 27 August, you can no longer let SwiftCharts calculate barWidth by only passing barSpacing. The parameter barSpacing is gone, there is only a parameter barWidth.

**Comment by i-schuetz** [comment]
Where's that? In [ChartGroupedBarsLayer](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartGroupedBarsLayer.swift#L44) at least you can pass both.

**Comment by ahartman** [comment]
This is in ChartStackedBarsLayer.swift. ChartStackedBarsLayer.swift has only barWidth, see below.
Kind regards, André Hartman

public init(xAxis: ChartAxis, yAxis: ChartAxis, innerFrame: CGRect, barModels: [ChartStackedBarModel], horizontal: Bool = false, barWidth: CGFloat, settings: ChartBarViewSettings, stackFrameSelectionViewUpdater: ChartViewSelector? = nil, tapHandler: ((ChartTappedBarStacked) -> Void)? = nil)

**Comment by ahartman** [comment]
Dear Ivan,

ChartStackedBarsLayer only has barWidth:

init(horizontal: Bool, layer: ChartCoordsSpaceLayer, barWidth: CGFloat, viewGenerator: ChartStackedBarsLayer<ChartPointViewBarStacked>.ChartBarViewGenerator? = nil) {
        self.stackedViewGenerator = viewGenerator
        super.init(horizontal: horizontal, layer: layer, barWidth: barWidth, viewGenerator: nil)
    }





Met vriendelijke groeten, Kind regards, Mes meilleures salutations,
André Hartman
Rodeweg 90
B-2920 Kalmthout
België
tel:		0032 3 666 0411
GSM:	0032 488 626 895

**Comment by i-schuetz** [comment]
Sorry for the long delay... and also because this is a non-answer: I honestly don't remember why it was removed and don't have time to investigate this. But you can determine the spacing indirectly by setting the width (and possibly the zoom level). Hope this doesn't cause a lot of trouble!
