### ISSUE TITLE
Deployment target 8.4

### ISSUE THREAD

**Issue by filip982** [i-schuetz/SwiftCharts#29]
Please change deployment target from 8.4 to lower (8.0). Downloaded using Carthage and when added to project and on import SwiftCharts, compiler gives an error:
module file's minimum deployment target is ios 8.4 v8.4
I worked around like this: changed it manually and carthage build and then droped the library
Thx in advance.

**Comment by i-schuetz** [comment]
Yes, sorry, this slipped through the recently added Carthage support, it's already on my list (also the merge to the Swift 2.0 branch). It will be fixed this week.

**Comment by i-schuetz** [comment]
Fixed
