### ISSUE TITLE
StackBars in TableViewCell difficult to tap

### ISSUE THREAD

**Issue by dustinspengler** [i-schuetz/SwiftCharts#292]
I have created a calendar app which uses SwiftCharts to display a time bar like this:

![img_6678](https://user-images.githubusercontent.com/16605397/30242305-ccb92ccc-9548-11e7-8a5f-322bb7336f8f.PNG)

I nest the chart bars inside UITableViewCells. When i tap on the cells (not the event bar), I navigate to another view. Everything currently works great except when I tap directly on the bars themselves. It seems like there is a tapGestureRecognizer or something on the bars that is overriding the cell tap. Id like to either disable to tapRecognizer on the bar or have the tap trigger the segue. Any idea how I might do either?

**Comment by dustinspengler** [comment]
This is my code so far but it doesnt seem to work:
`            barStack = ChartStackedBarsLayer(xAxis: xAxis , yAxis: yAxis , innerFrame: innerFrame, barModels: barModels, horizontal: true, barWidth: 75, settings: chartviewSettings) {tappedBar in
                print("user tapped a bar")
            }`

**Comment by i-schuetz** [comment]
Hm. Seems like a bug! Unfortunately I don't have time to fix this now, but feel free to give it a look and submit a pull request... the bar layers are straight forward (just custom views with tap handlers), shouldn't be difficult to debug. Sorry for the delay!

**Comment by dustinspengler** [comment]
I found a work around for now by adding a long tap gesture to my tableview like this:

`let longPressGesture:UILongPressGestureRecognizer = UILongPressGestureRecognizer(target: self, action: #selector(self.handleLongPress(_:)))`
`    func  handleLongPress(_ longPressGestureRecognizer: UILongPressGestureRecognizer) {
        if longPressGestureRecognizer.state == UIGestureRecognizerState.began {
            let touchPoint = longPressGestureRecognizer.location(in: self.view)
            if let indexPath = self.usersTableVew.indexPathForRow(at: touchPoint) {
                let cellData = self.homeTableData[indexPath.section][indexPath.row]
                GlobalNavDelegate.homeVCDelegate!.selectedName = cellData.name
                GlobalNavDelegate.homeVCDelegate!.segueToEditPersonCal()
            }
        }
    }`

For some reason if you tap and hold, it by-passes the `ChartStackedBarsLayer` tap handler. I'm guessing I did something weird with z-indexes or adding different views to a parent view or something along those lines, so this most likely is not be a bug with the framework. 

Many thanks for the feedback and great framework!
