### ISSUE TITLE
Change Candlestick Fill

### ISSUE THREAD

**Issue by jimijon** [i-schuetz/SwiftCharts#296]
It seems like ChartCandleStickLayer has hard coded the fill colors of black and white for the candle in the candlestick chart.

What is the proper way to change this color?

**Comment by c-st** [comment]
It seems to me that the colours are currently hardcoded in `ChartCandleStickLayer.generateScreenItems()` and cannot be customized right now.

The code setting the colours based on whether the stick is decreasing or increasing is this one (adjusted to using red + green):
`let (rectTop, rectBottom, fillColor) = closeScreenY < openScreenY ? (closeScreenY, openScreenY, UIColor.green) : (openScreenY, closeScreenY, UIColor.red)`.

So either you can copy that file over to your project and customize it or you fork this project and adjust `ChartCandleStickLayer` to allow setting those colours in `init`.

**Comment by i-schuetz** [comment]
Pull request merged - closing this.
