### ISSUE TITLE
ChartPointsScatterCrossesLayer does not allow a change of colour

### ISSUE THREAD

**Issue by KaisEbraheem** [i-schuetz/SwiftCharts#298]
I have tried to change the colour for cross point type to anything but black. It always draws crosses in black. Any idea if this is a bug.  Thanks

**Comment by i-schuetz** [comment]
It should be customizable - the passed fill color is used as stroke color. See https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartPointsScatterLayer.swift#L227

Please ensure you are passing correctly the color.

**Comment by KaisEbraheem** [comment]
Thanks  for your prompt feedback.
Indeed I tried just that. The itemFillColor works file for circle, square,
triangle, except for cross, where the itemFillCollor is supposed to be used
for the context strokColor, but it doesn't.  Strangely enough, I have even
hard-coded the line:
  context.setStrokeColor(itemFillColor.cgColor) to context.setStrokeColor
(UIColor.red.cgColor)
and still crosses are painted black.

I guess, there is an issue here.

Regards,
Kais

**Comment by i-schuetz** [comment]
You will have to debug this, since I don't have time (sorry). It shouldn't be difficult to figure by looking in the scatter layer. If there's a bug then a pull request is welcome.
