### ISSUE TITLE
Support for gradient in line chart

### ISSUE THREAD

**Issue by dehlen** [i-schuetz/SwiftCharts#302]
Hi,

I was searching for the possiblity to apply a gradient to a line chart. I just implemented this in a fork. I will open up a PR if you are interested to include this feature into the main repository. Here is a screenshot of the current result:

![simulator screen shot - iphone 8 plus - 2017-09-22 at 16 18 02](https://user-images.githubusercontent.com/680180/30748796-a5a7df70-9fb1-11e7-9039-0e6e17d595e5.png)

Thank you very much for the ongoing effort keeping this project alive :)

Cheers,
David

**Comment by riccardoch** [comment]
Is it already possible to set gradient direction? 
I have a line chart with temperature values on the vertical axis, so it would be nice to have cold colors for low values and warm colors for the higher ones.
