### ISSUE TITLE
Gradient fill for curved areas

### ISSUE THREAD

**Issue by dehlen** [i-schuetz/SwiftCharts#304]
Hi,

as mentioned in #202 

> ChartAreasView can generate only straight lines at the moment. 

I'll open a up PR in a second where I implemented gradient fill for curved areas too. However the solution is not ideal I guess. So would be great if someone could give me some tips on how to improve on this. I think we can discuss the exact code optimizations in the PR issue.

However for documentation purposes, so everybody finds this issue when they search for the described behaviour here is a screenshot of the working "AreaExample", but with curved line graphs and a gradient fill.

![simulator screen shot - iphone 8 plus - 2017-09-25 at 23 32 28](https://user-images.githubusercontent.com/680180/30832180-74282752-a24a-11e7-9048-11b8ca6ab069.png)

Thank for the superb library :)

**Comment by i-schuetz** [comment]
Nice, thanks!

**Comment by xinnai** [comment]
How to make gradient color between many colors? I use `areaColors: [.red, .green]`,but only a green color displays.
