### ISSUE TITLE
Generate values for y-axis based on input min and max values 

### ISSUE THREAD

**Issue by zoufishanmehdi** [i-schuetz/SwiftCharts#306]
Hi, I would like to input min and max y-axis values for a chart in order to determine y-axis values (and  its increments) as numbers rounded to thousands of units. 

Right now I have to manually enter values using `yValues = stride(from: 0, through: 3,838,383,838,282, by: 3,838,383,838,282/4).map {ChartAxisValuePercent($0, labelSettings: labelSettings)}` Is there a way to round up the max value indicated here to 4,000,000,000,000, for example, and generate the increments for y-axis based on those min and max values as numbers rounded to thousands of units? Based on the numbers provided above, the resulting y-axis values would be: 
0
1,000,000,000,000 
2,000,000,000,000
3,000,000,000,000
4,000,000,000,000

Thanks!

**Comment by i-schuetz** [comment]
Please take a look at the wiki and examples - if it doesn't help ask in stackoverflow. The issues are not meant to be used for questions anymore (as stated in the readme). Thanks!
