### ISSUE TITLE
How to put the graf in a view

### ISSUE THREAD

**Issue by ChopperNOR** [i-schuetz/SwiftCharts#307]
Hi
How do I put the graf in a define view(hight, width), and not use addSubview(chart.view)?
Best regards
Njål Are

**Comment by nets-rac** [comment]
I think it should work this way:

- add a view to your controller and create an outlet
- use height and width of this view to calculate height and width of your chart and bars and so on
- add your chart to your view -> yourView.addSubview(chart.view)

**Comment by ChopperNOR** [comment]
Thank You 😀
