### ISSUE TITLE
Hatched Bars?

### ISSUE THREAD

**Issue by nets-rac** [i-schuetz/SwiftCharts#308]
HI,

is it possible to create hatched bars in a bar chart?

**Comment by i-schuetz** [comment]
As mentioned in the issue template, the issues are not meant to be used for this kind of questions.

**Comment by i-schuetz** [comment]
Actually, this question is constructive in the sense that the wiki should be clearer about customizing bars. I added a "[custom views](https://github.com/i-schuetz/SwiftCharts/wiki/Bars#custom-views)" section to it.

(Yes, it's possible).
