### ISSUE TITLE
Programmatically change the color of ChartPointTextCircleView in generator

### ISSUE THREAD

**Issue by av8ramit** [i-schuetz/SwiftCharts#310]
I want to change the color of `ChartPointTextCircleView` programmatically based on which line they are attached to. The `ChartPointsViewsLayer` constructor takes in a `circleViewGenerator` but outside of creating multiple of these I'm not sure how I can programmatically pass in the color.

**Comment by danieldesouzadev** [comment]
`           let v = ChartPointTextCircleView(chartPoint: chartPoint, center: screenLoc, diameter: 16, cornerRadius: 8, borderWidth: 0, font: ChartDefault.fontWithSize( 8))
            
            if ( number <= 2) {
                v.layer.backgroundColor = UIColor.Black.cgColor
            } else {
                v.layer.backgroundColor = UIColor.White.cgColor
            }`

I do not know how to do it differently.

**Comment by av8ramit** [comment]
@danieldesouzadev thanks, I ended up declaring the generator in my for loop. Thanks!
