### ISSUE TITLE
how to chance color of selected bar ? 

### ISSUE THREAD

**Issue by ismailtosun** [i-schuetz/SwiftCharts#311]
hello, thanks for this awesome library ! 

my question is that how to chance color of selected bar ?

**Comment by i-schuetz** [comment]
As mentioned in the issue template, the issues are not meant to be used for this kind of questions.

**Comment by i-schuetz** [comment]
Actually this is constructive feedback, in the sense that the wiki should be clearer about this. Added a section: https://github.com/i-schuetz/SwiftCharts/wiki/Bars#selection-handling
