### ISSUE TITLE
ChartPointsViewsLayer and zoom

### ISSUE THREAD

**Issue by BunsSlider** [i-schuetz/SwiftCharts#313]
Hello, thanks for such a great library!
In my project I need to show year label above every bar. Also it should be scrollable, so I use maxZoom properties 
       

```
 chartSettings.zoomPan.maxZoomX = 2
 chartSettings.zoomPan.minZoomX = 2
 chartSettings.zoomPan.minZoomY = 1
 chartSettings.zoomPan.maxZoomY = 1
```

then I create ChartPointsViewsLayer and add it to my chart

      let labelsLayer = ChartPointsViewsLayer(xAxis: xAxisLayer.axis, yAxis: yAxisLayer.axis, chartPoints: labelChartPoints, viewGenerator: { (chartPointModel, layer, chart) -> UIView? in
            let label = HandlingLabel()
            label.text =  chartPointModel.chartPoint.x.description
            label.font = UIFont.systemFont(ofSize: 12)
            label.sizeToFit()
            label.center = CGPoint(x: chartPointModel.screenLoc.x, y: chartPointModel.screenLoc.y - 10)
            return label
        })

but the labels are zooming too

![screenshot](https://user-images.githubusercontent.com/739803/32536380-54fe53f0-c46f-11e7-937e-f00514485b02.png)

How can I make labels not stretched?

**Comment by i-schuetz** [comment]
Please take a look at https://github.com/i-schuetz/SwiftCharts/wiki/View-hierarchy-and-transforms#chartpointsviewslayer-transform-modes. It's explained there.

**Comment by preethacmu** [comment]
could you please comment how did add ChartPointsViewsLayer to chart MasterWatcher
