### ISSUE TITLE
Storyboard view

### ISSUE THREAD

**Issue by ahmadabudawod** [i-schuetz/SwiftCharts#314]
I have run the Chart example and everything is fine, but when I try to use storyboard as standard view the chart didn't display the code below 

fileprivate func showChart(horizontal: Bool) {
        self.chart?.clearView()
        let chart = barsChart(horizontal: horizontal)
        self.chartView = chart.view
// Hide the below code and assign view manualy from storyboard
//        view.addSubview(chart.view)
        self.chartView.backgroundColor = .red
        self.chart = chart
    }

**Comment by i-schuetz** [comment]
Take a look here https://gist.github.com/i-schuetz/f6e285eb0c86bb831510

May need some changes to compile.
