### ISSUE TITLE
Scrolling & selecting on same bar graph

### ISSUE THREAD

**Issue by escully27** [i-schuetz/SwiftCharts#316]
Hello!

I really looked for any help on this issue, it seems doable with this level of framework but I cannot find any answers so far.

I am trying to have a bar graph this is both scrollable (horizontally) and that has a selection tracker. I am able to get each of those working properly on their own but when I have them both on the same graph at the same time, things get buggy.

It seems to break and put the tracker layer beneath the graph after I scroll, so that it only triggers the tap when I select around a bar line (I want it to work when I tap a bar, of course)

Any help or advice would be great! Let me know if I need to clarify further!

Thanks

**Comment by i-schuetz** [comment]
It's possible, I remember having implemented this use case (bars with zooming and panning + tracker). It may need some special settings/tweaks which I don't remember. If you put a (complete, self contained) example together it's easier for me to take a look.

**Comment by rajan2211** [comment]
Is is possible to scroll the view with multiple bar those are out of the bound of the screen?
