### ISSUE TITLE
Highlight specific bar

### ISSUE THREAD

**Issue by lsnmarcinr** [i-schuetz/SwiftCharts#317]
Can I highlight specific bar on chart? 

I have external spreadsheet (table) with values - when I click on value in table I need to highlight specific bar. How can I do that?

Here is preview:

<img width="992" alt="zrzut ekranu 2017-11-29 o 09 30 19" src="https://user-images.githubusercontent.com/26714814/33365263-fa8a88ce-d4e7-11e7-9934-dbefe52a8e65.png">

**Comment by lsnmarcinr** [comment]
I found solution to do that through ChartPointsViewsLayer, but it's mostly not clearly to understand.

**Comment by i-schuetz** [comment]
Sorry, missed this issue - yes, you can pass the bar layers a view generator as well, you can either re-create the chart each time (with disabled animations) where you generate a highlighted view for the current selection, or you can store the generated views in your own data structure and manipulate these, avoiding having to re-create the chart.

**Comment by lsnmarcinr** [comment]
Okay, what if I want to do the same with ChartStackedBarsLayer? I don't have viewGenerator there, I'm using ChartStackedBarModel as barModels. How can I get bar views and highlight them?

**Comment by i-schuetz** [comment]
Stacked bars has also a view generator so the same approach is possible.

These are of course workarounds - ideally the layers should have a method to do this.  This isn't difficult to implement, I'll add it to my list but I have no idea when I'll have time - if you want to do a pull request I'd be happy to merge it.

**Comment by i-schuetz** [comment]
I uploaded a fix to master - now the `barViews` array of the plain/stacked bar layers in exposed, so you can just retrieve the bar from these. You have to use master!

**Comment by lsnmarcinr** [comment]
Great! Thanks a lot! 👍
