### ISSUE TITLE
Rounded corners bar

### ISSUE THREAD

**Issue by lsnmarcinr** [i-schuetz/SwiftCharts#318]
Why my ViewBar have rounded all corners, even I choose only .topLeft and .topRight? I can't change that. No corners rounded or all corners rounded - nothing else.

`let barViewGenerator = {(chartPointModel: ChartPointLayerModel, layer: ChartPointsViewsLayer, chart: Chart) -> UIView? in
let bottomLeft = layer.modelLocToScreenLoc(x: 0, y: 0)
let barWidth: CGFloat = 30
let settings = ChartBarViewSettings(cornerRadius: 15, roundedCorners: [.topLeft, .topRight])
let (p1, p2): (CGPoint, CGPoint) = {
return (CGPoint(x: chartPointModel.screenLoc.x, y: bottomLeft.y), CGPoint(x: chartPointModel.screenLoc.x, y: chartPointModel.screenLoc.y))
}()
return ChartPointViewBar(p1: p1, p2: p2, width: barWidth, bgColor: UIColor.blue, settings: settings)}`

And preview: 

<img width="986" alt="zrzut ekranu 2017-11-30 o 15 42 22" src="https://user-images.githubusercontent.com/26714814/33436360-1481ec2e-d5e5-11e7-9064-53d3ff7281a1.png">

**Comment by i-schuetz** [comment]
Unfortunately selective rounding of corners works only for stacked bars at the moment, see https://github.com/i-schuetz/SwiftCharts/pull/239

Perhaps you can port the functionality to the plain bars. Otherwise I can give it a look in the coming days, though can't guarantee when.

**Comment by lsnmarcinr** [comment]
True, I created ChartStackedBarsLayer with rounded .topLeft and .topRight corner 👍

**Comment by i-schuetz** [comment]
You can actually always used stacked bars - plain bars having only 1 stack frame, this keeps it also flexible.

**Comment by arthursady** [comment]
If we enable scaleX on the chart, the round corners are lost, is there a work around that issue? or is there a way to set X scroll without changing the scaleX or min and max zoom?
