### ISSUE TITLE
func filler() doesn't seem to serve a purpose. if true, i'm happy to take it out. :)

### ISSUE THREAD

**Issue by scribblecat** [i-schuetz/SwiftCharts#319]
Hi!

This method embedded in `viewDidLoad()` of a few vc's in the example code doesn't get called anywhere in the code source --
`func filler(_ date: Date) -> ChartAxisValueDate`

It's in 
`CandleStickExample`, `CandleStickInteractiveExample`, `CustomUnitsExample`

Is it there for future use? 

If not, I'd be happy to remove it and submit a pull request.

p.s. sorry if that sounds like a lame change. as a framework user combing through the examples to get an idea of how to do what i want to do (which was a date drive x-axis), the filler method just serves as an unnecessary decoy is all.

**Comment by i-schuetz** [comment]
Hi, feel free to remove it, thanks!
