### ISSUE TITLE
It's seem like can't release chart instance completely?

### ISSUE THREAD

**Issue by hopy11** [i-schuetz/SwiftCharts#321]
In my ViewController,I write a method createChart() to create a new chart,below is part of the code:

    class ViewController:UIViewController{
        var chart:Chart?

        func createChart(){
            //Omitted code for init layers ...
            let chart = Chart(
                frame: chartFrame,
                innerFrame: innerFrame,
                settings: chartSettings,
                layers: [
                    xAxisLayer,
                    yAxisLayer,
                    guidelinesLayer,
                    chartPointsLineLayer,
                    chartPointsCircleLayer
                ]
            )
        
            view.addSubview(chart.view)
            chart.zoom(scaleX: 6, scaleY: 1, centerX: 0, centerY: 0)
        
            chartPointsLineLayer.initScreenLines(chart)
            chartPointsCircleLayer.initViews(chart)
            chartPointsCircleLayer.zoom(6, y: 1, centerX: 0, centerY: 0)
       
            chart.delegate = self
            //here set new chart to self.chart
            self.chart = chart
        }
    }

In order to refresh the chart's display in time, I call createChart() in viewWillAppear:

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        //update some variable data for chart display
        updateData()
        //release(remove) chart from view
        if let chart = chart{
            chart.clearView()
            self.chart = nil
        }
        //recreate chart
        enrollChart()
    }

It's mean everytime when user enter the vc,it will first remove chart and then recreate it!

It seem looks good! But actually run the code is bad!  it's seem like chart instance not released completely! because the UI of the vc become very slow after few times,and chart display is not right.

my question is : what is the right way for release chart? Is my way correct?
thanks :)

**Comment by hopy11** [comment]
what I mean : "the UI of the vc become very slow after few times,and chart display is not right." is this:

<img width="375" alt="2017-12-05 10 48 16" src="https://user-images.githubusercontent.com/6326047/33613736-5a273cfa-da10-11e7-998d-2bbf8ea2b31b.png">
<img width="356" alt="2017-12-05 10 48 49" src="https://user-images.githubusercontent.com/6326047/33613737-5a6f0864-da10-11e7-9b59-9536fbca4c86.png">
<img width="330" alt="2017-12-05 10 49 06" src="https://user-images.githubusercontent.com/6326047/33613741-5ad9b1d2-da10-11e7-97a5-1eb192609074.png">

when I quit App and run it again , the chart display correct! (like the 3th picture above)

**Comment by i-schuetz** [comment]
This usually works
```
for view in chart.view.subviews {
    view.removeFromSuperview()
}
initChart() // code to create chart instance
chart.view.setNeedsDisplay() // this may be necessary to trigger a redraw
```
If there's still a problem try profiling, or upload a self containing gist and I'll take a look.

**Comment by hopy11** [comment]
OK，it's worked！thanks！
