### ISSUE TITLE
Podfile spec '~> 0.6.1' is not working

### ISSUE THREAD

**Issue by SergMykhailov** [i-schuetz/SwiftCharts#322]
Hello
I'm trying to integrate your charts library into my project written in Swift 4
I've added podfile spec which was shown in guide:
_**pod 'SwiftCharts', '~> 0.6.1'**_
but seems that it's not working. I get the following error:

[!] Unable to satisfy the following requirements:
- `SwiftCharts (~> 0.6.1)` required by `Podfile`
None of your spec sources contain a spec satisfying the dependency: `SwiftCharts (~> 0.6.1)`.

When I set version of the library to 0.6 like shown below everything goes fine
**_pod 'SwiftCharts', '0.6'_**
but this version of library is not compatible with Swift 4
Could you please verify this issue. Maybe I'm doing something unproperly

Thank you
Serg

**Comment by i-schuetz** [comment]
Execute `pod search SwiftCharts` in the terminal and see if `0.6.1` appears. If not, use `pod repo update` and try again.

**Comment by SergMykhailov** [comment]
pod repo update
helped thank you for help
