### ISSUE TITLE
Line circle layer- circle appearing stretched out 

### ISSUE THREAD

**Issue by zoufishanmehdi** [i-schuetz/SwiftCharts#327]
Hi! As you can see below, I added code to generate circle found in BarsPlusMinusAndLinesExample. However, the circle doesn't appear circular as it should, but instead looks horizontally stretched out. Please refer to the code and screenshots below. 

`let circleViewGenerator = {(chartPointModel: ChartPointLayerModel, layer: ChartPointsLayer, chart: Chart) -> UIView? in
            let color = UIColor(red: 0.7, green: 0.7, blue: 0.7, alpha: 1)
            let screenLoc = CGPoint(x: chartPointModel.screenLoc.x.isNaN ? 50.0 : chartPointModel.screenLoc.x, y: chartPointModel.screenLoc.y)
            let circleView = ChartPointEllipseView(center: screenLoc, diameter: 6)
            circleView.animDuration = 0
            circleView.fillColor = color
            return circleView
        }`
        
        `let lineCirclesLayer = ChartPointsViewsLayer(xAxis: xAxisLayer.axis, yAxis: yAxisLayer.axis, chartPoints: chartPoints, viewGenerator: circleViewGenerator, displayDelay: 0, delayBetweenItems: 0.05)`

<img width="175" alt="screen shot 2018-01-02 at 10 40 53 am" src="https://user-images.githubusercontent.com/12058032/34489466-706b8502-efaa-11e7-9094-04e422be3691.png">
<img width="190" alt="screen shot 2018-01-02 at 10 40 34 am" src="https://user-images.githubusercontent.com/12058032/34489490-8a25d47a-efaa-11e7-943a-8a4b0e059c7c.png">

Any ideas how to fix this? Thank you!

**Comment by i-schuetz** [comment]
Please read https://github.com/i-schuetz/SwiftCharts/wiki/View-hierarchy-and-transforms#chartpointsviewslayer-transform-modes and see examples where the circles are not scaled.
