### ISSUE TITLE
Is there any way to show a Horizontal Stack single Bar?

### ISSUE THREAD

**Issue by Vignesh-Thangamariappan** [i-schuetz/SwiftCharts#328]

**Comment by i-schuetz** [comment]
Yes.

**Comment by Vignesh-Thangamariappan** [comment]
Can you please tell me how will i be able to do that?

**Comment by i-schuetz** [comment]
Please provide a full description of the problem - what did you tried, which specific problems did you encounter?

That said, somebody else happened to ask a similar question recently, which is likely related, see https://github.com/i-schuetz/SwiftCharts/issues/326
