### ISSUE TITLE
Axis problem

### ISSUE THREAD

**Issue by iOSMadDev** [i-schuetz/SwiftCharts#335]
If your data looks something like this:
let array (Sting, Double) = [("first", 0.001), ("second", 0.001), ("third", 0.001)] there will be a problem with axis x (or y depends how you will pass the parameters).

So main thing is that double value is not changing in data array (straight line) and its less then 1

And in method "func generateAxisValuesWithChartPoints" of "struct ChartAxisValuesStaticGenerator" there is a code:

let last = lastPar =~ first ? lastPar + 1 : lastPar

so "+ 1" is a problem for values than less than 1

**Comment by i-schuetz** [comment]
Which problem? Can you be more specific?

**Comment by iOSMadDev** [comment]
Problem with scale.
So my values in array are less the 1. And if they are all equal ( like 0.001) there will be a problem.
Chart will be from 0 to 1 and all of my values will be almost invisible because of wrong scale.

Test data for "Hello world" example:
 let chartPoints: [ChartPoint] = [(0.0001, 0.0001), (0.0001, 0.0001), (0.0001, 0.0001), (0.0001, 0.0001), (0.0001, 0.0001), (0.0001, 0.0001)].map{ChartPoint(x: ChartAxisValueDouble($0.0), y: ChartAxisValueDouble($0.1))}

**Comment by i-schuetz** [comment]
`ChartAxisValuesStaticGenerator.generateAxisValuesWithChartPoints` is just convenience to generate the array and not really needed anymore... I will probably deprecate it soon. Now there are dynamic generators - please checkout the [wiki](https://github.com/i-schuetz/SwiftCharts/wiki/Axes#generators). You of course can also simply pass an array with the desired axis values / write your own logic to generate this array.

**Comment by iOSMadDev** [comment]
thx
