### ISSUE TITLE
Using chart in PageViewController doesn't support swiping

### ISSUE THREAD

**Issue by TDede** [i-schuetz/SwiftCharts#338]
I use the charts in a PageViewController environment to show measurement results. When I want to swipe to change the page, it does not work, as long as I swipe over the view containing the chart. Only when I swipe next to it, I can change the view. Since my graph is nearly covering the complete screen, this makes it complicated for the user. Is this issue known? I haven't found a description of it.

**Comment by i-schuetz** [comment]
Did you disable zooming and panning? Otherwise please upload a small example where I can reproduce it (to your github, please not as zip).

**Comment by TDede** [comment]
Thank you. It works now!
