### ISSUE TITLE
stride(from:through:by:)' is unavailable: call the 'stride(through:by:)' method instead

### ISSUE THREAD

**Issue by mostworld77** [i-schuetz/SwiftCharts#34]
Hello,
im using Xcode 7 Beta 6, now i get the error:
"..../SwiftCharts/Convenience/BarsChart.swift:34:29: 'stride(from:through:by:)' is unavailable: call the 'stride(through:by:)' method instead"

is there a fix in the next time?
thanks

**Comment by i-schuetz** [comment]
Hi,
I'll fix it by the weekend... if you want you also can submit a pull request, if everything works I'll merge it quickly. Here is an example with the new syntax: http://stackoverflow.com/a/24372631/930450

**Comment by i-schuetz** [comment]
Fixed
