### ISSUE TITLE
Build issue in Xcode 10 beta 2 (10L177m)

### ISSUE THREAD

**Issue by pmurphyjam** [i-schuetz/SwiftCharts#358]
SwiftCharts won't build in Xcode 10 beta 2 due String.swift extension method subscript (r:Range<Int>) -> String.
Error lies in 
return String(self[Range(start..<end)])
Range no longer supports start to end values in call.

Great library by the way, using it in my App, need this issue fixed since it prevents it from build in iOS12 using Xcode 10.

**Comment by i-schuetz** [comment]
This was fixed in this pr https://github.com/i-schuetz/SwiftCharts/pull/357
Please use master in the meantime, thanks!
