### ISSUE TITLE
Flatmap deprecated in swift 4

### ISSUE THREAD

**Issue by worchyld** [i-schuetz/SwiftCharts#366]
I get the following warnings in Swift 4, using:

`pod 'SwiftCharts', '~> 0.6.1'`

> 'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value

**Comment by worchyld** [comment]
If an update is made, I'm hoping it will be pushed soon.

**Comment by i-schuetz** [comment]
0.6.2 released!
