### ISSUE TITLE
Swift 4.2 compile error

### ISSUE THREAD

**Issue by DavidLari** [i-schuetz/SwiftCharts#367]
Using Xcode 10 GM Seed, Swift 4.2, file String.swift has a compile error on line 25:

``` 
return String(self[start..<end])
```

Cannot invoke initializer for type 'Range<_>' with an argument list of type '(Range<String.Index>)'

**Comment by fuzunspm** [comment]
same issue here

**Comment by StephenNorris** [comment]
I just built my app against the latest pod with Xcode 10. After I did the Swift 4.2 migration on my project it compiled okay (although there are a lot of warnings about replacing “open let” with public).

**Comment by i-schuetz** [comment]
Yes, the fix is in 0.6.2. Will go through the warnings this week. PRs also welcome.
