### ISSUE TITLE
Does not compile with Swift 4.2

### ISSUE THREAD

**Issue by BergQuester** [i-schuetz/SwiftCharts#370]
# Problem

Pod does not compile in project that uses Swift 4.2. I have tried both release 0.6.2 and the latest master commits and both have issues compiling. See screenshot below for error details.

# Solution

Run Xcode's Swift syntax converter on master.

![image](https://user-images.githubusercontent.com/1323628/45826077-ebbb8080-bcb0-11e8-8ff9-6b2ca028eaaa.png)

**Comment by av8ramit** [comment]
Hitting this same issue.

**Comment by abhilashkhare** [comment]
I'm also facing the same issue - below is the screenshot.

![swiftchartsissue](https://user-images.githubusercontent.com/29790953/45942364-fb7be300-bf96-11e8-95d4-dcc3b8848ffb.png)

**Comment by jethmalani** [comment]
I am getting the same issues. Do you know when you will update to swift 4.2?

**Comment by i-schuetz** [comment]
Please ensure that you updated to 0.6.2. As you can see [here](https://github.com/i-schuetz/SwiftCharts/blob/0.6.2/SwiftCharts/String.swift#L25), `Range` is not being used.

There's a full update (for the warnings) to 4.2 in mater. You can link to master in your podfile. I'll release 0.6.3 with this update soon.
