### ISSUE TITLE
Swift 4.2 compile error

### ISSUE THREAD

**Issue by sparklefly** [i-schuetz/SwiftCharts#376]
![2019-01-08 9 57 29](https://user-images.githubusercontent.com/8312319/50805107-d9cb1f80-132b-11e9-986c-29ae84889418.png)

Don't know why these errors come out, that's odd. Pls help to fix, thanks.

**Comment by iamvijay7** [comment]
Hey facing same issue any solution?

**Comment by venky05** [comment]
Even i am facing same issue

**Comment by i-schuetz** [comment]
The project is compiling and running fine with Xcode 10.1. The declared Swift version is 4.2.

I think you may be using an older Swift version - for example `bringSubviewToFront` is the current correct way to write it, see https://developer.apple.com/documentation/uikit/uiview/1622541-bringsubviewtofront
