### ISSUE TITLE
Xcode 10 errors

### ISSUE THREAD

**Issue by wasatchtechnology** [i-schuetz/SwiftCharts#382]
I'd added SwiftCharts using pods in Xcode 10.1 and get 20 errors.
I've tried  pod 'SwiftCharts', '~> 0.6.3' and  pod 'SwiftCharts', '~> 0.6' but the errors persist.
I have removed the pod, then added it back in but to no avail.
This was an old project and use SwiftCharts. It may have been originally build in Swift 2.3.
 I need to update this. Please advise.

Thanks in advance.
<img width="468" alt="Screen Shot 2019-03-13 at 5 31 06 PM" src="https://user-images.githubusercontent.com/2913617/54319576-00216b80-45b8-11e9-81e1-1a6e797df732.png">

**Comment by i-schuetz** [comment]
See https://github.com/i-schuetz/SwiftCharts/issues/376#issuecomment-462737347

**Comment by wasatchtechnology** [comment]
Thanks for pointing me in that direction. I had changed the Swift version in the project but not the Target.
