### ISSUE TITLE
Some issues in Swift 5 conversion!!

### ISSUE THREAD

**Issue by roozbehg** [i-schuetz/SwiftCharts#383]
it seems hashValue is deprecated in Swift 5. is there any plan for Swift 5 conversion?

**Comment by i-schuetz** [comment]
I'll look into this in a few days. If anyone wants to do it, feel free to submit a PR.

**Comment by roozbehg** [comment]
thank you Ivan!

**Comment by bmalbuck** [comment]
@i-schuetz @roozbehg Take a look at my Pull Request. I implemented hash(into: inout Hasher)

**Comment by bmalbuck** [comment]
I fixed a lot of warnings in addition to Hashable. Also added a new target for a universal fat binary including a build phase script to strip architecture.

**Comment by roozbehg** [comment]
@bmalbuck  thanks a lot Brian !!

**Comment by i-schuetz** [comment]
Released 0.6.4
