### ISSUE TITLE
Update for Xcode 10.2

### ISSUE THREAD

**Issue by chinmaykumardas8** [i-schuetz/SwiftCharts#385]
After updating Xcode to 10.2 I found an error in ChartGroupedBarsLayer.swift line 114. It says "The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions"

**Comment by i-schuetz** [comment]
Will be fixed with https://github.com/i-schuetz/SwiftCharts/pull/384

**Comment by i-schuetz** [comment]
0.6.4 Was released.
