### ISSUE TITLE
Display text next to Bubbles similar to AreasExample.swift

### ISSUE THREAD

**Issue by mac389** [i-schuetz/SwiftCharts#4]
I am trying to have a text box appear next to each bubble in the bubble plot when the user touches that bubble. Similar to the dialog box in AreasExample.swift, I want the dialog box next to the bubble to display a string stored in a field of ChartPointBubble. 

My understanding is that I need to pass a modification of `circleViewGenerator` as the viewGenerator for chartPointsBubbleLayer. I am unsure of how to mesh _AreasExample.swift_ and _BubbleExample.swift_ to achieve this.  _BubbleExample.swift_ has a local version of _BubbleView_.  _BubbleExample.swift_ seems to not need a viewGenerator, which makes me all the more uncertain of how to insert it.

**Comment by mac389** [comment]
I forgot to mention that using circleViewGenerator instead of the closure in bubblesLayer doesn't work. Perhaps my question can be rephrased as how to modify that closure to incorporate circleViewGenerator.

**Comment by i-schuetz** [comment]
The easiest way is to implement touchesEnded in the local BubbleView class, and pass a handler to it, similar to how it is implemented in ChartPointTextCircleView (which is used in the areas example) or HandlingView. Then you can do handling like in circleViewGenerator.

I'll add a generic BubbleView in an upcoming version (with touch handler), which will replace the current BubbleView and ChartPointTextCircleView, and remove this local class.

The circleViewGenerator from areas principally works in the bubbles example, but you probably have a name clash with the local BubbleView class, plus the generated views work with a fixed cornerRadius, which you would have to adjust depending on the bubble's size.

**Comment by mac389** [comment]
I implemented touchesEnded like you suggested. 

Am I correct that  _bubbleViewGenerator_, the analog to _circleViewGenerator_, will call _MyBubbleView_, my rename of the local _BubbleView_ class? How do I pass this to the BubbleLayer?

Perhaps a gist (https://gist.github.com/mac389/0e2fbe441b1eef8538ae) will be more explanatory. Aside from the obvious modifications to _MyBubbleView_ constructor. I think this file illustrates my confusion. 

Thanks for your help in this. 
I hope I get to the point where I can contribute to this project. I think increasing the ability of iOS to make scientific graphs is a worthy endeavour.

**Comment by i-schuetz** [comment]
I created this gist that does what you want: https://gist.github.com/i-schuetz/badf5ac8d8de3bb748f2

You will have to tinker a bit with the info bubbles, right now they are not designed to be used in this type of chart - for example the touch area of the bubble covers the rect including transparent area in the bottom where the arrow is, so if you try to tap a chartpoint in this area it will be absorbed by the info bubble. You may want to try to use a library specialised in info bubbles, for example https://github.com/chrismiles/CMPopTipView. My info bubbles are rather demonstrative purpose... I would have used CMPopTipView but didn't want to introduce external dependencies to the project. I maybe move this to the example project in the future.

Also, the reason that I didn't add touch handling to the bubble example, in the first place, was that the chartpoints can overlay each other (as seen in the example) and it's difficult for the user to tap a specific one. You can of course add special handling for this, like showing an intermediate selection view, etc. 
Maybe your chart will not have overlapping chartpoints, in which case it's ok to add the touch handler like it is now.

**Comment by mac389** [comment]
Thanks :+1:
