### ISSUE TITLE
Lots of errors found when build in xcode7 swift2.0

### ISSUE THREAD

**Issue by Kevin713** [i-schuetz/SwiftCharts#42]
when can you update a new version support swift2

**Comment by i-schuetz** [comment]
I'll do it by the weekend. Sorry for the delay, been busy these days.

**Comment by i-schuetz** [comment]
Wait, not sure what you asked. There's already a swift 2.0 branch. It works in XCode 7 beta 6.

 It has not been tested with the released version of XCode 7. This is what I'm going to do at the weekend.

**Comment by i-schuetz** [comment]
The current swift 2.0 branch works without problems in XCode 7 release version.
