### ISSUE TITLE
Building the project in XCODE 7 with updated SWIFT 2.0 Carthage built framework

### ISSUE THREAD

**Issue by pavlem** [i-schuetz/SwiftCharts#43]
Hi, I tried implementing new swift 2.0 version and I have entirely removed and rebuild the framework (cart file, cart update...), got the framework in the project folder, imported it to XCODE project in the the General part under Linked Framework and libraries, put the input file "$(SRCROOT)/Carthage/Build/iOS/SwiftCharts.framework" under run scripts. 

After I build I always get the error:
**dyld: Library not loaded: @rpath/libswiftSecurity.dylib
  Referenced from: /Users/currentuser/Library/Developer/CoreSimulator/Devices/5D1EFC15-79C5-4A91-9C38-3DF1DD8D7B06/data/Containers/Bundle/Application/DAFD269F-0E16-44D4-A237-E6D30706924A/UBS Funds.app/Frameworks/SwiftCharts.framework/SwiftCharts
  Reason: image not found**

I tried the online solutions without success:
- Restart Xcode, then computer and iPhone
- Go to project build settings and set Embedded Content Contains Swift Code flag to YES
- Go to project build settings and add @executable_path/Frameworks to Runpath Search Paths option

It worked in XCODE 6.4 with swift 1.2, do you have any ideas?

Thanks, 
Pavle

**Comment by i-schuetz** [comment]
You are using the new tag, correct?
```
github "i-schuetz/SwiftCharts" ~> 0.3
```

**Comment by pavlem** [comment]
Yes I am.

**Comment by i-schuetz** [comment]
I could reproduced it. Solved it by adding the framework to embedded binaries.

**Comment by pavlem** [comment]
I just tried it with same result, please see attachment. Do you have any other idea?
<img width="1440" alt="1" src="https://cloud.githubusercontent.com/assets/14887690/10163247/d8167f06-66b1-11e5-9949-f09176e2e26b.png">
<img width="1440" alt="2" src="https://cloud.githubusercontent.com/assets/14887690/10163246/d8169c02-66b1-11e5-8d7b-0e6ba85fbb37.png">

**Comment by i-schuetz** [comment]
Mhh it worked for me. See also [here](http://www.raywenderlich.com/forums/viewtopic.php?t=23238&p=95484)

I also removed the script build phase, but this shouldn't be related.

**Comment by i-schuetz** [comment]
Here again exactly what I did:

rm -rf ~/Library/Caches/org.carthage.CarthageKit/dependencies/
rm -rf ~/Library/Caches/org.carthage.CarthageKit/binaries/
(this fixes possible "Failed to discover shared schemes in project ..." error)

carthage update

Drag framework to embedded binaries

Build

**Comment by pavlem** [comment]
Ok, I managed to fix it and here is what I did. 

1. Removed already built SwiftCharts framework completely (in project settings from project in Linked Framework and libraries in general tab and deleted Run Script completely in Build Phases tab). Also deleted Carthage folder in the project folder 
2. Cleaned the XCODE project and deleted derived data
3. Installed Carthage via Homebrew package manager and SwiftyJSON framework( followed instruction from this tutorial http://www.raywenderlich.com/109330/carthage-tutorial-getting-started ). I added new run script in build phases tab
4. After that compiled without errors, I added SwifttCharts to cart file, updated and added the built framework ONLY to the Linked Frameworks and Libraries in General tab (not in embedded binaries). Also I added **$(SRCROOT)/Carthage/Build/iOS/SwiftCharts.framework input file in Build Phases tab**
5. After that I finally built the app successfully without errors. 

Thanks, you can close this issue.

**Comment by i-schuetz** [comment]
Great!
