### ISSUE TITLE
Can't build example

### ISSUE THREAD

**Issue by skywinder** [i-schuetz/SwiftCharts#44]
![screen shot 2015-10-06 at 09 22 49](https://cloud.githubusercontent.com/assets/3356474/10301512/d68b43ce-6c0b-11e5-8e3a-9bab3ef18192.png)

**Comment by i-schuetz** [comment]
Can you please provide your Xcode version and the branch and version of SwiftCharts you are using?

**Comment by skywinder** [comment]
Just updated from Xcode6 to Xcode7 and error is gone, sorry, I didn't find information which swift version in master branch.

**Comment by i-schuetz** [comment]
Ok, I edited the readme to make this a bit clearer, thanks for the feedback!
