### ISSUE TITLE
Charts do not rotate properly

### ISSUE THREAD

**Issue by RickStreet** [i-schuetz/SwiftCharts#45]
Great Library!  The examples look great.  When I rotate, the landscape doesn't fill the frame.  When I rotate back to prostrate, part of the graph is cut off.  This happens with and without using auto layout.

Here's the ViewController I'm using:

//  Copyright © 2015 us.rickstreet. All rights reserved.
//

import UIKit
import SwiftCharts

class ViewController: UIViewController {
    
    private var chart: Chart? // arc
    
    @IBOutlet weak var chartView: ChartBaseView!
    
    private var didLayout: Bool = false

    
   override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
            NSNotificationCenter.defaultCenter().addObserver(self, selector: "rotated", name: UIDeviceOrientationDidChangeNotification, object: nil)
        }

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        if !self.didLayout {
            self.didLayout = true
            self.initChart()
        }
    }
    
    private func initChart() {
        
        for index in 5.stride(through: 1, by: -1) {
            print(index)
        }
        
        // map model data to chart points
        let chartPoints: [ChartPoint] = [(2, 2), (4, 4), (6, 6), (8, 10), (12, 14)].map{ChartPoint(x: ChartAxisValueInt($0.0), y: ChartAxisValueInt($0.1))}
        
        let labelSettings = ChartLabelSettings(font: ExamplesDefaults.labelFont)
        
        // define x and y axis values (quick-demo way, see other examples for generation based on chartpoints)
        let xValues = 0.stride(through: 16, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}
        
        let yValues = 0.stride(through: 16, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}
        
        // create axis models with axis values and axis title
        let xModel = ChartAxisModel(axisValues: xValues, axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings))
        let yModel = ChartAxisModel(axisValues: yValues, axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings.defaultVertical()))
        
        let chartFrame = self.chartView.frame
        
        // generate axes layers and calculate chart inner frame, based on the axis models
        let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: ExamplesDefaults.chartSettings, chartFrame: chartFrame, xModel: xModel, yModel: yModel)
        let (xAxis, yAxis, innerFrame) = (coordsSpace.xAxis, coordsSpace.yAxis, coordsSpace.chartInnerFrame)
        
        // create layer with guidelines
        let guidelinesLayerSettings = ChartGuideLinesDottedLayerSettings(linesColor: UIColor.blackColor(), linesWidth: ExamplesDefaults.guidelinesWidth)
        let guidelinesLayer = ChartGuideLinesDottedLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, settings: guidelinesLayerSettings)
        
        // view generator - this is a function that creates a view for each chartpoint
        let viewGenerator = {(chartPointModel: ChartPointLayerModel, layer: ChartPointsViewsLayer, chart: Chart) -> UIView? in
            let viewSize: CGFloat = Env.iPad ? 30 : 20
            let center = chartPointModel.screenLoc
            let label = UILabel(frame: CGRectMake(center.x - viewSize / 2, center.y - viewSize / 2, viewSize, viewSize))
            label.backgroundColor = UIColor.greenColor()
            label.textAlignment = NSTextAlignment.Center
            label.text = "\(chartPointModel.chartPoint.y.text)"
            label.font = ExamplesDefaults.labelFont
            return label
        }
        
        // create layer that uses viewGenerator to display chartpoints
        let chartPointsLayer = ChartPointsViewsLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, chartPoints: chartPoints, viewGenerator: viewGenerator)
        
        // create chart instance with frame and layers
        let chart = Chart(
            view: self.chartView!,
            layers: [
                coordsSpace.xAxis,
                coordsSpace.yAxis,
                guidelinesLayer,
                chartPointsLayer
            ]
        )
        self.chart = chart
    }
    
    func rotated() {
        for view in self.chartView.subviews {
            view.removeFromSuperview()
        }
        self.initChart()
    }

}

Thanks,
Rick

**Comment by i-schuetz** [comment]
Hi Rick,
I just tested it and it works fine. Have you debugged it - is it calling rotated, etc?

**Comment by RickStreet** [comment]
It is calling rotated...   it works on the first rotation, buy when you rotate back, the graph gets cut off.

**Comment by i-schuetz** [comment]
hmm. I could reproduce a cut problem but not related with rotation. The issue in this case it's the way the example view controller's view is added as a child to details view controller. For it to work correctly with autolayout you have to give the example view controller's view the correct frame, so in DetailViewController:
```
    private func showExampleController(controller: UIViewController) {
        if let currentExampleController = self.currentExampleController {
            currentExampleController.removeFromParentViewController()
            currentExampleController.view.removeFromSuperview()
        }
        self.addChildViewController(controller)
        controller.view.frame = self.view.frame // add this line
        self.view.addSubview(controller.view)

        self.currentExampleController = controller
    }
```
You can also use autolayout for this. Outside of the example project you will likely not have this problem unless you also have a nested view controller or insufficient constraints.
