### ISSUE TITLE
How to disable animation on basic bar chart example

### ISSUE THREAD

**Issue by meyitangp** [i-schuetz/SwiftCharts#51]
Hi, thanks for making swiftcharts: it's awesome..I'm a beginner SWIFT 2 programmer and am trying out the basic chart example. How do I prevent the animation of bars every time the chart loads?

**Comment by i-schuetz** [comment]
Hi,

thanks! You can just pass 0 as duration to the layer:

´´´swift
ChartBarsLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, bars: bars, horizontal: false, barWidth: 25, animDuration: 0)
´´´

**Comment by meyitangp** [comment]
Great, thank you. It worked a few hours ago, but now Xcode displays the following error: 
Module file was created by an older version of the compiler; rebuild 'SwiftCharts' and try again: /Users/..../SwiftCharts.framework/Modules/SwiftCharts.swiftmodule/x86_64.swiftmodule

I guess my computer must have run an update and I now have to wait for you to recompile Swiftcharts? Thanks ahead for your help.

**Comment by i-schuetz** [comment]
No problem! I think you have to clean (product menu -> clean) and rebuild to fix this.

**Comment by meyitangp** [comment]
I'm using Xcode 7.1(7B91b) and the swift 2.0 branch of Swiftcharts installed through carthage 0.9.3. Cleaning and rebuilding does fix this error either.

**Comment by i-schuetz** [comment]
Hmm carthage builds the project and you say it was working before. The error must be in your side. Have you tried "clean build folder" (this is different to only clean)? see e.g. here http://stackoverflow.com/questions/29632044/sqlite-swift-module-file-was-created-by-an-older-version-of-compiler

**Comment by meyitangp** [comment]
Boy apple sure knows how to make the simplest fixes monumental to repair. I come from visual studio and this whole apple ecosystem is new to me. Holding down the "Option" key while clicking Product-->Clean build folder..worked. Note after doing this, you must click on "Clean" then "Build" again to make the error go away. Thank you.
