### ISSUE TITLE
numeric y axis and literal x axis for line chart

### ISSUE THREAD

**Issue by ZitingWei** [i-schuetz/SwiftCharts#54]
Is it possible to set the y axes labels all double/int values but the x axes labels all string values in LineChart?

Assume that I have arrays of values like:
line1: [1.1, 2.5, 1.3, 8.4, 2.2]
line2: [4.8, 5.1, 0.6, 7.2, 9.1]
axisX: [A,B,C,D,E]

and I'd like my chart looks this way: (sorry for the ugly presenting)

![chart](https://cloud.githubusercontent.com/assets/14345420/10877162/9661185e-817e-11e5-93fb-3ac8c42f6493.png)

The chartPoints for LineChart seems need to be in (x,y) format, which is a little trivial for combining two elements in different values array into one pair (e.g. (line1[0], axisX[0]) ), and I see no text parameter in the chartPoints class.

Do I have to use Chart class for more flexible layer settings to accomplish this or is there a simpler way within the LineChart?

Thanks for supporting!

**Comment by i-schuetz** [comment]
Yes, you have to use `Chart` directly. `LineChart` is just a convenience wrapper and currently supports only supports numeric values.

**Comment by ZitingWei** [comment]
Starting from the HelloWorld example, the `ChartPointCircleView` doesn't seem to exist. Only if I remove it from chart parameters like:

`let chart = Chart(
            frame: chartFrame,
            layers: [
                xAxis,
                yAxis,
                guidelinesLayer,
                chartPointsLineLayer
                //chartPointsCircleLayer
            ]
        )`

I get a chart which shows only one line without axis title, axis label, or guidelines. 
Could you help figuring it out?

**Comment by i-schuetz** [comment]
The code in the readme is a bit outdated, just run the example project... you find similar (updated) code in HelloWorld example. If you need specifically circles this is now [ChartPointEllipseView](https://github.com/i-schuetz/SwiftCharts/blob/bd1d5b3f63f7c524004604708ccad9bcd84dd693/SwiftCharts/Views/ChartPointEllipseView.swift), which you find also in other examples.

**Comment by ZitingWei** [comment]
I did try HelloWorld, NotNumeric, and CustomUnit example, it was confusing that non of them (all Chart class )were showing axes or guidelines but only one main line was drawn. What could be the possible causing?

**Comment by i-schuetz** [comment]
What exactly did you try? See e.g. [here](https://github.com/i-schuetz/SwiftCharts/issues/30) somebody also had this problem with axes and grid.

**Comment by ZitingWei** [comment]
Did check your link, I though it's not about the auto scaling...
Does the code above work on your IDE? (working with storyboard)

**Comment by i-schuetz** [comment]
Ah, now there's code, that's better :) You have to store a reference to the chart in an instance variable (this is why there's an arc comment next to the instance variable in all the examples). Otherwise it's deallocated before the core graphics things are rendered.

**Comment by ZitingWei** [comment]
I should have noticed that! That really helps! :+1:
