### ISSUE TITLE
Constructing an object of class type 'T' with a metatype value must use a 'required' initializer

### ISSUE THREAD

**Issue by ban9ban3** [i-schuetz/SwiftCharts#55]
I have this error after i update to xcode 7.1
Help me pls.

**Comment by ban9ban3** [comment]
This is error in file ChartPointsTrackerLayer.swift line 217

let chartPoint = T(x: x, y: y)

i change it to 

let chartPoint = ChartPoint(x: x, y: y)

the error was gone, but i'm not sure about all, is it working correct?

**Comment by i-schuetz** [comment]
The reason of this T is to create an instance of the concrete chart point class being used, so `text` is called on this class. It may be that you have a chart point subclass in which you override `text` to show something different than the default (the default is quite flexible though, as it forwards to the concrete axes implementations...).

In most cases using only `ChartPoint` should be fine. But it would be better to have a `chartPoint.copy(xScalar, yScalar)`, which copies internally the axes and returns the correct subclass. It would be better than `T` also, as the initialiser can have values other than x and y Axis. I remember I tried this at the beginning (swift 1.2) but had some issues, maybe it's possible now.

So yes, you should be able to change it locally to ChartPoint without problems. In case you are asking to submit a pull request it would have to be a better solution like `copy` approach above.

**Comment by ban9ban3** [comment]
Thanks @i-schuetz
