### ISSUE TITLE
plotting live data 50 times a second?

### ISSUE THREAD

**Issue by Raikete** [i-schuetz/SwiftCharts#56]
Hi, first of all thanks for this fine piece of Software.

Would it be easy to plot live data that changes something like 50 times a second and gives the data in an array of doubles?

We are looking for a performant solution to present data in a live situation.

Thanks and regards, Rainer from Germany :-)

**Comment by i-schuetz** [comment]
Hi Rainer,

thanks! Unfortunately the library is not optimised for live data. May change in the future, but it's not planned yet. See also https://github.com/i-schuetz/SwiftCharts/issues/21.
