### ISSUE TITLE
Cubic lines and high slope

### ISSUE THREAD

**Issue by kayoslab** [i-schuetz/SwiftCharts#57]
Using cubic lines and Data with a high slope after period of axial values causes a short decrease of the functions Graph. The following data example should not result in values below 0.0 :

data = [(name: "", quantity: 0.0), (name: "12:00", quantity: 0.0), (name: "", quantity: 0.0),  (name: "", quantity: 60.0),  (name: "", quantity: 57.0),  (name: "", quantity: 50.0),  (name: "", quantity: 150.0), (name: "18:00", quantity: 135.0),  (name: "", quantity: 125.0), (name: "", quantity: 120.0), (name: "", quantity: 110.0), (name: "", quantity: 210.0),  (name: "", quantity: 180.0), (name: "00:00", quantity: 165.0), (name: "", quantity: 142.0), (name: "", quantity: 120.0), (name: "", quantity: 100.0), (name: "", quantity: 80.0), (name: "", quantity: 75.0), (name: "06:00", quantity: 65.0), (name: "", quantity: 59.0), (name: "", quantity: 57.0), (name: "", quantity: 55.0), (name: "", quantity: 54.0)]

![example-graph](https://cloud.githubusercontent.com/assets/7895569/10968979/8c15a6d2-83c5-11e5-8e52-37d8260f5e44.png)

**Comment by i-schuetz** [comment]
The current implementation of cubic lines has to be improved. In the meantime, you can pass a generator to the line layer with a better interpolation algorithm. See issue https://github.com/i-schuetz/SwiftCharts/issues/47 (last comments) for how to do this (there's also a link to a library that can be used for the algorithm). Feel free to ask if you need more help doing this.

**Comment by kayoslab** [comment]
Thanks for the hint, I modified it with the catmullrom extension by andrelind[/swift-catmullrom](https://github.com/andrelind/swift-catmullrom). It looks slightly better now :)

**Comment by i-schuetz** [comment]
Ok, I hope the "slightly better" was good? If not as I said the algorithm from in https://github.com/i-schuetz/SwiftCharts/issues/47 generates a decent curve.
