### ISSUE TITLE
Zooming scatter plot

### ISSUE THREAD

**Issue by pprraasshhaanntthh** [i-schuetz/SwiftCharts#58]
Zooming the scatter plot is available ???

**Comment by i-schuetz** [comment]
There's no built in zooming functionality. You can of course achieve a similar effect re-creating the chart for different zoom levels, which may be enough depending on your requirements.

**Comment by pprraasshhaanntthh** [comment]
How can I achieve this ? Do we have any sample code ?

**Comment by i-schuetz** [comment]
You would need to implement a slider (or whatever you use to select a zoom level) and re-generate the chart on zoom change, that is scale the x/y values accordingly and create a new chart with these values that replaces the old one. I think this works only with steps - if you need a continuos update the processing to reinitialise the chart probably will cause stuttering.

**Comment by pprraasshhaanntthh** [comment]
Will the zoom feature will available in future enhancements??

**Comment by i-schuetz** [comment]
Maybe, but there are no plans for this yet.
