### ISSUE TITLE
Linking Tap and LongPress to Bubble View

### ISSUE THREAD

**Issue by mac389** [i-schuetz/SwiftCharts#6]
I would like to link two touch events to each point in the scatter plot as follows:

- Tap : Display popup box with information (**have this**)
- Long Press: Switch to Detail page.  (**want this in addition**)

I am unsure how to integrate this with my extension of the Bubble Chart (gist --> https://gist.github.com/0a5191ece2b870b33658.git). 

The commented code, excluding that in the header, shows my attempts to create a response to a long gesture by the user. If I put `performSegueWithIdentifier` in `bubblesLayer`, then the segue happens when the bubble layer is rendered.  Putting `performSegueWithIdentifier` in the inner code block of `bubblesLayer` that creates `infoView` leads to a runtime error.

**Comment by i-schuetz** [comment]
You have to set the gesture recognizer programmatically, [here](http://www.veasoftware.com/tutorials/2015/1/8/long-press-gesture-recognizer-in-swift-xcode-6-ios-8-tutorial) for example you can see how to do it. IBAction doesn't work in this case because the views are generated programmatically, not in storyboard.

About the error, could you post the message? What I see at first glance is 1. you have to declare self in the touch handler as weak, like this: 
```swift
bubbleView.touchHandler = {[weak self] view in (...)
```
Then, because it's a weak variable, treat it as an optional `self?.performSegueWithIdentifier`.

Otherwise you would get there a memory leak. This should not be causing the crash though.

Another issue I see is that you are assigning the chartPoint to a local variable, you probably want to use your instance variable `chartPointDetail` instead.

**Comment by mac389** [comment]
My scatter plot now recognizes two touches. The scatter plot displays a dialog box when the user taps. It switches to a detail view when the user taps and holds if the user holds for at least one second. 

I used `chartPointDetail`. Thanks for pointing that out. 

I avoided the crash by moving the function that handles `UILongPressGesture` outside `touchHandler`. It looks like the crash happened because putting the function to handle tap and holds inside the function to handle taps led to calls to the function to handle tap and holds without the state of `UILongPressGesture` being set.

**Comment by mac389** [comment]
Why does this code fail to detect the currently pressed button during a tap and hold gesture? (Gist: https://gist.github.com/0a5191ece2b870b33658.git)

It always chooses the last member of `ChartPointBubble`. I do not know how to update `selectedIndex`, assuming this approach is the best way to handle two touch events. I believe my error is that `bubblesLayer`.

**Comment by mac389** [comment]
//
//  MasterViewController.swift
//  beta
//
//  Created by Michael Chary on 5/25/15.
//  Copyright (c) 2015 Michael Chary. All rights reserved.
//

import UIKit
import AudioToolbox

private enum Shape {
    case NYU, Sinai, Rockefeller
}


class EcosystemMasterViewController: UIViewController, UIScrollViewDelegate {
    
    var objects = [AnyObject]()
    var chartPoints = [ChartPointBubble]()
    var gesture: UILongPressGestureRecognizer?
    var UniColors = ["nyu": CGFloat(0.5), "sinai":CGFloat(0.2),"rockefeller":CGFloat(0.7)]
    private var chart: Chart?
    private var chartPointDetail:ChartPointBubble?
    var selectedIndex:Int?

    
    private let colorBarHeight: CGFloat = 50
    private let useViewsLayer = true
    
    override func awakeFromNib() {
        super.awakeFromNib()
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.navigationItem.leftBarButtonItem = self.editButtonItem()
        self.gesture =  UILongPressGestureRecognizer(target: self, action: "longPressed:")
        self.gesture!.minimumPressDuration = 1.0
        self.view.addGestureRecognizer(self.gesture!)
        // Do any additional setup after loading the view, typically from a nib.
        
        let frame = ExamplesDefaults.chartFrame(self.view.bounds)
        let chartFrame = CGRectMake(frame.origin.x, frame.origin.y, frame.size.width, frame.size.height - colorBarHeight)
        let labelSettings = ChartLabelSettings(font: ExamplesDefaults.labelFont)
        
        let path = NSBundle.mainBundle().pathForResource("data", ofType: "json")
        let data = NSData(contentsOfMappedFile: path!)
        let json = JSON(data: data!, options: NSJSONReadingOptions.AllowFragments, error: nil)
        let scrollViewFrame = ExamplesDefaults.chartFrame(self.view.bounds)
        
        let colorBar = ColorBar(frame: CGRectMake(0, chartFrame.origin.y + chartFrame.size.height, self.view.frame.size.width, self.colorBarHeight), c1: UIColor.redColor(), c2: UIColor.greenColor())
        
        func toColor(institution: String) -> UIColor {
            return colorBar.colorForPercentage(UniColors[institution.lowercaseString]!).colorWithAlphaComponent(0.6)
        }
        
        for (index: String, object: JSON) in json {
            let pointBubble = ChartPointBubble(
                x: ChartAxisValueFloat(CGFloat(object["x"].floatValue),
                    labelSettings:labelSettings),
                y:ChartAxisValueFloat(CGFloat(object["y"].floatValue)),
                diameterScalar: CGFloat(object["r"].floatValue),
                description: object["description"],
                bgColor:toColor(object["description"]["institution"].stringValue))
            
            self.chartPoints.append(pointBubble)
        }
        
        let xValues = Array(stride(from: -0.6, through: 1.2, by: 0.1)).map {ChartAxisValueFloat($0, labelSettings: labelSettings)}
        let yValues = Array(stride(from: -0.6, through: 1.2, by: 0.1)).map {ChartAxisValueFloat($0, labelSettings: labelSettings)}
        
        let xModel = ChartAxisModel(axisValues: xValues, axisTitleLabel: ChartAxisLabel(text: "Semantic Dimension 1", settings: labelSettings))
        let yModel = ChartAxisModel(axisValues: yValues, axisTitleLabel: ChartAxisLabel(text: "Semantic Dimension 2", settings: labelSettings))
        
        let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: ExamplesDefaults.chartSettings, chartFrame: chartFrame, xModel: xModel, yModel: yModel)
       
        let (xAxis, yAxis, innerFrame) = (coordsSpace.xAxis, coordsSpace.yAxis, coordsSpace.chartInnerFrame)
        
        let lineModel = ChartLineModel(chartPoints: chartPoints, lineColor: UIColor.redColor(), animDuration: 0.5, animDelay: 0)
        
        let bubbleLayer = self.bubblesLayer(xAxis: xAxis, yAxis: yAxis, chartInnerFrame: innerFrame, chartPoints: chartPoints)
        
        let guidelinesLayerSettings = ChartGuideLinesDottedLayerSettings(linesColor: UIColor.blackColor(), linesWidth: ExamplesDefaults.guidelinesWidth)
        let guidelinesLayer = ChartGuideLinesDottedLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, settings: guidelinesLayerSettings)
        
        let guidelinesHighlightLayerSettings = ChartGuideLinesDottedLayerSettings(linesColor: UIColor.redColor(), linesWidth: 1, dotWidth: 4, dotSpacing: 4)
        let guidelinesHighlightLayer = ChartGuideLinesForValuesDottedLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, settings: guidelinesHighlightLayerSettings, axisValuesX: [ChartAxisValueFloat(0)], axisValuesY: [ChartAxisValueFloat(0)])
        
        let scrollView = UIScrollView(frame: scrollViewFrame)
        scrollView.contentSize = CGSizeMake(chartFrame.size.width, scrollViewFrame.size.height)
        
        let chart = Chart(
            frame: chartFrame,
            layers: [
                xAxis,
                yAxis,
                guidelinesLayer,
                guidelinesHighlightLayer,
                bubbleLayer
            ]
        )
        
        self.view.addSubview(chart.view)
        self.chart = chart
        
    }
    
    //MARK: -- Touch handling
    func longPressed(longPress: UIGestureRecognizer){
        if (longPress.state == UIGestureRecognizerState.Ended)
        {
            AudioServicesPlayAlertSound(SystemSoundID(kSystemSoundID_Vibrate))
            self.performSegueWithIdentifier("showDetail", sender: self.chartPoints[self.selectedIndex!])

        }
    }
    
    private func bubblesLayer(#xAxis: ChartAxisLayer, yAxis: ChartAxisLayer, chartInnerFrame: CGRect, chartPoints: [ChartPointBubble]) -> ChartLayer {
        
        let maxBubbleDiameter: CGFloat = 30, minBubbleDiameter: CGFloat = 2
        
        if self.useViewsLayer == true {
            
            
            let (minDiameterScalar: CGFloat, maxDiameterScalar: CGFloat) = chartPoints.reduce((min: CGFloat(0), max: CGFloat(0))) {tuple, chartPoint in
                (min: min(tuple.min, chartPoint.diameterScalar), max: max(tuple.max, chartPoint.diameterScalar))
            }
            let diameterFactor = (maxBubbleDiameter - minBubbleDiameter) / (maxDiameterScalar - minDiameterScalar)
            
            
            var popups: [UIView] = []
            
            return ChartPointsViewsLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: chartInnerFrame, chartPoints: chartPoints, viewGenerator: {[weak self] (chartPointModel, layer, chart) -> UIView? in
                
                let (chartPoint, screenLoc) = (chartPointModel.chartPoint, chartPointModel.screenLoc)
                self!.chartPointDetail = self?.chartPoints[chartPointModel.index]
                let diameter = chartPointModel.chartPoint.diameterScalar * diameterFactor
                
                let rect = CGRectMake(chartPointModel.screenLoc.x - diameter / 2, chartPointModel.screenLoc.y - diameter / 2, diameter, diameter)
                let bubbleView = MyBubbleView(frame: rect, fillColor: chartPointModel.chartPoint.bgColor, borderColor: UIColor.blackColor().colorWithAlphaComponent(0.6), animDelay: 0.1*Float(chartPointModel.index) * 0.2, animDuration: 1.2)
                
                bubbleView.touchHandler = {[weak self] view in
                    
                    for p in popups {p.removeFromSuperview()}
                    
                    let w: CGFloat = Env.iPad ? 250 : 150
                    let h: CGFloat = Env.iPad ? 100 : 80
                    
                    let x: CGFloat = {
                        let attempt = screenLoc.x - (w/2)
                        let leftBound: CGFloat = chart.bounds.origin.x
                        let rightBound = chart.bounds.size.width - 5
                        if attempt < leftBound {
                            return view.frame.origin.x
                        } else if attempt + w > rightBound {
                            return rightBound - w
                        }
                        return attempt
                        }()
                    
                    let frame = CGRectMake(x, screenLoc.y - (h + (Env.iPad ? 30 : 12)), w, h)
                    
                    let bubbleView = BubbleView(frame: frame, arrowWidth: Env.iPad ? 40 : 28, arrowHeight: Env.iPad ? 20 : 14, bgColor: UIColor.blackColor(), arrowX: screenLoc.x - x)
                    chart.addSubview(bubbleView)
                    
                    bubbleView.transform = CGAffineTransformConcat(CGAffineTransformMakeScale(0, 0), CGAffineTransformMakeTranslation(0, 100))
                    let infoView = UILabel(frame: CGRectMake(0, 10, w, h - 20))
                    infoView.textColor = UIColor.whiteColor()
                    infoView.backgroundColor = UIColor.blackColor()
                    infoView.text = chartPoint.description["name"].stringValue
                    infoView.font = ExamplesDefaults.fontWithSize(Env.iPad ? 14 : 12)
                    infoView.textAlignment = NSTextAlignment.Center
                    
                    bubbleView.addSubview(infoView)
                    popups.append(bubbleView)
                    
                    UIView.animateWithDuration(0.2, delay: 0, options: UIViewAnimationOptions.allZeros, animations: {
                        bubbleView.transform = CGAffineTransformIdentity
                        }, completion: {finished in})
                    
                    
                }
                return bubbleView
                
            })
            
        } else {
            return ChartPointsBubbleLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: chartInnerFrame, chartPoints: chartPoints)
        }
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    // MARK: - Segues
    //TODO Include vibrate on selection
    override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?) {
        if segue.identifier == "showDetail" {
            if let destination = segue.destinationViewController as? DetailViewController
            {
                self.navigationItem.title = "Ecosystem"
                let payload = self.chartPoints[self.selectedIndex!].description
                let theName = payload["name"].stringValue
                let theInstitution = payload["institution"].stringValue
                let technologyDescription  = payload["keywords"].count == 0 ? "None" : ", ".join(payload["keywords"].arrayValue.map{(var item) -> String in return item.stringValue})
                destination.detailItem = "Name: \(theName) \n\n Institution: \(theInstitution) \n\n Areas: \(technologyDescription)"
            }
        }
    }
    
}

class MyBubbleView: UIView {
    
    let fillColor: UIColor
    let borderColor: UIColor
    let borderWidth: CGFloat
    let animDelay: Float
    let animDuration: Float
    var touchHandler: ((MyBubbleView) -> ())?
    
    init(frame: CGRect, fillColor: UIColor, borderColor: UIColor, borderWidth: CGFloat = 1, animDelay: Float, animDuration: Float) {
        self.fillColor = fillColor
        self.borderColor = borderColor
        self.borderWidth = borderWidth
        self.animDelay = animDelay
        self.animDuration = animDuration
        
        super.init(frame: CGRectInset(frame, -borderWidth, -borderWidth))
        
        self.backgroundColor = UIColor.clearColor()
    }
    
    required init(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override func drawRect(rect: CGRect) {
        let context = UIGraphicsGetCurrentContext()
        
        CGContextSetLineWidth(context, self.borderWidth)
        CGContextSetStrokeColorWithColor(context, self.borderColor.CGColor)
        CGContextSetFillColorWithColor(context, self.fillColor.CGColor)
        let circleRect = (CGRectMake(self.borderWidth, self.borderWidth, self.frame.size.width - (self.borderWidth * 2), self.frame.size.height - (self.borderWidth * 2)))
        CGContextFillEllipseInRect(context, circleRect)
        CGContextStrokeEllipseInRect(context, circleRect)
    }
    
    override func didMoveToSuperview() {
        self.transform = CGAffineTransformMakeScale(0.1, 0.1)
        self.alpha = 0
        
        UIView.animateWithDuration(NSTimeInterval(self.animDuration), delay: NSTimeInterval(self.animDelay), usingSpringWithDamping: 0.4, initialSpringVelocity: 0.5, options: UIViewAnimationOptions.allZeros, animations: { () -> Void in
            self.transform = CGAffineTransformMakeScale(1, 1)
            self.alpha = 1
            }, completion: nil)
    }
    
    override func touchesEnded(touches: Set<NSObject>, withEvent event: UIEvent) {
        self.touchHandler?(self)
    }
}
class ColorBar: UIView {
    
    let dividers: [CGFloat]
    
    let gradientImg: UIImage
    
    lazy var imgData: UnsafePointer<UInt8> = {
        let provider = CGImageGetDataProvider(self.gradientImg.CGImage)
        let pixelData = CGDataProviderCopyData(provider)
        return CFDataGetBytePtr(pixelData)
        }()
    
    init(frame: CGRect, c1: UIColor, c2: UIColor) {
        
        var gradient: CAGradientLayer = CAGradientLayer()
        gradient.frame = CGRectMake(0, 0, frame.width, 30)
        gradient.colors = [UIColor.blueColor().CGColor, UIColor.cyanColor().CGColor, UIColor.yellowColor().CGColor, UIColor.redColor().CGColor]
        gradient.startPoint = CGPointMake(0, 0.5)
        gradient.endPoint = CGPointMake(1.0, 0.5)
        
        
        let imgHeight = 1
        let imgWidth = Int(gradient.bounds.size.width)
        
        let bitmapBytesPerRow = imgWidth * 4
        let bitmapByteCount = bitmapBytesPerRow * imgHeight
        
        let colorSpace:CGColorSpace = CGColorSpaceCreateDeviceRGB()
        let bitmapInfo = CGBitmapInfo(CGImageAlphaInfo.PremultipliedLast.rawValue)
        
        let context = CGBitmapContextCreate (nil,
            imgWidth,
            imgHeight,
            8,
            bitmapBytesPerRow,
            colorSpace,
            bitmapInfo)
        
        UIGraphicsBeginImageContext(gradient.bounds.size)
        gradient.renderInContext(context)
        let gradientImg = UIImage(CGImage: CGBitmapContextCreateImage(context))!
        
        UIGraphicsEndImageContext()
        self.gradientImg = gradientImg
        
        let segmentSize = gradient.frame.size.width / 6
        self.dividers = Array(stride(from: segmentSize, through: gradient.frame.size.width, by: segmentSize))
        
        super.init(frame: frame)
        
        self.layer.insertSublayer(gradient, atIndex: 0)
        
        let numberFormatter = NSNumberFormatter()
        numberFormatter.maximumFractionDigits = 2
        
        for x in stride(from: segmentSize, through: gradient.frame.size.width - 1, by: segmentSize) {
            
            let dividerW: CGFloat = 1
            let divider = UIView(frame: CGRectMake(x - dividerW / 2, 25, dividerW, 5))
            divider.backgroundColor = UIColor.blackColor()
            self.addSubview(divider)
            
            let text = "\(numberFormatter.stringFromNumber(x / gradient.frame.size.width)!)"
            let labelWidth = ChartUtils.textSize(text, font: ExamplesDefaults.labelFont).width
            let label = UILabel()
            label.center = CGPointMake(x - labelWidth / 2, 30)
            label.font = ExamplesDefaults.labelFont
            label.text = text
            label.sizeToFit()
            
            self.addSubview(label)
        }
    }
    
    func colorForPercentage(percentage: CGFloat) -> UIColor {
        
        let data = self.imgData
        
        let xNotRounded = self.gradientImg.size.width * percentage
        let x = 4 * (floor(abs(xNotRounded / 4)))
        let pixelIndex = Int(x * 4)
        
        let color = UIColor(
            red: CGFloat(data[pixelIndex + 0]) / 255.0,
            green: CGFloat(data[pixelIndex + 1]) / 255.0,
            blue: CGFloat(data[pixelIndex + 2]) / 255.0,
            alpha: CGFloat(data[pixelIndex + 3]) / 255.0
        )
        return color
    }
    
    required init(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
}

**Comment by i-schuetz** [comment]
1. I would add the long touch recognizer to the bubbles. You can do this in the MyBubbleView initializer, and add a new handler to this class analogous to touchHandler. Then, in your longPressed, which would be now in MyBubbleView, call your new handler.

2. In the long touch handler closure, which you can pass now to MyBubbleView thanks to 1. you have access to the index of the touched point, and can set your selectedIndex variable.

**Comment by mac389** [comment]
XCode gives me an error when I try to move `longPressed` into `MyBubbleView` that `performSegueWithIdentifier` is an unknown method. I think this is because `MyBubbleView` inherits from `UIView` rather than `UIViewController`?  

How can I address this? Changing `MyBubbleView` to inherit from `UIViewController` creates many problems, for example the `init` method becomes out of place. Along the same lines, what do I do with `prepareForSegue`? My understanding is I can't move it to `MyBubbleView` because `UIView` doesn't have a `prepareForSegue` function. 

Perhaps in `MyBubbleView`, `longPressed` should look like
      
       var longPressHandler: ((MyBubbleView) -> ())?
       var gesture: UILongPressGestureRecognizer?
      var package: AnyObject?
       ...
        func longPressed(longPress: UIGestureRecognizer){
             if (longPress.state == UIGestureRecognizerState.Ended)
             {
                  longPressHandler{ something here}
                 AudioServicesPlayAlertSound(SystemSoundID(kSystemSoundID_Vibrate))
                 //self.performSegueWithIdentifier("showDetail", sender: self.chartPoints[self.selectedIndex!])
                 
             }
         }

I assume the closure in `EcosystemMasterViewController` (the main class of that file) should look like:

     bubbleView.longPressHandler { [weak self] view in 

             bubbleView.add(gesture!)
             self.package = self.ChartPoints[self.chartPointsModel.charIndex]
              
     }

I apologize for the extended question. I am still learning both Swift and SwiftCharts.

**Comment by i-schuetz** [comment]
You don't have to put any code in longPressed except calling the handler function...

**Comment by mac389** [comment]
You mean the following?

     func longPressed(longPress: UIGestureRecognizer){
          self.longPressHandler(self)
}

**Comment by i-schuetz** [comment]
Yes, that's why I wrote analogous to touchHandler.

**Comment by mac389** [comment]
I am still missing something. A tap and hold leads to no transition now. I think I followed your suggestions. There is no transition whether `GestureRecognizer` is added to `bubbleView` or `EcosystemMasterViewController`

Gist: https://gist.github.com/mac389/0a5191ece2b870b33658

**Comment by i-schuetz** [comment]
Put the addGestureRecognizer in the initializer, directly after you create the recognizer.
