### ISSUE TITLE
how to combine chart as follows

### ISSUE THREAD

**Issue by hengchengfei** [i-schuetz/SwiftCharts#64]
**Top: CombinedChartDrawOrder.Candle + CombinedChartDrawOrder.Line
Bottom: BarChartData**

Their leftAxis and xAxis are different.
How to combine them in a chartView?

thank you.

![1070cd76-99d3-11e5-842a-6a1d24cdfe91](https://cloud.githubusercontent.com/assets/3182964/11705509/64cb58a2-9f2b-11e5-8a05-43b583c6f3f6.jpg)

**Comment by i-schuetz** [comment]
Just use 2 charts? And arrange the intervals such that they align.
The chart overlays are not confined to the chart's boundaries, such that e.g. those white lines should not be a problem.

**Comment by i-schuetz** [comment]
Is this solved? Feel free to submit more specific questions if you need more help.
