### ISSUE TITLE
Is it possible to build charts like this?

### ISSUE THREAD

**Issue by bmacin** [i-schuetz/SwiftCharts#69]
![img_2643](https://cloud.githubusercontent.com/assets/10099555/11931858/dd94a1e6-a816-11e5-9e2d-e501859a5398.jpg)
![img_2646](https://cloud.githubusercontent.com/assets/10099555/11931857/dd93c7f8-a816-11e5-898c-24a0fb799133.jpg)

**Comment by i-schuetz** [comment]
Yes. You will find everything you need in the examples, just have to combine the different components appropriately. The legends on top are not provided. You have to implement those views yourself.

**Comment by bmacin** [comment]
Thanks for your response, how can I get the vertical lines crossing through the circle points in the above chart and for the second chart candlestick will work I believe.

**Comment by i-schuetz** [comment]
You can use `ChartPointsViewsLayer` where you can pass a view generator which creates an `UIView` for each point... so basically you would need 2 layers, one that creates the line views, and another on top that creates the circle views. You would use this for both charts. Here https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/BarsExample.swift#L40 you see `ChartPointsViewsLayer` used to generate bars. Or also here https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/HelloWorld.swift#L43 there's a layer that generates an UILabel for each chart point.

**Comment by bmacin** [comment]
Thanks. :)

**Comment by bmacin** [comment]
How can I get the X-axis values in 12 Hr. format 12 AM, 12 PM, 12AM and as shown above how to customise for the week(Today and 21 Nov). I'm using ChartAxisValueDate for creating week and month but having trouble customising it.

**Comment by i-schuetz** [comment]
You can implement your own axis values, by subclassing [ChartAxisValue](https://github.com/i-schuetz/SwiftCharts/blob/24ddd625a7199e48a1eda5bd931280f0c1bd34bf/SwiftCharts/AxisValues/ChartAxisValue.swift). There you write custom logic to map the internal value (scalar) to the labels.
