### ISSUE TITLE
Creating Chart using existing view after viewDidLayoutSubviews displays only data point layer

### ISSUE THREAD

**Issue by reivax** [i-schuetz/SwiftCharts#75]
Steps to repro:
- Use the gist from https://gist.github.com/i-schuetz/f6e285eb0c86bb831510
- instead of calling initChart during viewDidLayoutSubviews - use an NSTimer to call initChart after say 2 sec (this mimics my scenario where I want to display the chart after getting data from a http get) 
```
var timer = NSTimer.scheduledTimerWithTimeInterval(2, target: self, selector: "initChart", userInfo: nil, repeats: false)
```
Results:
- only the data point layer is displayed - the axis and background layers are not displayed. The main reason seem to be the data point layer is pushed in the view after creation but the axis layers are not?
I tried to call setNeedsDisplay on the main view, the chart view but no luck...

Side effect: the view in the storyboard has 4 constraints and the following warning is shown fyi :This application is modifying the autolayout engine from a background thread, which can lead to engine corruption and weird crashes.  This will cause an exception in a future release.

Any idea on how to get this to work? thanks!

**Comment by i-schuetz** [comment]
I think your problem is that you're not holding a strong reference to the chart. This is why all the examples have the "arc" comment next to the instance variable. I'll add a note about this in the readme as it seems to happen quite frequently...
