### ISSUE TITLE
Pan & Zoom

### ISSUE THREAD

**Issue by iainbryson** [i-schuetz/SwiftCharts#76]
Good day,

First, thanks for your library!  It's very nicely engineered.

I'd like to figure out how to add some functionality that is not very obvious.  In particular, I'd like to do Pan and Zoom gestures without using scrolling: i.e. no bitmap stretching for the zoom and keeping the axis locations fixed while panning.

Is there a preferred approach to this? Essentially this amounts to smoothly changing the transformation from data coordinates to screen coordinates, moving the points as the dictated by the change and then updating the labels on the axes.

There don't seem to be examples of changing the points or the axes after the chart is created so any guidance would be appreciated.

Thanks!

**Comment by i-schuetz** [comment]
Hi,
thanks!! - The chart is for the most part immutable but this should be easy to change. Basically it's changing the `let` s into `var`s and probably adding some `didSet` observers to update what's necessary. It would also need a mechanism to notify the layers on top of the updated layer, which would have to be redrawn to keep the z-ordering correctly. I think this could be done via the `chart` reference (which has references to the layers), which is passed to layers.

Panning: you can keep the axis locations fixed while scrolling, by adding the axis layer that would scroll to a different chart instance. See code here https://github.com/i-schuetz/SwiftCharts/issues/59

Infinite scrolling is not implemented and I think it's not trivial. But with a good understanding of how the library works it's possible :) For the zooming maybe I would implement a generic ZoomingLayer or similar, that's basically an invisible view that handles the gesture and propagates the updates to the other layers... The handling of zoom update would have to be implemented in a layer superclass, such that it's reusable, or maybe use protocol extensions such that is a "behaviour" that can be mixed in? Each layer would then apply the transformations to its views or context graphics.

**Comment by i-schuetz** [comment]
Hi,
thanks!! 
You mean like this? http://bl.ocks.org/stepheneb/1182434

**Comment by iainbryson** [comment]
Yep, that’s it.

I’ve done a lot of stuff with d3.js, and I think I had almost the exact
example in mind ;)

On Wed, Jan 13, 2016 at 8:28 PM, Ivan Schütz <notifications@github.com>
wrote:

> Hi,
> thanks!!
> You mean like this? http://bl.ocks.org/stepheneb/1182434
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/i-schuetz/SwiftCharts/issues/76#issuecomment-171527150>
> .
>



-- 
— Iain

**Comment by iainbryson** [comment]
Hello Ivan!

I don’t need infinite scroll, so that’s not a problem.

I’ve ended up getting pretty far using your suggestion for panning:
separate charts for points, x and y axis.  This allows me to clip the
points to a visible portion of the screen and control the scrolling for the
axis (i.e. only pan x in the x axis).  It works nicely. If it sounds
interesting to you, I can make sure it’s OK with my employer and submit a
pull request for an example that shows the implementation.

Zooming is not as pretty.  It works well for the points, but the axis tick
labels are text which gets stretched and ugly.  Ideally I’d like to move
the text elements (like an animation).  Could you point me in the right
direction for that?  I recall reading that it’s possible for each of the
tick labels to have their own view, and so be moveable.  But it’s not clear
how I can access that from “outside” of the library.

This is related to one design point on the library I wanted to ask about:
have you considered separating the “Axis” concept?  Right now the notion of
the tick marks, the coordinate transformation and the border are all bound
together as “axis”.  It particular, it would be useful sometimes to start
the edge of the visible portion of a chart away from the first tick mark.
i.e. imagine you have a scatter chart with a point at 9.97 in x.  It would
be nicer to have a little space at the left edge of the chart and the first
tick mark at x=10 in some cases.

Thanks!


On Wed, Jan 13, 2016 at 4:16 PM, Ivan Schütz <notifications@github.com>
wrote:

> Hi,
> thanks!! - The chart is for the most part immutable but this should be
> easy to change. Basically it's changing the let s into vars and probably
> adding some didSet observers to update what's necessary. It would also
> need a mechanism to notify the layers on top of the updated layer, which
> would have to be redrawn to keep the z-ordering correctly. I think this
> could be done via the chart reference (which has references to the
> layers), which is passed to layers.
>
> Panning: you can keep the axis locations fixed while scrolling, by adding
> the axis layer that would scroll to a different chart instance. See code
> here #59 <https://github.com/i-schuetz/SwiftCharts/issues/59>
>
> Infinite scrolling is not implemented and I think it's not trivial. But
> with a good understanding of how the library works it's possible :) For the
> zooming maybe I would implement a generic ZoomingLayer or similar, that's
> basically an invisible view that handles the gesture and propagates the
> updates to the other layers... The handling of zoom update would have to be
> implemented in a layer superclass, such that it's reusable, or maybe use
> protocol extensions such that is a "behaviour" that can be mixed in? Each
> layer would then apply the transformations to its views or context graphics.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/i-schuetz/SwiftCharts/issues/76#issuecomment-171480457>
> .
>



-- 
— Iain

**Comment by i-schuetz** [comment]
Hi -  if you look at the thread in Github you'd notice I deleted that answer ;) Was not sure what you were talking about, but now it's clear.

The axes only have to implement the [ChartAxisLayer](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Axis/ChartAxisLayer.swift) protocol. You can use a custom implementation instead of the default ones. I would add a handler for zoom updates somewhere in a common superclass such that all the layers, including the axes can handle them. A good candidate would be [ChartLayerBase](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartLayerBase.swift), but the axes currently don't subclass this. We are actually discussing the layer architecture in https://github.com/i-schuetz/SwiftCharts/issues/73. @interstateone had some suggestions and may do changes here, maybe you want to join this discussion?

Of course I'm interested in a pull request, this would be a very useful addition!

**Comment by i-schuetz** [comment]
P.S. In this [pull request](https://github.com/i-schuetz/SwiftCharts/pull/70/files) you can find inline documentation for `ChartAxisLayer` and some other classes.

**Comment by iainbryson** [comment]
I hope to find the time to address this next week. Sorry for the delay Ivan.
