### ISSUE TITLE
From Swift 1.x to Swift 2.x

### ISSUE THREAD

**Issue by sniis84** [i-schuetz/SwiftCharts#77]
Dear All,
maybe it is really easy but I really do not want to mess up with my old project.
I have an only project wherein I used SwiftCharts under Swift 1.x, is there an easy way to convert it to Swift 2.x without starting from scratch?

Even after updating my Podfile nothing changes in the project.

Thanks

**Comment by i-schuetz** [comment]
You don't have to start from scratch! If you update the pod and open your old project in XCode 7 I think it will assist you with the syntax changes. You can also go through the commit history, there are some commits for Swift 2 where you can see what was changed. It wasn't that much.

**Comment by sniis84** [comment]
I update the Podfile and typed pod install again.
Everything was updated, but when I open the project I still have >200 errors. Most of them I corrected using auto-fix (mainly related to the # issue in function calling).

This line I really don't understand how to fix (ChartYAxisRendererHorizontalBarChart.swift:drawYLabels)

            ChartUtils.drawText(context: text: text, point: CGPoint(x: positions[i].x, y: fixedPosition - offset), align: .Center, attributes: [NSFontAttributeName: labelFont, NSForegroundColorAttributeName: labelTextColor])

Can you help me?

**Comment by sniis84** [comment]
how about this

            var textBounds = centerTextNs.boundingRectWithSize(boundingRect.size, options: .UsesLineFragmentOrigin | .UsesFontLeading | .TruncatesLastVisibleLine, attributes: drawingAttrs, context: nil)

and that

            centerTextNs.drawWithRect(drawingRect, options: .UsesLineFragmentOrigin | .UsesFontLeading | .TruncatesLastVisibleLine, attributes: drawingAttrs, context: nil)

error: type of expression is ambiguous without more context (PieChartRedenderer.swift:drawCenterText)

**Comment by sniis84** [comment]
I have issues also modifying this part (ChartViewBase.swift):

// MARK: - Touches
    
    public override func touchesBegan(touches: Set<NSObject>, withEvent event: UIEvent)
    {
        if (!_interceptTouchEvents)
        {
            super.touchesBegan(touches, withEvent: event)
        }
    }
    
    public override func touchesMoved(touches: Set<NSObject>, withEvent event: UIEvent)
    {
        if (!_interceptTouchEvents)
        {
            super.touchesMoved(touches, withEvent: event)
        }
    }
    
    public override func touchesEnded(touches: Set<NSObject>, withEvent event: UIEvent)
    {
        if (!_interceptTouchEvents)
        {
            super.touchesEnded(touches, withEvent: event)
        }
    }
    
    public override func touchesCancelled(touches: Set<NSObject>, withEvent event: UIEvent)
    {
        if (!_interceptTouchEvents)
        {
            super.touchesCancelled(touches, withEvent: event)
        }
    }

Method does not override any method of its superclass

**Comment by sniis84** [comment]
and finally this (ChartViewBase.swift):

    public func observeValueForKeyPath(keyPath: String, ofObject object: AnyObject, change: [NSObject: AnyObject], context: UnsafeMutablePointer<Void>)
    {

**Comment by i-schuetz** [comment]
None of the files or code you mention are from SwiftCharts.

**Comment by sniis84** [comment]
You are right sorry.
I have this old app in which I tried several libraries for plotting.
But at the end I chose yours because was the most versatile :)
I did what you suggest in the main page but it says it cannot find the module SwiftCharts

**Comment by sniis84** [comment]
Please delete this post. Thanks as always for the support.
I figured it out.

**Comment by i-schuetz** [comment]
You're welcome! Deleting is not possible ;) https://github.com/isaacs/github/issues/253
