### ISSUE TITLE
How to remove text on AxixY?

### ISSUE THREAD

**Issue by orkhanalizade** [i-schuetz/SwiftCharts#79]
Hi. How can I remove text from the AxisY? I want to disable this function from my chart

**Comment by i-schuetz** [comment]
You can use a axis value subclass that doesn't return labels:

```
class EmptyAxisValue: ChartAxisValueDouble {
    override var labels: [ChartAxisLabel] {
        return []
    }
}
```
And pass an empty axis title.
In case you would also want to remove the line, you can simply not pass the y axis layer to `Chart`.

**Comment by orkhanalizade** [comment]
Thanks for your response! And where need I use this snippet? I've added it under the class, where I'm using charts, but it did not make a sense. I think I do something wrong

**Comment by i-schuetz** [comment]
Yes you have to replace `ChartAxisValueDouble` with `EmptyAxisValue` there. You also don't have to pass `labelSettings` then.

**Comment by orkhanalizade** [comment]
Thanks, but it still fills the place on my view. It's empty, yes, but it fills the place as it there

**Comment by i-schuetz** [comment]
You have to set all the relevant settings to 0 in `ChartSettings` (`leading`, `labelsToAxisSpacingY`, `axisTitleLabelsToLabelsSpacing`). I think after that it still reserves a bit of space for the title. You can pass a negative value to `leading` to make it shift to the left or also shift the view where the chart is in to the left.

**Comment by orkhanalizade** [comment]
Thanks for you response!
