### ISSUE TITLE
How to highlight range and show irregular date scale with even intervals

### ISSUE THREAD

**Issue by skrite** [i-schuetz/SwiftCharts#80]
is there an option to put a band marking a specific range in a line chart? for example, if i have a graph that scales from 0 - 100, could I highlight 20-24 somehow? Also, do these line charts support a date-time scale for the x-axis ? Thanks

**Comment by i-schuetz** [comment]
Range: Yes you mean something similar to here in the first image https://github.com/i-schuetz/SwiftCharts/issues/69 quoting the relevant part:
> You also can use a layer for the highlighted area between 80 and 140 in the first chart. The quickest approach would be to use also a `ChartPointsViewsLayer`, pass a dummy chart point to it and generate a view that covers this area. To calculate the frame of this view you would also use `modelLocToScreenLoc`. 

Date-time scale: You can use `ChartAxisValueDate` and pass a custom date formatter. If you need further customisation you can create your own `ChartAxisValue` subclass. Everything that can be represented internally by a number can be used.

**Comment by skrite** [comment]
yes, this was exactly what I was asking for. Your image was perfect. Thanks.  About the time scale. If i create this ChartAxisValueDate and have a lot of plots on my line chart, if say, three plots are within a couple of hours and others are a few days between them, will it space them out on the chart like that? 
![draw_quick_chart](https://cloud.githubusercontent.com/assets/176528/12652995/0da98b80-c5b3-11e5-8a58-c9c84a0098a0.png)

**Comment by i-schuetz** [comment]
In that case the internal number is basically independent of the labels. You can number internally with an evenly spaced interval (1,2,3.. would be enough) and return the labels you want to show. There is actually an [example](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/EqualSpacingExample.swift) for this ;)

**Comment by skrite** [comment]
and this would not spread the plots out evenly along the x-Axis? it would be a graphical representation of the time passed between the plot points?  And yes, They are independant of the labels.

**Comment by i-schuetz** [comment]
You are just mapping to a different scale which has also different proportions, as long as you map the x values of your chartpoints to the same scale it should be fine?

**Comment by skrite** [comment]
Awesome. Thanks !
