### ISSUE TITLE
example chart only showing lines. 

### ISSUE THREAD

**Issue by skrite** [i-schuetz/SwiftCharts#84]
Greetings. 
I have installed swiftcharts and run the example simple line chart from the README . However, when run, it only shows the line (i only ran with one line instead of two). .  
Also, when I run it with my own plot points, there is not line at all. I believe this is because the plots are out of range to be shown on the chart (they are unix timestamps that i will eventually turn to a date scale). Is there a way to auto-scale the chart?  Thanks. 
![screen shot 2016-02-03 at 9 09 41 am](https://cloud.githubusercontent.com/assets/176528/12788990/869a7f10-ca61-11e5-970c-fce8ac47e6e5.png)

**Comment by i-schuetz** [comment]
https://github.com/i-schuetz/SwiftCharts#important ;)

**Comment by skrite** [comment]
Thank you for your reply. 
I kinda don't understand what you mean by 'keeping a strong reference' I am very new to swift. 
If i use this code
`let chart = LineChart(
            frame: CGRectMake(0, 70, 300, 500),
            chartConfig: chartConfig,
            xTitle: "X axis",
            yTitle: "Y axis",
            lines: [
                //(chartPoints: [(2.0, 10.6), (4.2, 5.1), (7.3, 3.0), (8.1, 5.5), (14.0, 8.0)], color: UIColor.redColor()),
                (chartPoints: arrayOfPlotPoints, color: UIColor.blueColor())
            ]
            
        )`

nothing shows up, however if i uncomment the other plots (mine) and uncomment the example, i get the line. 
Again, i think that it is the range.

**Comment by i-schuetz** [comment]
Ah, it's just that you reference the chart with an instance variable so it's not deallocated when the method finishes executing. This is in all the examples followed with an "arc" comment. The axes show independently of range.

**Comment by skrite** [comment]
ok, I added the instance variable, but still getting the same results.
My whole class is located here.
https://gist.github.com/skrite/825ad7787c46728b8474

**Comment by i-schuetz** [comment]
You also have to assign the local variable to the instance variable ;)

**Comment by skrite** [comment]
yay ! the scale showed up. man thanks ! 
I still don't have my plots and lines though, is that because of the scale? 
is there an auto scale option?

**Comment by i-schuetz** [comment]
As I wrote you have to ensure that the range of the axes matches the range of the chart points. E.g. the timestamps are definitely not in the 0-15 range you use in the y-axis. If you don't want to create the axis values yourself you can use `ChartAxisValuesGenerator` to generate them based on the chart points. For this though you have to use the more explicit way to create charts (which is used in most examples).

**Comment by skrite** [comment]
ok, that should get me going. thanks for all of your help

**Comment by i-schuetz** [comment]
You're welcome!
