### ISSUE TITLE
How to change the line width of the Axis?

### ISSUE THREAD

**Issue by christinalau** [i-schuetz/SwiftCharts#86]
Hi, is it possible to change the width of the graph axis? I can change the line width in the graph, but not the axis. Like to have something thicker on iPad. Thanks...

**Comment by i-schuetz** [comment]
Yep, you can use `chartSettings.axisStrokeWidth` for this.

**Comment by christinalau** [comment]
I updated the number in ExamplesDefaults.swift, but it doesn't seem to do anything. The only noticeable difference is the (0,0) coordinate doesn't touch anymore. Where should I make this change?

**Comment by i-schuetz** [comment]
In ExampleDefaults there are settings both for iPad and iPhone, did you
update the correct one?

2016-02-04 18:18 GMT+01:00 Christina Lau <notifications@github.com>:

**Comment by christinalau** [comment]
Yes I tried both, and they have no effects, I tried different numbers too.

**Comment by i-schuetz** [comment]
Hmm I just tried it out and it works, are you sure you are also using the
settings in your chart? Did you double check you are setting
`axisStrokeWidth` and not something else?

2016-02-04 18:40 GMT+01:00 Christina Lau <notifications@github.com>:

**Comment by christinalau** [comment]
That is what I am unsure of. How do you set it? In your examples, you only have this:
 
let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: ExamplesDefaults.chartSettings, chartFrame: chartFrame, xModel: xModel, yModel: yModel)

Do I need to set something else?
I didn't change any of the sample code, just that one line. Maybe I need to change more to see something?

**Comment by i-schuetz** [comment]
Can you instantiate the settings directly and pass them to the coords
space, if it still doesn't work then please post your full code (with this
change).

2016-02-04 19:00 GMT+01:00 Christina Lau <notifications@github.com>:

**Comment by christinalau** [comment]
You mean this?

let chartSettings = ChartSettings()
chartSettings.axisStrokeWidth = 10

let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings:
chartSettings, chartFrame: chartFrame, xModel: xModel, yModel: yModel)

No, it still doesn't work. The full code is exactly the same as the sample
code. This is the change I made.


On Thu, Feb 4, 2016 at 1:04 PM, Ivan Schütz <notifications@github.com>
wrote:

> Can you instantiate the settings directly and pass them to the coords
> space, if it still doesn't work then please post your full code (with this
> change).
>
> 2016-02-04 19:00 GMT+01:00 Christina Lau <notifications@github.com>:
>
> > That is what I am unsure of. How do you set it? In your examples, you
> only
> > have this:
> >
> > let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings:
> > ExamplesDefaults.chartSettings, chartFrame: chartFrame, xModel: xModel,
> > yModel: yModel)
> >
> > Do I need to set something else?
> > I didn't change any of the sample code, just that one line. Maybe I need
> > to change more to see something?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/i-schuetz/SwiftCharts/issues/86#issuecomment-179968706>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/i-schuetz/SwiftCharts/issues/86#issuecomment-179971008>
> .
>



-- 
Christina

**Comment by i-schuetz** [comment]
```

import UIKit
import SwiftCharts

class HelloWorld: UIViewController {

    private var chart: Chart? // arc

    override func viewDidLoad() {
        super.viewDidLoad()

        // map model data to chart points
        let chartPoints: [ChartPoint] = [(2, 2), (4, 4), (6, 6), (8, 10), (12, 14)].map{ChartPoint(x: ChartAxisValueInt($0.0), y: ChartAxisValueInt($0.1))}

        let labelSettings = ChartLabelSettings(font: ExamplesDefaults.labelFont)
        
        // define x and y axis values (quick-demo way, see other examples for generation based on chartpoints)
        let xValues = 0.stride(through: 16, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}
        let yValues = 0.stride(through: 16, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}
        
        // create axis models with axis values and axis title
        let xModel = ChartAxisModel(axisValues: xValues, axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings))
        let yModel = ChartAxisModel(axisValues: yValues, axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings.defaultVertical()))
        
        let chartFrame = ExamplesDefaults.chartFrame(self.view.bounds)
        
        // generate axes layers and calculate chart inner frame, based on the axis models
        let chartSettings = ChartSettings()
        chartSettings.leading = 10
        chartSettings.top = 10
        chartSettings.trailing = 10
        chartSettings.bottom = 10
        chartSettings.labelsToAxisSpacingX = 5
        chartSettings.labelsToAxisSpacingY = 5
        chartSettings.axisTitleLabelsToLabelsSpacing = 4
        chartSettings.axisStrokeWidth = 5
        chartSettings.spacingBetweenAxesX = 8
        chartSettings.spacingBetweenAxesY = 8
        let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: chartSettings, chartFrame: chartFrame, xModel: xModel, yModel: yModel)

        let (xAxis, yAxis, innerFrame) = (coordsSpace.xAxis, coordsSpace.yAxis, coordsSpace.chartInnerFrame)
        
        // create layer with guidelines
        let guidelinesLayerSettings = ChartGuideLinesDottedLayerSettings(linesColor: UIColor.blackColor(), linesWidth: ExamplesDefaults.guidelinesWidth)
        let guidelinesLayer = ChartGuideLinesDottedLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, settings: guidelinesLayerSettings)
        
        // view generator - this is a function that creates a view for each chartpoint
        let viewGenerator = {(chartPointModel: ChartPointLayerModel, layer: ChartPointsViewsLayer, chart: Chart) -> UIView? in
            let viewSize: CGFloat = Env.iPad ? 30 : 20
            let center = chartPointModel.screenLoc
            let label = UILabel(frame: CGRectMake(center.x - viewSize / 2, center.y - viewSize / 2, viewSize, viewSize))
            label.backgroundColor = UIColor.greenColor()
            label.textAlignment = NSTextAlignment.Center
            label.text = chartPointModel.chartPoint.y.description
            label.font = ExamplesDefaults.labelFont
            return label
        }
        
        // create layer that uses viewGenerator to display chartpoints
        let chartPointsLayer = ChartPointsViewsLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, chartPoints: chartPoints, viewGenerator: viewGenerator)
        
        // create chart instance with frame and layers
        let chart = Chart(
            frame: chartFrame,
            layers: [
                coordsSpace.xAxis,
                coordsSpace.yAxis,
                guidelinesLayer,
                chartPointsLayer
            ]
        )
        
        self.view.addSubview(chart.view)
        self.chart = chart
    }
}
```
![simulator screen shot 04 feb 2016 22 28 44](https://cloud.githubusercontent.com/assets/1381744/12830306/d9dc7c40-cb8e-11e5-9ecd-c63c7d94199c.png)

**Comment by christinalau** [comment]
I ran your code on my mac, I got this instead:


[image: Inline image 1]

On Thu, Feb 4, 2016 at 4:30 PM, Ivan Schütz <notifications@github.com>
wrote:

>
> import UIKit
> import SwiftCharts
>
> class HelloWorld: UIViewController {
>
>     private var chart: Chart? // arc
>
>     override func viewDidLoad() {
>         super.viewDidLoad()
>
>         // map model data to chart points
>         let chartPoints: [ChartPoint] = [(2, 2), (4, 4), (6, 6), (8, 10), (12, 14)].map{ChartPoint(x: ChartAxisValueInt($0.0), y: ChartAxisValueInt($0.1))}
>
>         let labelSettings = ChartLabelSettings(font: ExamplesDefaults.labelFont)
>
>         // define x and y axis values (quick-demo way, see other examples for generation based on chartpoints)
>         let xValues = 0.stride(through: 16, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}
>         let yValues = 0.stride(through: 16, by: 2).map {ChartAxisValueInt($0, labelSettings: labelSettings)}
>
>         // create axis models with axis values and axis title
>         let xModel = ChartAxisModel(axisValues: xValues, axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings))
>         let yModel = ChartAxisModel(axisValues: yValues, axisTitleLabel: ChartAxisLabel(text: "Axis title", settings: labelSettings.defaultVertical()))
>
>         let chartFrame = ExamplesDefaults.chartFrame(self.view.bounds)
>
>         // generate axes layers and calculate chart inner frame, based on the axis models
>         let chartSettings = ChartSettings()
>         chartSettings.leading = 10
>         chartSettings.top = 10
>         chartSettings.trailing = 10
>         chartSettings.bottom = 10
>         chartSettings.labelsToAxisSpacingX = 5
>         chartSettings.labelsToAxisSpacingY = 5
>         chartSettings.axisTitleLabelsToLabelsSpacing = 4
>         chartSettings.axisStrokeWidth = 5
>         chartSettings.spacingBetweenAxesX = 8
>         chartSettings.spacingBetweenAxesY = 8
>         let coordsSpace = ChartCoordsSpaceLeftBottomSingleAxis(chartSettings: chartSettings, chartFrame: chartFrame, xModel: xModel, yModel: yModel)
>
>         let (xAxis, yAxis, innerFrame) = (coordsSpace.xAxis, coordsSpace.yAxis, coordsSpace.chartInnerFrame)
>
>         // create layer with guidelines
>         let guidelinesLayerSettings = ChartGuideLinesDottedLayerSettings(linesColor: UIColor.blackColor(), linesWidth: ExamplesDefaults.guidelinesWidth)
>         let guidelinesLayer = ChartGuideLinesDottedLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, settings: guidelinesLayerSettings)
>
>         // view generator - this is a function that creates a view for each chartpoint
>         let viewGenerator = {(chartPointModel: ChartPointLayerModel, layer: ChartPointsViewsLayer, chart: Chart) -> UIView? in
>             let viewSize: CGFloat = Env.iPad ? 30 : 20
>             let center = chartPointModel.screenLoc
>             let label = UILabel(frame: CGRectMake(center.x - viewSize / 2, center.y - viewSize / 2, viewSize, viewSize))
>             label.backgroundColor = UIColor.greenColor()
>             label.textAlignment = NSTextAlignment.Center
>             label.text = chartPointModel.chartPoint.y.description
>             label.font = ExamplesDefaults.labelFont
>             return label
>         }
>
>         // create layer that uses viewGenerator to display chartpoints
>         let chartPointsLayer = ChartPointsViewsLayer(xAxis: xAxis, yAxis: yAxis, innerFrame: innerFrame, chartPoints: chartPoints, viewGenerator: viewGenerator)
>
>         // create chart instance with frame and layers
>         let chart = Chart(
>             frame: chartFrame,
>             layers: [
>                 coordsSpace.xAxis,
>                 coordsSpace.yAxis,
>                 guidelinesLayer,
>                 chartPointsLayer
>             ]
>         )
>
>         self.view.addSubview(chart.view)
>         self.chart = chart
>     }
> }
>
> [image: simulator screen shot 04 feb 2016 22 28 44]
> <https://cloud.githubusercontent.com/assets/1381744/12830306/d9dc7c40-cb8e-11e5-9ecd-c63c7d94199c.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/i-schuetz/SwiftCharts/issues/86#issuecomment-180060798>
> .
>



-- 
Christina

**Comment by i-schuetz** [comment]
The img is not showing, I only see [image: Inline image 1] ;)

**Comment by christinalau** [comment]
Attaching directly into the comment view..
![simulator screen shot feb 4 2016 4 47 01 pm](https://cloud.githubusercontent.com/assets/5726085/12831639/53151616-cb63-11e5-8058-243414380fcd.png)

**Comment by i-schuetz** [comment]
Hmm, I have no idea. Which version of SwiftCharts are you using? There have been no changes concerning this though.

I'd say that you do a fresh clone of the repository and run the examples and then check step by step what may be different than your current code. If it's a bug in the library then maybe time to do a pull request? ;)

**Comment by christinalau** [comment]
Hi, here is what I found. 
1. I download the current zip file (SwiftCharts-master.zip), ran the example, and it works.
2. I did the cocoa pod update in my existing project, and it doesn't work. The pod file is exactly the same as in the readme (pod 'SwiftCharts', '~> 0.3')

Can you tell me how I am supposed to update my existing project to pick up the latest? Is the pod file way getting the same content as the zip file?

**Comment by i-schuetz** [comment]
You can use master directly, it's stable and there are not a lot of changes (and the ones which are there are backwards compatible). You would need this in your podfile:
```
    pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```
I suspect though that there's something wrong with your project, in this case it would not be solved by changing the pod to master (unless this causes a clean/refresh somehow which solves it), did you try also cloning/downloading the 0.3 tag?

**Comment by i-schuetz** [comment]
Ohh I just went through the commits and there was actually a pull request about this. I forgot, sorry! So yes it doesn't work and it's fixed in master. If you update your podfile as described above it should work.
