### ISSUE TITLE
Setting axis' data and titles to UILabel

### ISSUE THREAD

**Issue by MariamNers** [i-schuetz/SwiftCharts#87]
Hi! Trying to set axis' data and titles to UILabel so that the VoiceOver is able to pick it up. Any ideas?

**Comment by i-schuetz** [comment]
Hi,

the axis titles are easy, you just would have to pass no axis titles to the chart and use your own labels instead. You would have to ensure they are positioned correctly.

For the axis numbers, you can create your own axis implementation. There's a generic protocol for axis: [ChartAxisLayer](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Axis/ChartAxisLayer.swift). With this you would also not need the workaround described above for the titles but would also do this with your custom implementation.

Another alternative (easier I think) would be to mark all the axis values as hidden or pass empty labels and create the labels as chartpoints, using [ChartPointsViewsLayer](https://github.com/i-schuetz/SwiftCharts/blob/master/SwiftCharts/Layers/ChartPointsViewsLayer.swift) ([here](https://github.com/i-schuetz/SwiftCharts/blob/master/Examples/Examples/HelloWorld.swift#L55) e.g. you can see how it's used). You would pass map your axis values to chart points (where one coordinate is the "constant" coordinate of the axis, probably 0). And you have to offset the frames of the views a bit such that they appear outside of the chart.

**Comment by i-schuetz** [comment]
Where you able to advance with this? If there's problem please provide more details glad to assist.

**Comment by kilabyte** [comment]
how would you mark the axis values as hidden? within the label settings passed to the ChartAxisLayer?

**Comment by i-schuetz** [comment]
`ChartAxisValue` has a `hidden` variable. You have to set it when initialising the axis values.

**Comment by kilabyte** [comment]
Looks like the pod source code is different then cloning github? Both ChartAxisValue and ChartAxisLabel are different from github and from my pod install. (yes I've don't pod update and have version 0.3). In the example code i can see the use of .hidden but when i use it in my implementation i get "has no member 'hidden'". If i check the classes .hidden does not exist.

**Comment by i-schuetz** [comment]
Here it is in the [0.3 tag](https://github.com/i-schuetz/SwiftCharts/blob/0.3/SwiftCharts/AxisValues/ChartAxisValue.swift#L31) and in [master](https://github.com/i-schuetz/SwiftCharts/blob/b678222e6cb568bc7c0bc8a33998ef75fac7693d/SwiftCharts/AxisValues/ChartAxisValue.swift#L20)

**Comment by kilabyte** [comment]
Hmm ok its not there so i just cloned the github repo... but it still doesn't work. Here is my code. Everything compiles now that member hidden is there but it doesn't actually hide anything.
![screen shot 2016-02-15 at 3 03 03 pm](https://cloud.githubusercontent.com/assets/487948/13062705/5e885bd0-d3f5-11e5-92ec-06494ea8c519.png)
![screen shot 2016-02-15 at 3 04 00 pm](https://cloud.githubusercontent.com/assets/487948/13062706/5eb07e80-d3f5-11e5-890e-9fe6aeddd37b.png)

**Comment by i-schuetz** [comment]
I just replaced the code to generate the x values in hello world example in master with this:
```
let xValues: [ChartAxisValue] = 0.stride(through: 16, by: 2).map {
    let v = ChartAxisValueDouble($0, labelSettings: labelSettings)
    v.hidden = true
    return v
}
```
And it works. Are you sure you are calling that function and passing the generated values to the chart?

**Comment by kilabyte** [comment]
<img width="1406" alt="screen shot 2016-02-15 at 4 37 16 pm" src="https://cloud.githubusercontent.com/assets/487948/13063942/69281e56-d402-11e5-97ff-4e015d3eab14.png">
Yup

**Comment by i-schuetz** [comment]
Well, then, since you already cloned the repository you're kindly encouraged to debug the issue :)

This flag is not difficult to track down until it's used to decide if the label is drawn or not.

**Comment by kilabyte** [comment]
hmmm haha ok will do

**Comment by i-schuetz** [comment]
Great!

**Comment by kilabyte** [comment]
i was able to find the bug. But looking at the hello world in master, those classes for the SwiftCharts do not match the classes of SwiftCharts from Cocoapods. Here is a screen showing the class "ChartAxisValueDouble.swift" On the left is the Cocoapods and on the right is the master clone on github. Also the workaround/bug you can see on line 32 on the left class i added "axisLabel.hidden = self.hidden". The hidden property now works.

![screen shot 2016-02-17 at 12 02 33 am](https://cloud.githubusercontent.com/assets/487948/13103296/1a9d572a-d50a-11e5-80fc-ae524a50458a.png)

**Comment by i-schuetz** [comment]
Ah, right! Somebody changed the structure a bit and I see now that this also fixes this bug. So the issue - as you noticed - is that the axis values subclasses were overriding `labels`, so the hidden flag was not being set. With the new structure the label defaults to the description, such that it's not necessary to override `labels` anymore but only `description` which returns the text (you may want to override `labels` to show multiple labels per axis value, but this is rarely used).

You probably should just use master, it's stable. You would need this in your podfile:

```ruby
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git'
```

Thanks for taking the time to investigate it, very appreciated!

**Comment by i-schuetz** [comment]
Btw: Alternatives to hidden are also using empty strings or a custom `ChartAxisValue` subclass that returns an empty labels array. [Here](https://github.com/i-schuetz/SwiftCharts/issues/81) near the end you find the code for this.

**Comment by kilabyte** [comment]
Great! Glad I could help! I made a bunch of other changes to some classes to override the scale of a chart so that I could see a bar with a value of 200 and a value of 20 within a range of 20 (client requirement) so I'll prob just keep my version as now it's working fantastic! If there's anything else I'm glad to help out but the framework is solid love it!

**Comment by i-schuetz** [comment]
Thanks :)
