### ISSUE TITLE
Adjusting Charts' frame manually 

### ISSUE THREAD

**Issue by MariamNers** [i-schuetz/SwiftCharts#88]
Hi!
As far as i understood, the frame is set via Env.Ipad? (or any other interface), however I am trying to customise this view so that the charts are not so large.
Is this possible?

**Comment by i-schuetz** [comment]
You can remove that and pass as frame anything you want.

**Comment by MariamNers** [comment]
Duh thanks, that worked :) Also on that note, in your hello world example, when i tried to input a larger value to see how the graph will wrap them up it just didnt fit in the screen and on the grid. How can i fix this? Sorry not sure if this was asked before. Thanks for your help!

**Comment by i-schuetz** [comment]
A larger value where? A chart point? You have to ensure that everything is in range. Not sure if this is what you mean.

**Comment by MariamNers** [comment]
![screen shot 2016-02-08 at 19 42 30](https://cloud.githubusercontent.com/assets/17073482/12896867/38ea34b0-ce9c-11e5-9439-d86409dc535f.png)

**Comment by i-schuetz** [comment]
Ok, so as I said: you have to ensure that the chart points are in range. That is select min max in axis according to your chart points. There is also `ChartAxisValuesGenerator` which you can use to generate the axis values from you, there's also a flag you can set to add an extra value when the chart point is at the edge like in (16, 16) in your screenshot.
