### ISSUE TITLE
Use of unresolved identifier 'ExamplesDefaults' Revisited

### ISSUE THREAD

**Issue by NasFwa** [i-schuetz/SwiftCharts#89]
I'm having the same problem as noted before:  For the detailed sample code, I get same 4 errors on different lines with "ExamplesDefaults:"
ex.: Use of unresolved identifier 'ExamplesDefaults'

I also get the same error message for two lines with "ChartPointCircleView"

I'm using xCode 7.2.1 and CocoaPods.  

Here the pod file I am using:
```
platform :ios, '8.0'
use_frameworks!
pod 'SwiftCharts', :git => 'https://github.com/i-schuetz/SwiftCharts.git', :branch => 'swift2.0', :commit => 'b7c523b'
```

Any suggestions?
Thanks

**Comment by NasFwa** [comment]
I tried the spec'd pod file first:
```
platform :ios, '8.0'
use_frameworks!
pod 'SwiftCharts', '~> 0.3'
```

Nas

**Comment by i-schuetz** [comment]
Hmm I haven't tried the library on 7.2.1 but it should work. Using the tag is correct, the swift 2.0 branch is not longer used and outdated. Can you narrow down the cause by building the framework? ExampleDefaults is not the problem.

**Comment by i-schuetz** [comment]
Just tested on 7.2.1 and it works, could you find more details?
