### ISSUE TITLE
not seeing a line on the chart

### ISSUE THREAD

**Issue by skrite** [i-schuetz/SwiftCharts#92]
hello. i have created a line chart. and pass the following points to it. 

`appending 19.0 at 1456318414.0
appending 18.0 at 1456318606.0
appending 19.0 at 1456318922.0
appending 19.0 at 1456318938.0
appending 19.0 at 1456319210.0
appending 19.0 at 1456319336.0
appending 19.0 at 1456319529.0
appending 19.0 at 1456319836.0
appending 31.0 at 1456319905.0
appending 31.0 at 1456320096.0
appending 26.0 at 1456322045.0
appending 24.0 at 1456404427.0
appending 23.0 at 1456404509.0
appending 24.0 at 1456406438.0
appending 24.0 at 1456406630.0
appending 19.0 at 1456406937.0
appending 20.0 at 1456407697.0
appending 20.0 at 1456407786.0
appending 18.0 at 1456491564.0
appending 19.0 at 1456491757.0
appending 19.0 at 1456492308.0
appending 18.0 at 1456495339.0
appending 18.0 at 1456495444.0
appending 18.0 at 1456495636.0
found lo psi = 18.0 on 1456318414.0
found hi psi = 31.0 on 1456495636.0
lowest Date = 1456318414.0
hightes Date = 1456495636.0
scales are set at 22152.75 and 1.625
`

here is the code
`Alamofire.request(.GET, url, parameters: ["id": site.pressureSensorID])
            .responseJSON { response in
                //print(response.result)   // result of response serialization
                
                // handle network problem
                switch response.result {
                case .Success(_):
                    print("success code back from api server for sites request")
                case .Failure(_):
                    let alertView = UIAlertController(title: "Connect Error", message: "Network error, please try again", preferredStyle: .Alert)
                    let alertAction = UIAlertAction(title: "OK", style: .Default) { _ in
                    }
                    alertView.addAction(alertAction)
                    self.presentViewController(alertView, animated: true) {}
                }
                
                if let jsonResult = response.result.value {
                    //print(response.result.value!)
                    
                    let arrayOfJSONDataPlots = JSON(jsonResult)
                    
                    for (key, item) in arrayOfJSONDataPlots {
                        var timestamp: Double = item[1].double!
                        let psi: Double = item[0].double!
                        
                        
                        // set the initial values for my comparison variables
                        if lowestDate == 0 {
                            lowestValue = psi
                            highestValue = psi
                            lowestDate = timestamp
                            highestDate = timestamp
                        }
                        
                        if highestValue < psi{
                           highestValue = psi
                        }
                        
                        if lowestValue > psi{
                           lowestValue = psi
                        }
                        
                        if timestamp < lowestDate{
                            lowestDate = timestamp
                        }
                        
                        if timestamp > highestDate {
                            highestDate = timestamp
                        }
                        
                        print("appending \(psi) at \(timestamp)")
                        self.arrayOfPlotPoints.append((psi, timestamp))
                    }
                    
        print("found lo psi = \(lowestValue) on \(lowestDate)")
        print("found hi psi = \(highestValue) on \(highestDate)")
        print("lowest Date = \(lowestDate)")
        print("hightes Date = \(highestDate)")
        
        var xScale: Double = (highestDate - lowestDate)
        var yScale: Double = (highestValue - lowestValue)
                    
        
        xScale = xScale / 8.0
        yScale = yScale / 8.0
        
        
        if xScale < 1 {
            xScale = 1
        }
        if yScale < 1 {
            yScale = 1
        }
                    
        
        print("scales are set at \(xScale) and \(yScale)")
        
        /*
        let chartConfig = ChartConfigXY(
            xAxisConfig: ChartAxisConfig(from: 0, to: 14, by: 2),
            yAxisConfig: ChartAxisConfig(from: 0, to: 15, by: 2)
        )
        */
        
        let chartConfig = ChartConfigXY(
            xAxisConfig: ChartAxisConfig(from: lowestDate, to: highestDate, by: xScale),
            yAxisConfig: ChartAxisConfig(from: lowestValue, to: highestValue, by: yScale)
        )
        
        let chart = LineChart(
            frame: CGRectMake(0, 70, 300, 500),
            chartConfig: chartConfig,
            xTitle: "X axis",
            yTitle: "Y axis",
            lines: [
            //(chartPoints: [(2.0, 10.6), (4.2, 5.1), (7.3, 3.0), (8.1, 5.5), (14.0, 8.0)], color: UIColor.redColor()),
            (chartPoints: self.arrayOfPlotPoints, color: UIColor.blueColor())
            ]
            
        )
        
        self.lineChartView.addSubview(chart.view)
        self.chart = chart
                    
                    
                    
                    
                    
                }
                else {
                    print("JSON data is nil.")
                }
        } // end of json sites request`

the scales and axis lables are showing up, but i cannot see the line.

would appreciate any help with this
![graph-screenie](https://cloud.githubusercontent.com/assets/176528/13361745/2f94e5f2-dc86-11e5-90eb-33c86c575f4d.png)

**Comment by i-schuetz** [comment]
Looks like you are setting the range you want for y in the x axis and the other way... btw you can also adjust the chart settings to provide enough spacing, such that the labels are not cut at the edges.

**Comment by skrite** [comment]
you were correct. thanks
