### ISSUE TITLE
trouble with landscape mode

### ISSUE THREAD

**Issue by skrite** [i-schuetz/SwiftCharts#95]
Hello there. 
I am having some trouble with landscape mode when using a line chart.
i have designed the view in landscape mode with the storyboard and programmatically force it to stay. I disabled the auto-rotate for just this view. 

However, the graph is not filling the space properly.

![screen shot 2016-03-01 at 9 41 19 am](https://cloud.githubusercontent.com/assets/176528/13432179/2a026a6a-df92-11e5-8f27-655fd98c55ae.png)
![screen shot 2016-03-01 at 9 41 35 am](https://cloud.githubusercontent.com/assets/176528/13432185/2e2122b2-df92-11e5-88b2-88423dff2a2f.png)

**Comment by i-schuetz** [comment]
This is not related with the chart. Your view apparently is still showing in portrait mode.

**Comment by skrite** [comment]
ok, thanks much

**Comment by i-schuetz** [comment]
No problem :)

**Comment by skrite** [comment]
i think i have this down. (was a problem with auto-layout)  is there a way to make the size of the chart dynamic? like get the dimensions of the view that contains it instead of the
 frame: CGRectMake(0, 70, 500, 900) ?  -thanks

**Comment by i-schuetz** [comment]
Sure! You can just pass the view using the other initialiser. You have to set the class of the view to `ChartBaseView` in the IB.

**Comment by skrite** [comment]
awesome, thanks

**Comment by skrite** [comment]
sorry, do you have an example of this. 
I found the super.init in the LineChart one of the args is a view, the other is layers ?

**Comment by i-schuetz** [comment]
Yes here's a gist: https://gist.github.com/i-schuetz/f6e285eb0c86bb831510

**Comment by skrite** [comment]
wow, thanks very much i will try to work with this and see what i can figure out. Sorry for the trouble, still very new to all of this.

**Comment by skrite** [comment]
sorry, another question. I don't get what is going on here.
.map{ChartPoint(x: ChartAxisValueInt($0.0), y: ChartAxisValueInt($0.1))}
with ChartAxisValueInt($0.0)  ?

**Comment by i-schuetz** [comment]
That's just to generate the axis values from tuples, which makes the code a bit more readable. `$0.0` is the first element of each tuple - which corresponds to the x coordinate and `$0.1` is the second which corresponds to the y coordinate.

**Comment by skrite** [comment]
gotcha, thanks
