### ISSUE TITLE
weird margins when using stack view

### ISSUE THREAD

**Issue by robomotic** [i-schuetz/SwiftCharts#98]
I am not sure about the origin of this issue but there is something rather odd happening when I use a simple StackView to plot 4 graphs in the same column.
This is how the UIViews are equally distributed 
![vertical stack](https://cloud.githubusercontent.com/assets/315964/13585944/4b41e59c-e4b6-11e5-99b8-0baf85bf4c5a.png)

But this happens when I plot the charts, it seems that some sort of margin is added into each drawing and no matter what fill option I use (scale to fill, aspect fit, aspect fill, redraw etc. etc.) the space is never filled accordingly.

![chartsmargin](https://cloud.githubusercontent.com/assets/315964/13586020/951ee106-e4b6-11e5-8fa1-db590adb07f9.png)

Just as a comparison I can put one BaseChart in the first row:
![partial](https://cloud.githubusercontent.com/assets/315964/13586077/e42a92e0-e4b6-11e5-93d7-c067bdab7a93.png)

It just looks wrong!

**Comment by i-schuetz** [comment]
have you tried adjusting the margins in the chart settings?

**Comment by robomotic** [comment]
Hmm my settings now looks like this:

`    private static var iPhoneChartSettings: ChartSettings {
        let chartSettings = ChartSettings()
        chartSettings.leading = 10
        chartSettings.top = 0
        chartSettings.trailing = 10
        chartSettings.bottom = 0
        chartSettings.labelsToAxisSpacingX = 5
        chartSettings.labelsToAxisSpacingY = 5
        chartSettings.axisTitleLabelsToLabelsSpacing = 4
        chartSettings.axisStrokeWidth = 0.2
        chartSettings.spacingBetweenAxesX = 8
        chartSettings.spacingBetweenAxesY = 8
        return chartSettings
    }
`
But the chart looks even worse it gets squashed to one single line.

![simulator screen shot 9 mar 2016 23 18 29](https://cloud.githubusercontent.com/assets/315964/13654037/41674dc6-e64d-11e5-8c21-667421c29762.png)

**Comment by i-schuetz** [comment]
Probably the frame height is not calculated at the point you initialise the chart. Please take a look at [this gist](https://gist.github.com/i-schuetz/f6e285eb0c86bb831510), which addresses some issues with autolayout. Alternatively to `viewDidLayoutSubviews` you could also use `viewDidAppear` to initialise the chart, in which you don't have to use a `didLayout` flag (since it's called only once), but this is called a bit later and can cause a noticeable delay.

**Comment by robomotic** [comment]
Interesting, using the same approach I am getting a crash now in the constructor of Chart.  I will try to first replicate the exact code and then add a stack view .

**Comment by i-schuetz** [comment]
Slightly? If the settings and frame are correct the chart uses the available space. If you post your full code (or better upload a project, to have the interface files also) I can give it a look.

**Comment by robomotic** [comment]
Sure I made a simple project just with the stack view 
[StackChart.zip](https://github.com/i-schuetz/SwiftCharts/files/169672/StackChart.zip)

Feel free to put it as an example in your github.
Thanks in advance!

**Comment by i-schuetz** [comment]
No problem. If you don't mind please upload this as source in your Github. I'm a bit wary of downloading attachments here. Thanks!

**Comment by robomotic** [comment]
Sure here we go:
https://github.com/robomotic/StackChart

**Comment by i-schuetz** [comment]
Ok, there were several issues. https://github.com/i-schuetz/StackChart/commit/88b6c41d141d843ad731702d3f84b7c612b4a502 I don't have time to add this as an example but a pull request would be welcome. Many people have asked about autolayout so this would be very useful. You would have to tidy the code up a bit.
