### ISSUE TITLE
Change alignment of the label on y axis

### ISSUE THREAD

**Issue by marcinwlodarczyk** [i-schuetz/SwiftCharts#99]
Hi,
I want to display an yAxis inside chart area (on the right hand side of Y axis). I can achieve this by setting  chartSettings.leading to e.g. -5
But the problem is that by default label text is aligned to right because it's displayed on the left of Y axis.
The responsible for this is ChartAxisYLowLayerDefault class and func labelsX(offset offset: CGFloat, labelWidth: CGFloat) -> CGFloat which sets label x to labelsXRight - labelWidth.
The solution would be to return just labelsXRight.

Do you see any other (better) solution? If not do you mind a pull request with an alignment configuration on the ChartLabelSettings?

Best,
Marcin

**Comment by marcinwlodarczyk** [comment]
I will have to create another layer based on ChartCoordsSpaceRightBottomSingleAxis and it will work.
What is the best way to set margin? Is it only labelsToAxisSpacingY on ChartSettings ?

**Comment by marcinwlodarczyk** [comment]
And how to get rid of leading margin for the entire chart (in ChartCoordsSpaceLeftBottomSingleAxis mode). I'm setting leading = -37 on ChartSettings however this is a magic number that depends on many other things (like label font)  - I need my chart to take entire view it's added to (left and right margins equal to 0).

**Comment by i-schuetz** [comment]
I was thinking about an axis offset setting, but just noticed this is not complete. `ChartAxisSettings` has e.g. `screenLeading` but it's not used, and also it's initialised with the leading setting from the chart settings which is not what we need... so this would have to be implemented. With this offset setting you would be able to move the complete axis to the left (it could also be used to move axes a bit outside, for example). Or you can implement the label alignment setting, both are useful and welcome as pull request.

The leading margin disappears if chart leading is 0 and there's no left axis, if there's left axis it will be max label width + related axis settings. To remove the axis space ideally you would use the axis width (`-xAxis.rect.width`) to set `leading` but the chart settings are used to calculate the axes rects so this is not possible. But I think you can also offset the innerFrame calculated by coords space by this value. This is off the top of my head, if it doesn't work glad to dig further. This is a bit finicky and could be improved by e.g. implementing a setting to not reserve space for the axis content.
